package com.marketlabs.pulse.network.model.stocks

// Generated by Claude Code.

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 💡 THOUGHT PROCESS:
 * Response body for `GET /stocks/{symbol}/detail` — everything the backend moved out of the
 * small preview doc, fetched only when the user opens a stock. Replaces `NetworkStockDeepStudy`
 * alongside `NetworkStockPreview.kt`; see that file's header for the preview/detail split
 * rationale. Field names/nesting here are taken directly from `stockAnalysisEngine.ts`'s
 * `detailDoc` object literal, not just the sample JSON, so optionality matches what the backend
 * actually guarantees (`?? null` in the engine) rather than what one sample happened to contain.
 *
 * Three fields changed shape from the old deep-study payload and are easy to miss in review:
 * `executive_thesis.institutional_order_flow` -> `what_the_numbers_say`; the old top-level
 * `battleground_levels` -> `levels` (plus two new fields, `fair_value_anchor`/`commentary`);
 * and `context_vault.forward_outlook_projection` was dropped in favor of a code-authored
 * `event_log[]` (see `memory.ts` — this is written by CODE and read by the model, never the
 * reverse, so it can't drift into speculation the way a model-authored outlook field could).
 */
@JsonClass(generateAdapter = true)
data class NetworkStockDetail(
    val symbol: String? = null,

    @Json(name = "detail_version")
    val detailVersion: Long? = null,

    @Json(name = "analysis_date")
    val analysisDate: String? = null,

    @Json(name = "technical_indicators")
    val technicalIndicators: NetworkTechnicalIndicators? = null,

    val levels: NetworkLevels? = null,

    @Json(name = "setup_signals")
    val setupSignals: List<NetworkSetupSignal>? = null,

    @Json(name = "setup_confirming")
    val setupConfirming: List<String>? = null,

    @Json(name = "setup_conflicting")
    val setupConflicting: List<String>? = null,

    /** Same chip vocabulary as the preview's `condition_chips`, but WITH plain-English `meaning`. */
    @Json(name = "condition_labels")
    val conditionLabels: List<NetworkConditionLabel>? = null,

    @Json(name = "watch_list")
    val watchList: List<NetworkWatchItem>? = null,

    /** Snapshot copied from `market_fundamentals/{symbol}` at analysis time — a separate backend domain this app doesn't otherwise read. */
    val fundamentals: NetworkFundamentals? = null,

    val macro: NetworkMacro? = null,

    @Json(name = "technical_read")
    val technicalRead: String? = null,

    @Json(name = "not_covered")
    val notCovered: String? = null,

    val scenarios: List<NetworkScenario>? = null,

    val considerations: List<String>? = null,

    @Json(name = "executive_thesis")
    val executiveThesis: NetworkExecutiveThesis? = null,

    @Json(name = "top_news_stream")
    val topNewsStream: List<NetworkStockNewsItem>? = null,

    @Json(name = "context_vault")
    val contextVault: NetworkContextVault? = null,

    /** Forward-call track record (forwardCalls.ts) — falsifiable calls the AI makes, scored automatically against real closes. */
    val calls: NetworkCallRecord? = null,

    /** Epoch millis — this is the field the app actually uses for "as of" display, not `last_updated`. */
    val timestamp: Long? = null

    // 💡 `last_updated` (a pre-formatted display string) exists in the raw response but is
    // deliberately NOT modeled here — see the matching note on `NetworkStockPreview.timestamp`.
)

/** Every computed technical number (technicals.ts). */
@JsonClass(generateAdapter = true)
data class NetworkTechnicalIndicators(
    val rsi: Double? = null,
    val sma20: Double? = null,
    val sma50: Double? = null,
    val sma200: Double? = null,

    /** One of BULLISH | BEARISH | NEUTRAL. */
    @Json(name = "macd_signal")
    val macdSignal: String? = null,

    @Json(name = "macd_histogram")
    val macdHistogram: Double? = null,

    @Json(name = "bars_since_macd_cross")
    val barsSinceMacdCross: Int? = null,

    @Json(name = "latest_volume")
    val latestVolume: Long? = null,

    @Json(name = "avg_volume_20d")
    val avgVolume20d: Long? = null,

    @Json(name = "atr_pct")
    val atrPct: Double? = null,

    @Json(name = "realized_vol")
    val realizedVol: Double? = null,

    @Json(name = "vol_percentile")
    val volPercentile: Int? = null,

    val rvol: Double? = null,

    @Json(name = "up_down_volume_ratio")
    val upDownVolumeRatio: Double? = null,

    @Json(name = "dist_sma20_pct")
    val distSma20Pct: Double? = null,

    @Json(name = "dist_sma50_pct")
    val distSma50Pct: Double? = null,

    @Json(name = "dist_sma200_pct")
    val distSma200Pct: Double? = null,

    @Json(name = "high_52w")
    val high52w: Double? = null,

    @Json(name = "low_52w")
    val low52w: Double? = null,

    @Json(name = "range_position_52w")
    val rangePosition52w: Double? = null,

    val returns: NetworkReturns? = null
)

@JsonClass(generateAdapter = true)
data class NetworkReturns(
    val d1: Double? = null,
    val w1: Double? = null,
    val m1: Double? = null,
    val m3: Double? = null,
    val m6: Double? = null,
    val y1: Double? = null
)

/** Pivots + volume-at-price zones. Replaces the old top-level `battleground_levels`. */
@JsonClass(generateAdapter = true)
data class NetworkLevels(
    val support: Double? = null,
    val resistance: Double? = null,

    @Json(name = "accumulation_zone_low")
    val accumulationZoneLow: Double? = null,

    @Json(name = "distribution_zone_high")
    val distributionZoneHigh: Double? = null,

    @Json(name = "fair_value_anchor")
    val fairValueAnchor: Double? = null,

    val commentary: String? = null
)

@JsonClass(generateAdapter = true)
data class NetworkSetupSignal(
    val label: String? = null,

    /** One of BULLISH | BEARISH | NEUTRAL. */
    val direction: String? = null
)

/** Same shape as `NetworkConditionChip` plus `meaning` — the detail doc's reader-facing explanation of each label. */
@JsonClass(generateAdapter = true)
data class NetworkConditionLabel(
    val label: String? = null,
    val meaning: String? = null,

    /** One of BULLISH | BEARISH | NEUTRAL. */
    val direction: String? = null,

    /** One of MOMENTUM | TREND | VOLUME | VOLATILITY | VALUATION | EVENT. */
    val category: String? = null,

    @Json(name = "qualified_by")
    val qualifiedBy: String? = null
)

@JsonClass(generateAdapter = true)
data class NetworkWatchItem(
    val kind: String? = null,
    val text: String? = null,

    /** One of HIGH | MEDIUM | LOW. */
    val urgency: String? = null
)

/** Snapshot copied verbatim from `market_fundamentals/{symbol}` (fundamentalsEngine.ts) at analysis time. */
@JsonClass(generateAdapter = true)
data class NetworkFundamentals(
    @Json(name = "analyst_count")
    val analystCount: Int? = null,

    val beta: Double? = null,

    @Json(name = "capex_to_ocf_pct")
    val capexToOcfPct: Double? = null,

    @Json(name = "consensus_strength_pct")
    val consensusStrengthPct: Double? = null,

    @Json(name = "current_ratio")
    val currentRatio: Double? = null,

    @Json(name = "debt_to_equity")
    val debtToEquity: Double? = null,

    /** Only present for dividend-paying symbols; null/absent otherwise. */
    @Json(name = "dividend_yield_pct")
    val dividendYieldPct: Double? = null,

    @Json(name = "earnings_eps_estimate")
    val earningsEpsEstimate: Double? = null,

    @Json(name = "earnings_yield_pct")
    val earningsYieldPct: Double? = null,

    @Json(name = "eps_growth_yoy_pct")
    val epsGrowthYoyPct: Double? = null,

    @Json(name = "ev_ebitda")
    val evEbitda: Double? = null,

    @Json(name = "ev_revenue")
    val evRevenue: Double? = null,

    /** Free cash flow / market cap from Yahoo's dollar figures — NOT the inverse of Finnhub's price-to-FCF ratio. */
    @Json(name = "fcf_yield_pct")
    val fcfYieldPct: Double? = null,

    @Json(name = "fetched_at")
    val fetchedAt: Long? = null,

    @Json(name = "forward_eps")
    val forwardEps: Double? = null,

    @Json(name = "free_cash_flow")
    val freeCashFlow: Double? = null,

    @Json(name = "fundamentals_version")
    val fundamentalsVersion: Int? = null,

    @Json(name = "gross_margin_pct")
    val grossMarginPct: Double? = null,

    @Json(name = "last_earnings_date")
    val lastEarningsDate: String? = null,

    @Json(name = "market_cap")
    val marketCap: Double? = null,

    @Json(name = "next_earnings_date")
    val nextEarningsDate: String? = null,

    /** True when Yahoo only supplied an estimated window rather than a confirmed date. */
    @Json(name = "next_earnings_is_estimate")
    val nextEarningsIsEstimate: Boolean? = null,

    @Json(name = "operating_cash_flow")
    val operatingCashFlow: Double? = null,

    @Json(name = "operating_margin_pct")
    val operatingMarginPct: Double? = null,

    @Json(name = "pe_forward")
    val peForward: Double? = null,

    @Json(name = "pe_history_5y")
    val peHistory5y: List<Double>? = null,

    @Json(name = "pe_median_5y")
    val peMedian5y: Double? = null,

    @Json(name = "pe_percentile_5y")
    val pePercentile5y: Double? = null,

    @Json(name = "pe_spread")
    val peSpread: Double? = null,

    @Json(name = "pe_trailing")
    val peTrailing: Double? = null,

    @Json(name = "pe_vs_median_pct")
    val peVsMedianPct: Double? = null,

    @Json(name = "peg_ratio")
    val pegRatio: Double? = null,

    @Json(name = "price_to_book")
    val priceToBook: Double? = null,

    @Json(name = "price_to_sales")
    val priceToSales: Double? = null,

    @Json(name = "profit_margin_pct")
    val profitMarginPct: Double? = null,

    /** e.g. "strong_buy". Free-form string, not an enum — same reasoning as `technical_setup`. */
    @Json(name = "recommendation_key")
    val recommendationKey: String? = null,

    @Json(name = "recommendation_mean")
    val recommendationMean: Double? = null,

    @Json(name = "revenue_growth_yoy_pct")
    val revenueGrowthYoyPct: Double? = null,

    @Json(name = "roa_pct")
    val roaPct: Double? = null,

    @Json(name = "roe_pct")
    val roePct: Double? = null,

    @Json(name = "roic_pct")
    val roicPct: Double? = null,

    /** e.g. ["yahoo", "finnhub"]. */
    val sources: List<String>? = null,

    val symbol: String? = null,

    @Json(name = "target_dispersion_pct")
    val targetDispersionPct: Double? = null,

    @Json(name = "target_high")
    val targetHigh: Double? = null,

    @Json(name = "target_low")
    val targetLow: Double? = null,

    @Json(name = "target_mean")
    val targetMean: Double? = null,

    @Json(name = "total_cash")
    val totalCash: Double? = null,

    @Json(name = "total_debt")
    val totalDebt: Double? = null,

    @Json(name = "trailing_eps")
    val trailingEps: Double? = null
)

/** How this stock links to macro conditions — rate correlation and excess return vs. its benchmark. */
@JsonClass(generateAdapter = true)
data class NetworkMacro(
    val benchmark: String? = null,

    @Json(name = "excess_earnings_yield_pct")
    val excessEarningsYieldPct: Double? = null,

    @Json(name = "excess_return_21d_pct")
    val excessReturn21dPct: Double? = null,

    @Json(name = "excess_return_63d_pct")
    val excessReturn63dPct: Double? = null,

    @Json(name = "rate_correlation_63d")
    val rateCorrelation63d: Double? = null,

    /** e.g. NEGLIGIBLE, or a NEGATIVE/POSITIVE-prefixed sensitivity label. Free-form string. */
    @Json(name = "rate_sensitivity")
    val rateSensitivity: String? = null,

    @Json(name = "risk_free_10y_pct")
    val riskFree10yPct: Double? = null
)

/** One if/then path. Two per symbol (bullish + bearish), never a probability attached. */
@JsonClass(generateAdapter = true)
data class NetworkScenario(
    /** One of BULLISH | BEARISH. */
    val direction: String? = null,

    @Json(name = "what_it_would_mean")
    val whatItWouldMean: String? = null,

    @Json(name = "what_would_need_to_happen")
    val whatWouldNeedToHappen: String? = null
)

/** The AI's three analytical paragraphs. `what_the_numbers_say` replaces the old `institutional_order_flow`. */
@JsonClass(generateAdapter = true)
data class NetworkExecutiveThesis(
    @Json(name = "macro_transmission_vector")
    val macroTransmissionVector: String? = null,

    @Json(name = "what_the_numbers_say")
    val whatTheNumbersSay: String? = null,

    @Json(name = "valuation_context")
    val valuationContext: String? = null
)

/**
 * A single AI-enriched news item. `forward_implication`/`impact_magnitude` are new; the old
 * `desk_positioning_shift` field is gone.
 */
@JsonClass(generateAdapter = true)
data class NetworkStockNewsItem(
    val headline: String? = null,

    @Json(name = "source_date")
    val sourceDate: String? = null,

    val url: String? = null,

    @Json(name = "article_synthesis")
    val articleSynthesis: String? = null,

    @Json(name = "transmission_mechanism")
    val transmissionMechanism: String? = null,

    @Json(name = "forward_implication")
    val forwardImplication: String? = null,

    /** One of HIGH | MEDIUM | LOW. */
    @Json(name = "impact_magnitude")
    val impactMagnitude: String? = null
)

/**
 * Rolling memory carried forward between runs. `event_log` is CODE-authored (memory.ts) and fed
 * back to the model as input, never the reverse — replaces the old model-authored
 * `forward_outlook_projection`.
 */
@JsonClass(generateAdapter = true)
data class NetworkContextVault(
    @Json(name = "thirty_day_trend_timeline")
    val thirtyDayTrendTimeline: String? = null,

    @Json(name = "event_log")
    val eventLog: List<NetworkEventLogItem>? = null
)

@JsonClass(generateAdapter = true)
data class NetworkEventLogItem(
    val date: String? = null,

    /** One of BULLISH | BEARISH | NEUTRAL. */
    val direction: String? = null,

    /** e.g. CROSS_ABOVE_MA, VOLUME_SPIKE, RSI_REGIME, MACD_CROSS, FLOW_SHIFT, SETUP_CHANGE, NEW_52W_HIGH, BASELINE. Free-form string — new kinds can appear without a client change. */
    val kind: String? = null,

    val text: String? = null
)

/** Forward-call track record (forwardCalls.ts) — falsifiable, code-scored, never self-assessed by the model. */
@JsonClass(generateAdapter = true)
data class NetworkCallRecord(
    val open: List<NetworkForwardCall>? = null,
    val resolved: List<NetworkForwardCall>? = null,
    val stats: NetworkCallStats? = null
)

@JsonClass(generateAdapter = true)
data class NetworkForwardCall(
    val id: String? = null,

    @Json(name = "made_on")
    val madeOn: String? = null,

    @Json(name = "resolve_date")
    val resolveDate: String? = null,

    /** One of CLOSE_ABOVE | CLOSE_BELOW | HOLDS_ABOVE | HOLDS_BELOW | STAYS_WITHIN. */
    val predicate: String? = null,

    val level: Double? = null,

    /** Only ever set for STAYS_WITHIN; null for every other predicate. */
    @Json(name = "level_upper")
    val levelUpper: Double? = null,

    @Json(name = "price_when_made")
    val priceWhenMade: Double? = null,

    val statement: String? = null,
    val basis: String? = null,

    /** One of OPEN | HELD | FAILED | EXPIRED_UNRESOLVED. */
    val status: String? = null,

    @Json(name = "resolved_on")
    val resolvedOn: String? = null,

    @Json(name = "resolved_price")
    val resolvedPrice: Double? = null,

    @Json(name = "outcome_note")
    val outcomeNote: String? = null
)

@JsonClass(generateAdapter = true)
data class NetworkCallStats(
    @Json(name = "total_resolved")
    val totalResolved: Int? = null,

    val held: Int? = null,
    val failed: Int? = null,

    /** Null below 5 judged calls — the backend treats the rate as noise under that threshold. */
    @Json(name = "hit_rate_pct")
    val hitRatePct: Int? = null,

    @Json(name = "by_basis")
    val byBasis: Map<String, NetworkCallBasisStat>? = null
)

@JsonClass(generateAdapter = true)
data class NetworkCallBasisStat(
    val n: Int? = null,
    val held: Int? = null
)
