package com.marketlabs.pulse.storage.database.converters

// Generated by Claude Code.

import androidx.room.TypeConverter
import com.marketlabs.pulse.storage.model.stocks.DomainBattlegroundLevels
import com.marketlabs.pulse.storage.model.stocks.DomainContextVault
import com.marketlabs.pulse.storage.model.stocks.DomainExecutiveThesis
import com.marketlabs.pulse.storage.model.stocks.DomainStockNewsItem
import com.marketlabs.pulse.storage.model.stocks.DomainTechnicalIndicators
import com.squareup.moshi.Moshi
import com.squareup.moshi.Types
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory

/**
 * Room can't natively persist nested data classes, so each AI-enriched nested object on
 * `StockEntity` is (de)serialized to/from a JSON string column — same approach as
 * `IndicatorsConverters` for the indicators domain and `NewsConverters` for its article list.
 */
class StocksConverters {
    private val moshi = Moshi.Builder().add(KotlinJsonAdapterFactory()).build()

    // --- Technical Indicators ---
    @TypeConverter
    fun fromTechnicalIndicators(data: DomainTechnicalIndicators?): String? =
        data?.let { moshi.adapter(DomainTechnicalIndicators::class.java).toJson(it) }

    @TypeConverter
    fun toTechnicalIndicators(json: String?): DomainTechnicalIndicators? =
        json?.let { moshi.adapter(DomainTechnicalIndicators::class.java).fromJson(it) }

    // --- Executive Thesis ---
    @TypeConverter
    fun fromExecutiveThesis(data: DomainExecutiveThesis?): String? =
        data?.let { moshi.adapter(DomainExecutiveThesis::class.java).toJson(it) }

    @TypeConverter
    fun toExecutiveThesis(json: String?): DomainExecutiveThesis? =
        json?.let { moshi.adapter(DomainExecutiveThesis::class.java).fromJson(it) }

    // --- Top News Stream (List) ---
    private val newsListType = Types.newParameterizedType(List::class.java, DomainStockNewsItem::class.java)
    private val newsListAdapter = moshi.adapter<List<DomainStockNewsItem>>(newsListType)

    @TypeConverter
    fun fromTopNewsStream(data: List<DomainStockNewsItem>?): String? =
        data?.let { newsListAdapter.toJson(it) }

    @TypeConverter
    fun toTopNewsStream(json: String?): List<DomainStockNewsItem>? =
        json?.let { newsListAdapter.fromJson(it) }

    // --- Battleground Levels ---
    @TypeConverter
    fun fromBattlegroundLevels(data: DomainBattlegroundLevels?): String? =
        data?.let { moshi.adapter(DomainBattlegroundLevels::class.java).toJson(it) }

    @TypeConverter
    fun toBattlegroundLevels(json: String?): DomainBattlegroundLevels? =
        json?.let { moshi.adapter(DomainBattlegroundLevels::class.java).fromJson(it) }

    // --- Context Vault ---
    @TypeConverter
    fun fromContextVault(data: DomainContextVault?): String? =
        data?.let { moshi.adapter(DomainContextVault::class.java).toJson(it) }

    @TypeConverter
    fun toContextVault(json: String?): DomainContextVault? =
        json?.let { moshi.adapter(DomainContextVault::class.java).fromJson(it) }
}
