package com.marketlabs.pulse.ui.screens.tutorials

// Generated by Claude Code.

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.ui.components.DocumentSectionsScreen
import com.marketlabs.pulse.ui.theme.MarketPulseTheme

/** spec-20260915-compliance-disclaimers.md §6.1. Three flowing paragraphs, no per-paragraph
 * headings -- rendered as blank-heading sections of `DocumentSectionsScreen`. */
@Composable
fun TutorialsHowItWorksScreen(onNavigateUp: () -> Unit) {
    val sections = listOf(
        "" to stringResource(id = R.string.tutorials_how_it_works_paragraph_1),
        "" to stringResource(id = R.string.tutorials_how_it_works_paragraph_2),
        "" to stringResource(id = R.string.tutorials_how_it_works_paragraph_3)
    )

    DocumentSectionsScreen(
        title = stringResource(id = R.string.tutorials_item_how_it_works),
        sections = sections,
        onNavigateUp = onNavigateUp
    )
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewTutorialsHowItWorksScreenLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        TutorialsHowItWorksScreen(onNavigateUp = {})
    }
}

@Preview(name = "Dark", showBackground = true)
@Composable
private fun PreviewTutorialsHowItWorksScreenDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        TutorialsHowItWorksScreen(onNavigateUp = {})
    }
}
