package com.marketlabs.pulse.ui.screens.tutorials

// Generated by Claude Code.

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.ui.components.DocumentSectionsScreen
import com.marketlabs.pulse.ui.theme.MarketPulseTheme

/** spec-20260915-compliance-disclaimers.md §6.4. */
@Composable
fun TutorialsAiContentScreen(onNavigateUp: () -> Unit) {
    val sections = listOf(
        "" to stringResource(id = R.string.tutorials_ai_content_intro),
        stringResource(id = R.string.tutorials_ai_content_limitations_title) to
            stringResource(id = R.string.tutorials_ai_content_limitations_body),
        stringResource(id = R.string.tutorials_ai_content_mitigations_title) to
            stringResource(id = R.string.tutorials_ai_content_mitigations_body),
        stringResource(id = R.string.tutorials_ai_content_what_you_should_do_title) to
            stringResource(id = R.string.tutorials_ai_content_what_you_should_do_body)
    )

    DocumentSectionsScreen(
        title = stringResource(id = R.string.tutorials_item_ai_content),
        sections = sections,
        onNavigateUp = onNavigateUp
    )
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewTutorialsAiContentScreenLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        TutorialsAiContentScreen(onNavigateUp = {})
    }
}

@Preview(name = "Dark", showBackground = true)
@Composable
private fun PreviewTutorialsAiContentScreenDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        TutorialsAiContentScreen(onNavigateUp = {})
    }
}
