package com.marketlabs.pulse.ui.screens.tutorials

// Generated by Claude Code.

import androidx.annotation.StringRes

/** Flat data classes per this repo convention -- no `isLoading`/`errorMessage`, same reasoning as
 * `SettingsUiState`: the underlying source (`MetricGlossaryProvider`'s in-memory bundle) is a
 * synchronous local-asset read with no failure mode worth surfacing. */
data class TutorialsGaugesUiState(
    val categories: List<TutorialsGaugeCategoryUi> = emptyList()
)

data class TutorialsGaugeCategoryUi(
    @param:StringRes val titleRes: Int,
    val gauges: List<TutorialsGaugeUi>
)

data class TutorialsGaugeUi(
    @param:StringRes val titleRes: Int,
    val whatItIs: String
)
