package com.marketlabs.pulse.ui.screens.tutorials

// Generated by Claude Code.

import androidx.lifecycle.ViewModel
import com.marketlabs.pulse.core.glossary.MetricGlossaryProvider
import dagger.hilt.android.lifecycle.HiltViewModel
import javax.inject.Inject

/**
 * spec-20260915-compliance-disclaimers.md §6.2. `uiState` is a plain `val`, not a `StateFlow` --
 * `MetricGlossaryProvider.getAll()` is a synchronous read of an already-in-memory bundle (see that
 * provider's own doc comment: loaded once, cached for the process lifetime), so there's nothing
 * asynchronous here to stream. Resolved once at construction time, same as `MetricDetailViewModel`'s
 * own synchronous `glossaryProvider.get(metricId)` lookup, just for every entry `TutorialsGaugesCatalog`
 * lists instead of one.
 */
@HiltViewModel
class TutorialsGaugesViewModel @Inject constructor(
    glossaryProvider: MetricGlossaryProvider
) : ViewModel() {

    val uiState: TutorialsGaugesUiState = run {
        val allEntries = glossaryProvider.getAll()
        val categories = TutorialsGaugesCatalog.categories.mapNotNull { category ->
            val gauges = category.metricIds.mapNotNull { metricId ->
                val entry = allEntries[metricId] ?: return@mapNotNull null
                val titleRes = TutorialsGaugesCatalog.titleResFor(metricId) ?: return@mapNotNull null
                TutorialsGaugeUi(titleRes = titleRes, whatItIs = entry.whatItIs)
            }
            if (gauges.isEmpty()) null else TutorialsGaugeCategoryUi(titleRes = category.titleRes, gauges = gauges)
        }
        TutorialsGaugesUiState(categories = categories)
    }
}
