package com.marketlabs.pulse.ui.screens.tutorials

// Generated by Claude Code.

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.ui.components.DocumentSectionsScreen
import com.marketlabs.pulse.ui.components.tutorials.SentimentGaugesLivePreview
import com.marketlabs.pulse.ui.components.tutorials.SmaExtensionDiagram
import com.marketlabs.pulse.ui.components.tutorials.YieldCurveDiagram
import com.marketlabs.pulse.ui.theme.MarketPulseTheme

/**
 * spec-20260915-compliance-disclaimers.md §6.3 -- flagged in the spec as the highest-risk static
 * content in the document: every explanation stays descriptive of what market participants
 * generally do/believe ("historically interpreted as," "market participants often view this as"),
 * never prescriptive of what the reader should do. NEEDS A HUMAN REVIEW PASS before shipping, same
 * as AI-generated content gets, even though this is static -- flagging per the spec's own
 * instruction rather than self-certifying it.
 *
 * Maintenance note (per the spec): this section names specific gauges and their inputs (NAAIM/DIX/
 * net liquidity for Posture; AAII/COT/short interest for Positioning; the FRED series for Macro
 * Vitals) -- it goes stale if any of those inputs change. No automated check for that exists; a
 * human needs to remember to revisit this file when a gauge's methodology changes.
 */
@Composable
fun TutorialsMarketConceptsScreen(onNavigateUp: () -> Unit) {
    val sections = listOf(
        stringResource(id = R.string.tutorials_market_concepts_sentiment_title) to
            stringResource(id = R.string.tutorials_market_concepts_sentiment_body),
        stringResource(id = R.string.tutorials_market_concepts_macro_title) to
            stringResource(id = R.string.tutorials_market_concepts_macro_body),
        stringResource(id = R.string.tutorials_market_concepts_technical_title) to
            stringResource(id = R.string.tutorials_market_concepts_technical_body),
        stringResource(id = R.string.tutorials_market_concepts_valuation_title) to
            stringResource(id = R.string.tutorials_market_concepts_valuation_body)
    )

    // spec-20260917-content-refinement.md Pass 4, updated 2026-09: the real Fear & Greed/Put-Call/
    // COT/AAII widgets sit after Sentiment (index 0, replacing the hand-drawn SentimentGaugesDiagram
    // -- see SentimentGaugesLivePreview's own doc comment for why), D1 after Macro (index 1), D2
    // after Technical (index 2) -- matches the `sections` order right above.
    DocumentSectionsScreen(
        title = stringResource(id = R.string.tutorials_item_market_concepts),
        sections = sections,
        onNavigateUp = onNavigateUp,
        diagrams = mapOf(
            0 to { SentimentGaugesLivePreview() },
            1 to { YieldCurveDiagram() },
            2 to { SmaExtensionDiagram() }
        )
    )
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewTutorialsMarketConceptsScreenLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        TutorialsMarketConceptsScreen(onNavigateUp = {})
    }
}

@Preview(name = "Dark", showBackground = true)
@Composable
private fun PreviewTutorialsMarketConceptsScreenDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        TutorialsMarketConceptsScreen(onNavigateUp = {})
    }
}
