package com.marketlabs.pulse.ui.screens.tutorials

// Generated by Claude Code.

import androidx.compose.runtime.Composable
import androidx.hilt.navigation.compose.hiltViewModel

@Composable
fun TutorialsGaugesRoute(
    onNavigateUp: () -> Unit,
    viewModel: TutorialsGaugesViewModel = hiltViewModel()
) {
    TutorialsGaugesScreen(
        uiState = viewModel.uiState,
        onNavigateUp = onNavigateUp
    )
}
