package com.marketlabs.pulse.ui.components.bottomSheet

// Generated by Claude Code.

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.navigationBars
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.windowInsetsBottomHeight
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.Text
import androidx.compose.material3.rememberModalBottomSheetState
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.core.glossary.StockAnalysisGlossaryProvider
import com.marketlabs.pulse.ui.components.PulseCard
import com.marketlabs.pulse.ui.components.PulseCardStyle
import com.marketlabs.pulse.ui.theme.MarketPulseTheme

/**
 * A `(display label, glossary key)` pair -- the label is what a section already renders (via
 * `stringResource`), the key looks up `StockAnalysisGlossaryProvider`. `definitionOverride` is an
 * escape hatch for the rare definition that needs a runtime value baked in (Macro's "Excess
 * Return" explainer naming the actual benchmark, e.g. "SPY", instead of the glossary's generic
 * static "its benchmark") -- leave it `null` to use the provider's definition as-is, which is what
 * every other section's entries already do.
 */
data class GlossaryEntry(val label: String, val term: String, val definitionOverride: String? = null)

/**
 * Same `ModalBottomSheet` shell/styling `MarketGlossaryBottomSheet`/`IndicatorDetailSheet` already
 * use elsewhere in the app, but listing every metric a single Detail section (Key Levels,
 * Fundamentals, Macro, ...) currently has data for -- one tap on that section's info icon opens
 * this instead of a per-metric tooltip. `entries` should only include metrics the section is
 * actually rendering (a caller passes the same non-null-filtered list it used to lay out its own
 * stats), not the glossary's full term list, so this never shows a definition for something not
 * currently on screen.
 *
 * 2026-09-07: each entry now renders as its own `PulseCard(DATA)`, `titleSmall`/`bodySmall` (was a
 * plain `Column`, `titleMedium`/`bodyMedium`) -- matches `MetricDetailScreen`'s `BandRow`, the same
 * "list of terms" card shape `MarketGlossaryBottomSheet`'s own term cards were fixed to match a day
 * earlier (see `card-heading-conventions.md`'s Twelfth/Fifteenth steps). No accent border/"CURRENT"
 * badge here, unlike `BandRow` -- this sheet has no single current value to highlight (it's every
 * metric a section renders, not one reading against a set of bands), so only the card shape and
 * type scale carry over, not the current-highlight treatment.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun StockAnalysisGlossaryBottomSheet(
    title: String,
    entries: List<GlossaryEntry>,
    onDismiss: () -> Unit
) {
    val sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)
    val paddingExtraLarge = dimensionResource(id = R.dimen.padding_extra_large)
    val paddingLarge = dimensionResource(id = R.dimen.padding_large)
    val paddingSmall = dimensionResource(id = R.dimen.padding_small)
    val context = LocalContext.current

    ModalBottomSheet(
        onDismissRequest = onDismiss,
        sheetState = sheetState,
        // 💡 colorScheme.surface, not surfaceContainerHighest -- this sheet now nests
        // `PulseCard(DATA)` per entry (see the doc comment above), and this app's simplified
        // surface ramp resolves `surfaceContainerHighest`/`surfaceVariant` to the literal same
        // value as `PulseCard`'s own DATA fill (see card-heading-conventions.md's Thirteenth
        // step) -- a card sitting on a `surfaceContainerHighest` sheet has zero contrast against
        // it. `colorScheme.surface` is the one remaining token distinct from both `background`
        // (the screen behind the sheet) and `surfaceVariant` (the card's own fill).
        containerColor = MaterialTheme.colorScheme.surface
    ) {
        LazyColumn(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = paddingExtraLarge)
        ) {
            item {
                Text(
                    text = title,
                    style = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.Bold),
                    color = MaterialTheme.colorScheme.onBackground,
                    modifier = Modifier.padding(bottom = paddingLarge)
                )
            }

            items(entries) { entry ->
                val definition = entry.definitionOverride ?: StockAnalysisGlossaryProvider.definitionFor(context, entry.term)
                if (definition != null) {
                    PulseCard(style = PulseCardStyle.DATA, modifier = Modifier.fillMaxWidth()) {
                        Column(modifier = Modifier.padding(paddingLarge)) {
                            Text(
                                text = entry.label,
                                style = MaterialTheme.typography.titleSmall.copy(fontWeight = FontWeight.Bold),
                                color = MaterialTheme.colorScheme.onSurface
                            )
                            Text(
                                text = definition,
                                style = MaterialTheme.typography.bodySmall,
                                color = MaterialTheme.colorScheme.onSurfaceVariant,
                                modifier = Modifier.padding(top = paddingSmall)
                            )
                        }
                    }
                    Spacer(modifier = Modifier.height(paddingSmall))
                }
            }

            item { Spacer(modifier = Modifier.windowInsetsBottomHeight(WindowInsets.navigationBars)) }
        }
    }
}

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewStockAnalysisGlossaryBottomSheet() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        StockAnalysisGlossaryBottomSheet(
            title = "Key Levels",
            entries = listOf(
                GlossaryEntry(
                    label = "ATR",
                    term = "ATR",
                    definitionOverride = "Average True Range -- a measure of how much a stock typically moves per day."
                ),
                GlossaryEntry(
                    label = "Distance from 200-day SMA",
                    term = "DIST_SMA200",
                    definitionOverride = "How far the current price sits above or below its 200-day moving average."
                )
            ),
            onDismiss = {}
        )
    }
}
