package com.marketlabs.pulse.ui.components.bottomSheet

// Generated by Claude Code.

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.navigationBars
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.windowInsetsBottomHeight
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.Text
import androidx.compose.material3.rememberModalBottomSheetState
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.text.font.FontWeight
import com.marketlabs.pulse.R
import com.marketlabs.pulse.core.glossary.StockAnalysisGlossaryProvider

/**
 * A `(display label, glossary key)` pair -- the label is what a section already renders (via
 * `stringResource`), the key looks up `StockAnalysisGlossaryProvider`. `definitionOverride` is an
 * escape hatch for the rare definition that needs a runtime value baked in (Macro's "Excess
 * Return" explainer naming the actual benchmark, e.g. "SPY", instead of the glossary's generic
 * static "its benchmark") -- leave it `null` to use the provider's definition as-is, which is what
 * every other section's entries already do.
 */
data class GlossaryEntry(val label: String, val term: String, val definitionOverride: String? = null)

/**
 * Same `ModalBottomSheet` shell/styling `MarketGlossaryBottomSheet`/`IndicatorDetailSheet` already
 * use elsewhere in the app, but listing every metric a single Detail section (Key Levels,
 * Fundamentals, Macro, ...) currently has data for -- one tap on that section's info icon opens
 * this instead of a per-metric tooltip. `entries` should only include metrics the section is
 * actually rendering (a caller passes the same non-null-filtered list it used to lay out its own
 * stats), not the glossary's full term list, so this never shows a definition for something not
 * currently on screen.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun StockAnalysisGlossaryBottomSheet(
    title: String,
    entries: List<GlossaryEntry>,
    onDismiss: () -> Unit
) {
    val sheetState = rememberModalBottomSheetState(skipPartiallyExpanded = true)
    val paddingExtraLarge = dimensionResource(id = R.dimen.padding_extra_large)
    val paddingLarge = dimensionResource(id = R.dimen.padding_large)
    val paddingSmall = dimensionResource(id = R.dimen.padding_small)
    val context = LocalContext.current

    ModalBottomSheet(
        onDismissRequest = onDismiss,
        sheetState = sheetState,
        containerColor = MaterialTheme.colorScheme.surfaceContainerHighest
    ) {
        LazyColumn(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = paddingExtraLarge)
        ) {
            item {
                Text(
                    text = title,
                    style = MaterialTheme.typography.headlineSmall.copy(fontWeight = FontWeight.Bold),
                    color = MaterialTheme.colorScheme.onBackground,
                    modifier = Modifier.padding(bottom = paddingLarge)
                )
            }

            items(entries) { entry ->
                val definition = entry.definitionOverride ?: StockAnalysisGlossaryProvider.definitionFor(context, entry.term)
                if (definition != null) {
                    Column(modifier = Modifier.padding(bottom = paddingLarge)) {
                        Text(
                            text = entry.label,
                            style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
                            color = MaterialTheme.colorScheme.onSurface
                        )
                        Spacer(modifier = Modifier.height(paddingSmall))
                        Text(
                            text = definition,
                            style = MaterialTheme.typography.bodyMedium,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                }
            }

            item { Spacer(modifier = Modifier.windowInsetsBottomHeight(WindowInsets.navigationBars)) }
        }
    }
}
