package com.marketlabs.pulse.ui.settings

// Generated by Claude Code.

import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.platform.LocalContext
import androidx.core.content.pm.PackageInfoCompat

/**
 * Reads the installed app's version name/code from `PackageInfo` (never hardcoded) and hands them
 * to the stateless [AboutScreen]. No ViewModel -- the screen is static content.
 */
@Composable
fun AboutRoute(
    onNavigateUp: () -> Unit,
    onNavigateToPrivacyPolicy: () -> Unit,
    onNavigateToTerms: () -> Unit
) {
    val context = LocalContext.current
    val (versionName, versionCode) = remember(context) {
        runCatching {
            val info = context.packageManager.getPackageInfo(context.packageName, 0)
            (info.versionName ?: "") to PackageInfoCompat.getLongVersionCode(info).toString()
        }.getOrDefault("" to "")
    }

    AboutScreen(
        versionName = versionName,
        versionCode = versionCode,
        onNavigateUp = onNavigateUp,
        onNavigateToPrivacyPolicy = onNavigateToPrivacyPolicy,
        onNavigateToTerms = onNavigateToTerms
    )
}
