package com.marketlabs.pulse.ui.settings

// Generated by Claude Code.

import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle

/**
 * Stateful — `hiltViewModel()`, `collectAsStateWithLifecycle()`, per this repo convention.
 *
 * spec-20260915-compliance-disclaimers.md: the "More" rows are real, navigable destinations now
 * (Notifications/Data & Sync/About are placeholder screens; Terms & Conditions/Privacy Policy/
 * Tutorials are net-new) — each gets its own nav callback, wired to a real route in
 * `PulseNavGraph`, rather than the earlier Toast-only stub behavior.
 */
@Composable
fun SettingsRoute(
    onNavigateUp: () -> Unit,
    onNavigateToThemePicker: () -> Unit,
    onNavigateToNotifications: () -> Unit,
    onNavigateToDataSync: () -> Unit,
    onNavigateToAbout: () -> Unit,
    onNavigateToTerms: () -> Unit,
    onNavigateToPrivacyPolicy: () -> Unit,
    onNavigateToTutorials: () -> Unit,
    viewModel: SettingsViewModel = hiltViewModel()
) {
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()

    SettingsScreen(
        uiState = uiState,
        onNavigateToThemePicker = onNavigateToThemePicker,
        onNavigateUp = onNavigateUp,
        onMoreItemClick = { item ->
            when (item) {
                SettingsMoreItem.NOTIFICATIONS -> onNavigateToNotifications()
                SettingsMoreItem.DATA_SYNC -> onNavigateToDataSync()
                SettingsMoreItem.ABOUT -> onNavigateToAbout()
                SettingsMoreItem.TERMS_CONDITIONS -> onNavigateToTerms()
                SettingsMoreItem.PRIVACY_POLICY -> onNavigateToPrivacyPolicy()
                SettingsMoreItem.TUTORIALS -> onNavigateToTutorials()
            }
        }
    )
}
