package com.marketlabs.pulse.ui.settings

// Generated by Claude Code.

import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle

/**
 * Stateful wrapper for [ThemePickerScreen] -- reuses [SettingsViewModel] rather than a dedicated
 * ViewModel, since the theme state it needs (`selectedTheme`/`selectTheme`) is exactly what that
 * ViewModel already exposes, backed by the same DataStore-persisted `ThemeRepository` either way. A
 * fresh instance is created scoped to this route's own back-stack entry (Hilt Compose Navigation
 * default), reading/writing the same repository, so selecting a preset here stays in sync with the
 * Settings screen underneath it the moment the user navigates back.
 */
@Composable
fun ThemePickerRoute(
    onNavigateUp: () -> Unit,
    viewModel: SettingsViewModel = hiltViewModel()
) {
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()

    ThemePickerScreen(
        presets = uiState.availablePresets,
        selectedTheme = uiState.selectedTheme,
        onPresetSelected = viewModel::selectTheme,
        onNavigateUp = onNavigateUp
    )
}
