package com.marketlabs.pulse.ui.screens.stocks.components

// Generated by Claude Code.

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.FlowRow
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.stocks.DomainConditionChip
import com.marketlabs.pulse.ui.components.widgets.SignalPill
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme

/**
 * A preview card only ever shows 4 of a symbol's full 11 `condition_chips`. Selection order per
 * the spec: (1) anything in `chips_added` -- these are new signals worth surfacing first, (2)
 * among the rest, BULLISH/BEARISH before NEUTRAL (a directional read is more informative at a
 * glance than a neutral one), (3) ties fall back to the backend's own array order. `sortedWith`
 * is a stable sort, so rule 3 falls out for free once rules 1 and 2 are expressed as the primary/
 * secondary sort keys -- no explicit index bookkeeping needed.
 */
fun selectPreviewChips(
    chips: List<DomainConditionChip>,
    added: Set<String>
): List<DomainConditionChip> {
    return chips
        .sortedWith(
            compareBy(
                { chip -> if (chip.label != null && added.contains(chip.label)) 0 else 1 },
                { chip -> if (chip.direction?.uppercase() == "NEUTRAL") 1 else 0 }
            )
        )
        .take(4)
}

/**
 * The condensed signal-chip row on a `StockPreviewCard`. Colors come straight off `direction`
 * ("BULLISH"/"BEARISH"/"NEUTRAL") against the theme's signal tokens -- the same hand-rolled
 * `when`-on-raw-string pattern `NewsScreen.kt`'s sentiment tags already use, not the
 * `SignalColor`/`SignalColorExtensions` pairing, since that enum's GREEN/YELLOW/RED vocabulary
 * belongs to a different domain model. An unrecognized or null direction falls back to the
 * neutral tokens -- there's no resolved `signal.unknown` chip treatment yet (Design System v1.0
 * still has it as a TODO), so this is the same neutral-fallback the rest of this feature uses.
 *
 * `FlowRow` rather than a scrolling row -- all 4 selected chips should be visible at once without
 * a horizontal swipe; when they don't fit on one line the row wraps to a second instead of
 * clipping or scrolling offscreen.
 */
@Composable
fun ConditionChipRow(
    chips: List<DomainConditionChip>,
    modifier: Modifier = Modifier
) {
    val pulseColors = LocalPulseColors.current

    FlowRow(
        modifier = modifier,
        horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_small)),
        verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_small))
    ) {
        chips.forEach { chip ->
            val (pillColor, textColor) = when (chip.direction?.uppercase()) {
                "BULLISH" -> pulseColors.signalBullishPill to pulseColors.signalBullishText
                "BEARISH" -> pulseColors.signalBearishPill to pulseColors.signalBearishText
                else -> pulseColors.signalNeutralPill to pulseColors.signalNeutralText
            }

            SignalPill(
                text = chip.label.orEmpty(),
                pillColor = pillColor,
                contentColor = textColor
            )
        }
    }
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

private val previewChips = listOf(
    DomainConditionChip(label = "Firm momentum", direction = "BULLISH", category = "MOMENTUM"),
    DomainConditionChip(label = "Above all moving averages", direction = "BULLISH", category = "TREND"),
    DomainConditionChip(label = "Cheaper than its own history", direction = "BULLISH", category = "VALUATION"),
    DomainConditionChip(label = "Stretched from its average", direction = "BEARISH", category = "VOLATILITY")
)

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewConditionChipRowLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        // Constrained width so the wrap-to-a-second-line behavior is actually visible here,
        // rather than an unbounded Row letting every chip sit on one line.
        ConditionChipRow(
            chips = previewChips,
            modifier = Modifier
                .fillMaxWidth()
                .padding(dimensionResource(id = R.dimen.padding_large))
        )
    }
}

@Preview(name = "Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewConditionChipRowDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        ConditionChipRow(
            chips = previewChips,
            modifier = Modifier
                .fillMaxWidth()
                .padding(dimensionResource(id = R.dimen.padding_large))
        )
    }
}
