package com.marketlabs.pulse.ui.components

// Generated by Claude Code.

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.foundation.layout.asPaddingValues
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.statusBars
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.material3.TopAppBarScrollBehavior
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.alpha
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme

/**
 * 💡 THOUGHT PROCESS:
 * Global collapsing top bar, one instance at the top-level `Scaffold` in `MainActivity` — wordmark
 * left in the accent color (the wordmark is one of the few places this app deliberately uses the
 * accent as decoration, not just as an interactive-affordance color), gear right in a muted
 * neutral. `enterAlwaysScrollBehavior` (YouTube-style: hides on scroll-down, returns on any
 * scroll-up) is created by the caller and passed in, not built here, since the same
 * `TopAppBarScrollBehavior` instance also needs to be attached to the scrollable content producing
 * the scroll deltas (see `MainActivity.kt`).
 *
 * `title` is supplied by the caller per-route (`MainActivity` resolves it from the current
 * destination) rather than a hardcoded wordmark -- the Overview tab still shows the app name, but
 * every other tab now shows its own name here instead of "MarketPulse" everywhere. The in-content
 * icon+title rows Indicators and Insights used to render at the top of their own scrollable content
 * are gone now that this bar carries the title -- they would otherwise say the same thing twice in
 * two different places on screen at once. Drill-down sub-views reached from within a tab (e.g.
 * Indicators' Horizon Briefings) keep their own in-content back-button-plus-title row, since this
 * bar has no way to show a back affordance or react to in-tab navigation state.
 *
 * `TopAppBar`'s own default `windowInsets` reserves and paints the status bar inset itself,
 * permanently -- it never fully vanishes there even once fully "collapsed" by scroll, since M3
 * treats that inset as a fixed minimum the bar always owns. That is the opposite of what was
 * wanted here: once the bar hides, the status bar should go fully transparent and show whatever
 * has scrolled up underneath it, not stay tinted with the bar's color forever. Fixed by taking
 * that region over entirely: `TopAppBar` below is told to ignore the status bar (`windowInsets =
 * WindowInsets(0)`, so its own collapse genuinely reaches zero), and a separate scrim `Box`, sized
 * to exactly the real status bar height and fading via `alpha` as `collapsedFraction` climbs from
 * 0 to 1, sits above it. The scrim's LAYOUT size never changes, only its drawn alpha does -- that
 * matters because `MainActivity` derives the live content top-padding as `innerPadding +
 * heightOffset`, and that arithmetic depends on the bar's measured height staying constant while
 * only its render-time offset moves; a scrim that changed size instead of alpha would throw it off.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AppTopBar(
    title: String,
    scrollBehavior: TopAppBarScrollBehavior,
    onSettingsClick: () -> Unit,
    modifier: Modifier = Modifier
) {
    // 💡 Was `surfaceContainerHighest` (a distinct elevated-white tone) -- switched to
    // `colorScheme.background`, the same color every screen's own content sits on, so the bar
    // reads as part of the page rather than a separate colored band sitting on top of it.
    val barColor = MaterialTheme.colorScheme.background
    val statusBarHeight = WindowInsets.statusBars.asPaddingValues().calculateTopPadding()

    Column(modifier = modifier) {
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .height(statusBarHeight)
                // 💡 `alpha` must come BEFORE `background` in the chain -- alpha wraps whatever is
                // drawn after it (more inner), so putting it after `background` left the fill
                // completely unaffected by the fade (this was the actual bug: collapsedFraction was
                // computing correctly the whole time, verified with a temporary debug readout, but
                // the modifier order meant the fade was applied to nothing).
                .alpha(1f - scrollBehavior.state.collapsedFraction)
                .background(barColor)
        )
        TopAppBar(
            title = {
                Text(
                    text = title,
                    style = MaterialTheme.typography.titleLarge,
                    color = LocalPulseColors.current.accentPrimary
                )
            },
            actions = {
                IconButton(onClick = onSettingsClick) {
                    Icon(
                        painter = painterResource(id = R.drawable.ic_settings),
                        contentDescription = stringResource(id = R.string.app_top_bar_settings_content_description),
                        tint = LocalPulseColors.current.onSurfaceMuted
                    )
                }
            },
            colors = TopAppBarDefaults.topAppBarColors(
                containerColor = barColor,
                scrolledContainerColor = barColor
            ),
            windowInsets = WindowInsets(0, 0, 0, 0),
            scrollBehavior = scrollBehavior
        )
    }
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

@OptIn(ExperimentalMaterial3Api::class)
@Preview(name = "Light — Lilac is dark, so preview Navy for light", showBackground = true)
@Composable
private fun PreviewAppTopBarLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        AppTopBar(
            title = stringResource(id = R.string.app_name),
            scrollBehavior = TopAppBarDefaults.enterAlwaysScrollBehavior(),
            onSettingsClick = {}
        )
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Preview(name = "Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewAppTopBarDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        AppTopBar(
            title = stringResource(id = R.string.indicators_screen_title),
            scrollBehavior = TopAppBarDefaults.enterAlwaysScrollBehavior(),
            onSettingsClick = {}
        )
    }
}
