package com.marketlabs.pulse.ui.components

// Generated by Claude Code.

import androidx.compose.animation.animateContentSize
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.FlowRow
import androidx.compose.foundation.layout.IntrinsicSize
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.intraday.IntradayPoint
import com.marketlabs.pulse.ui.components.widgets.CardEyebrowLabel
import com.marketlabs.pulse.ui.components.widgets.ChangeDirection
import com.marketlabs.pulse.ui.components.widgets.DirectionalChangePill
import com.marketlabs.pulse.ui.components.widgets.GlossaryTapChevron
import com.marketlabs.pulse.ui.components.widgets.SignalPill
import com.marketlabs.pulse.ui.components.widgets.SparklineChart
import com.marketlabs.pulse.ui.screens.stocks.detail.DataCardTitleWithInfo
import com.marketlabs.pulse.ui.screens.stocks.detail.OutlinedBadge
import com.marketlabs.pulse.ui.screens.stocks.detail.SubClusterLabel
import com.marketlabs.pulse.ui.screens.stocks.detail.SynthesisCardHeader
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme

/**
 * 💡 THOUGHT PROCESS:
 * A repo-wide-scan-derived reference of every distinct card visual pattern currently in use across
 * the app, in one file, with live previews -- a design-communication artifact, not production UI.
 * Nothing here is wired into any screen or nav route; every sample below is a stripped-down
 * recreation of a real card's *shape* (using mock data and the same shared primitives the real
 * card uses -- `PulseCard`, `SignalPill`, `SynthesisCardHeader`, etc.), not the real card itself,
 * so this file has no production dependency and can be edited/reordered/deleted freely as the
 * design conversation evolves. Each sample's doc comment cites the real file:line it's modeled on,
 * so a change agreed on here can be traced back to what actually needs editing.
 *
 * Organized in the same DATA / SYNTHESIS / DATA_SPARKLINE grouping `PulseCardStyle` itself uses,
 * plus two closing sections for patterns that sit *outside* `PulseCard` on purpose (see
 * `docs/theming-system/theming-spec.md`'s documented exceptions) and the "tinted inset row"
 * sub-pattern nested inside an already-`PulseCard`'d parent. [CardStyleGallery] stacks all of them
 * in one scrollable-height column for a side-by-side look; each pattern also gets its own smaller
 * preview for isolated iteration. Individual previews are Light-only to keep this file's preview
 * count manageable -- copy any preview's `MarketPulseTheme.LILAC`/`backgroundColor` pairing from
 * [CardStyleGallery]'s dark preview if a specific pattern needs its own dark check too.
 */

// ============================================================================
// DATA — 1. Simple stat tile
// Modeled on: UniversalMetricCard.kt:59-163, DashboardScreen.kt's AssetCard (non-sparkline path)
// ============================================================================

@Composable
private fun DataStatTileSample() {
    val pulseColors = LocalPulseColors.current
    PulseCard(style = PulseCardStyle.DATA, onClick = {}, modifier = Modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text(
                    "VIX",
                    style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
                    color = MaterialTheme.colorScheme.onSurface
                )
                Icon(
                    painter = painterResource(id = R.drawable.ic_chevron_forward),
                    contentDescription = null,
                    tint = pulseColors.onSurfaceMuted,
                    modifier = Modifier.size(dimensionResource(id = R.dimen.icon_size_small))
                )
            }
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_medium)))
            Text(
                "14.82",
                style = MaterialTheme.typography.headlineSmall.copy(fontWeight = FontWeight.Bold),
                color = MaterialTheme.colorScheme.onSurface
            )
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
            // 💡 VIX inverts signal semantics on purpose -- a rising VIX is bearish for equities
            // even though the number itself went up, same reasoning DirectionalChangePill's own
            // doc comment gives for decoupling `direction` from `pillColor`.
            DirectionalChangePill(
                changeText = "3.2%",
                direction = ChangeDirection.UP,
                pillColor = pulseColors.signalBearishPill,
                contentColor = pulseColors.signalBearishText
            )
        }
    }
}

@Preview(name = "1. DATA — Stat tile", showBackground = true)
@Composable
private fun PreviewDataStatTile() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) { DataStatTileSample() }
}

// ============================================================================
// DATA — 2. FlowRow stat clusters, divider between populated groups
// Modeled on: stocks/detail/sections/Fundamentals.kt:99-157
// ============================================================================

@Composable
private fun DataFlowRowClustersSample() {
    PulseCard(style = PulseCardStyle.DATA, modifier = Modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            DataCardTitleWithInfo(title = "FUNDAMENTALS", onInfoClick = {})
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_medium)))
            SubClusterLabel(title = "VALUATION")
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_medium)))
            FlowRow(
                horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_xlarge)),
                verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_medium))
            ) {
                StatColumnSample(value = "21.83", label = "TRAILING PE")
                StatColumnSample(value = "26.44", label = "FORWARD PE")
                StatColumnSample(value = "1.46", label = "PEG")
            }
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_medium)))
            HorizontalDivider(
                color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.1f),
                thickness = dimensionResource(id = R.dimen.border_thin)
            )
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_medium)))
            SubClusterLabel(title = "PROFITABILITY")
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_medium)))
            FlowRow(
                horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_xlarge)),
                verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_medium))
            ) {
                StatColumnSample(value = "30.56%", label = "ROE")
                StatColumnSample(value = "50.77%", label = "GROSS MARGIN")
            }
        }
    }
}

@Composable
private fun StatColumnSample(value: String, label: String) {
    Column(modifier = Modifier.width(dimensionResource(id = R.dimen.detail_stat_width))) {
        Text(
            value,
            style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
            color = MaterialTheme.colorScheme.onSurface
        )
        Text(
            label,
            style = MaterialTheme.typography.labelSmall,
            color = LocalPulseColors.current.onSurfaceMuted
        )
    }
}

@Preview(name = "2. DATA — FlowRow clusters + divider", showBackground = true)
@Composable
private fun PreviewDataFlowRowClusters() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) { DataFlowRowClustersSample() }
}

// ============================================================================
// DATA — 3. Fixed stat strip (no FlowRow wrapping)
// Modeled on: stocks/detail/sections/HeadlineMetricsStrip.kt:50-92
// ============================================================================

@Composable
private fun DataFixedStripSample() {
    PulseCard(style = PulseCardStyle.DATA, modifier = Modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            DataCardTitleWithInfo(title = "KEY METRICS", onInfoClick = {})
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_medium)))
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                StatColumnSample(value = "62", label = "RSI")
                StatColumnSample(value = "1.8x", label = "RVOL")
                StatColumnSample(value = "+9.1%", label = "DIST SMA20")
            }
        }
    }
}

@Preview(name = "3. DATA — Fixed stat strip", showBackground = true)
@Composable
private fun PreviewDataFixedStrip() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) { DataFixedStripSample() }
}

// ============================================================================
// DATA — 4. Colored left-rail / side-stripe accent, flush to card edges
// Modeled on: insights/views/MarketRisksView.kt:153-227 (TailRiskCard), summary/views/SummaryScreen.kt:1082-1128 (MacroCard)
// ============================================================================

@Composable
private fun DataLeftRailSample() {
    val pulseColors = LocalPulseColors.current
    PulseCard(style = PulseCardStyle.DATA, modifier = Modifier.fillMaxWidth()) {
        Row(modifier = Modifier.height(IntrinsicSize.Min)) {
            Box(
                modifier = Modifier
                    .fillMaxHeight()
                    .width(dimensionResource(id = R.dimen.border_medium))
                    .background(pulseColors.signalWarningText)
            )
            Column(
                modifier = Modifier
                    .weight(1f)
                    .padding(dimensionResource(id = R.dimen.padding_large))
            ) {
                Text(
                    "Tariff Escalation Risk",
                    style = MaterialTheme.typography.titleSmall.copy(fontWeight = FontWeight.Bold),
                    color = MaterialTheme.colorScheme.onSurface
                )
                Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
                Text(
                    "A renewed round of tariffs on Chinese imports would raise input costs across the consumer discretionary sector.",
                    style = MaterialTheme.typography.bodyMedium,
                    color = pulseColors.onSurfaceMuted
                )
            }
        }
    }
}

@Preview(name = "4. DATA — Colored left-rail", showBackground = true)
@Composable
private fun PreviewDataLeftRail() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) { DataLeftRailSample() }
}

// ============================================================================
// DATA — 5. Gauge value + delta pill + trailing "tap for glossary" chevron, whole card clickable
// Modeled on: insights/views/MarketPostureView.kt:191-266 (NaaimExposureCard/DarkPoolCard/NetLiquidityCard)
// ============================================================================

@Composable
private fun DataGaugeWithChevronSample() {
    val pulseColors = LocalPulseColors.current
    PulseCard(style = PulseCardStyle.DATA, onClick = {}, modifier = Modifier.fillMaxWidth()) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(dimensionResource(id = R.dimen.padding_large)),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Column {
                Text(
                    "NAAIM EXPOSURE",
                    style = MaterialTheme.typography.labelMedium.copy(fontWeight = FontWeight.Bold),
                    color = pulseColors.accentPrimary
                )
                Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
                Text(
                    "62.4",
                    style = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.Bold),
                    color = MaterialTheme.colorScheme.onSurface
                )
                Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
                DirectionalChangePill(
                    changeText = "4.1%",
                    direction = ChangeDirection.UP,
                    pillColor = pulseColors.signalBullishPill,
                    contentColor = pulseColors.signalBullishText
                )
            }
            GlossaryTapChevron(tint = pulseColors.onSurfaceMuted)
        }
    }
}

@Preview(name = "5. DATA — Gauge + delta + chevron", showBackground = true)
@Composable
private fun PreviewDataGaugeWithChevron() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) { DataGaugeWithChevronSample() }
}

// ============================================================================
// DATA — 6. One card, multiple independently-clickable rows, dividers between
// Modeled on: insights/views/MarketPositioningView.kt:313-346 (InstitutionalPositioningCard)
// ============================================================================

private data class RowSampleData(val name: String, val value: String, val delta: String)

@Composable
private fun DataMultiRowSample() {
    val pulseColors = LocalPulseColors.current
    val rows = listOf(
        RowSampleData("S&P 500", "62% OI", "+4pp"),
        RowSampleData("Nasdaq 100", "54% OI", "-2pp"),
        RowSampleData("Russell 2000", "48% OI", "+1pp")
    )
    PulseCard(style = PulseCardStyle.DATA, modifier = Modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            Text(
                "FUTURES POSITIONING",
                style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
                color = MaterialTheme.colorScheme.onSurface
            )
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_medium)))
            rows.forEachIndexed { index, row ->
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .clickable {}
                        .padding(vertical = dimensionResource(id = R.dimen.padding_small)),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text(
                        row.name,
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onSurface
                    )
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Text(
                            row.value,
                            style = MaterialTheme.typography.bodySmall,
                            color = pulseColors.onSurfaceMuted
                        )
                        Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_small)))
                        Text(
                            row.delta,
                            style = MaterialTheme.typography.labelSmall.copy(fontWeight = FontWeight.Bold),
                            color = pulseColors.signalBullishText
                        )
                        Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_tiny)))
                        GlossaryTapChevron(tint = pulseColors.onSurfaceMuted)
                    }
                }
                if (index != rows.lastIndex) {
                    HorizontalDivider(
                        color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.1f),
                        thickness = dimensionResource(id = R.dimen.border_thin)
                    )
                }
            }
        }
    }
}

@Preview(name = "6. DATA — Multi-row, per-row click + dividers", showBackground = true)
@Composable
private fun PreviewDataMultiRow() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) { DataMultiRowSample() }
}

// ============================================================================
// DATA — 7. Reasoning list, thin colored bar per row (confirms/conflicts)
// Modeled on: stocks/detail/sections/SetupReasoning.kt:143-171 (ReasoningRow/ReasoningBar)
// ============================================================================

@Composable
private fun DataReasoningListSample() {
    val pulseColors = LocalPulseColors.current
    val reasons = listOf(
        "Price above all major moving averages" to pulseColors.signalBullishText,
        "RSI approaching overbought territory" to pulseColors.signalWarningText
    )
    PulseCard(style = PulseCardStyle.DATA, modifier = Modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            Text(
                "WHY THIS SETUP",
                style = MaterialTheme.typography.labelMedium.copy(fontWeight = FontWeight.Bold),
                color = pulseColors.accentPrimary
            )
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_medium)))
            reasons.forEachIndexed { index, (text, color) ->
                Row(verticalAlignment = Alignment.Top) {
                    Box(
                        modifier = Modifier
                            .width(dimensionResource(id = R.dimen.border_medium))
                            .height(dimensionResource(id = R.dimen.padding_large))
                            .background(color)
                    )
                    Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_medium)))
                    Text(
                        text,
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onSurface
                    )
                }
                if (index != reasons.lastIndex) Spacer(
                    modifier = Modifier.height(
                        dimensionResource(
                            id = R.dimen.padding_small
                        )
                    )
                )
            }
        }
    }
}

@Preview(name = "7. DATA — Reasoning list, colored bar per row", showBackground = true)
@Composable
private fun PreviewDataReasoningList() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) { DataReasoningListSample() }
}

// ============================================================================
// DATA — 8. Timeline steps, dot nodes down the left edge
// Modeled on: summary/views/SummaryScreen.kt:1140-1168 (DominoCard/DominoTimelineStep)
// ============================================================================

private data class TimelineStepSample(val label: String, val text: String)

@Composable
private fun DataTimelineSample() {
    val pulseColors = LocalPulseColors.current
    val steps = listOf(
        TimelineStepSample("TRIGGER", "Fed signals a pause at the next meeting"),
        TimelineStepSample("IMPACT", "10-year yield falls 12 basis points"),
        TimelineStepSample("OUTLOOK", "Rate-sensitive sectors likely to outperform")
    )
    val paddingLarge = dimensionResource(id = R.dimen.padding_large)
    val paddingStandard = dimensionResource(id = R.dimen.padding_standard)
    PulseCard(style = PulseCardStyle.DATA, modifier = Modifier.fillMaxWidth()) {
        Column {
            Text(
                "THE DOMINO EFFECT",
                style = MaterialTheme.typography.titleSmall.copy(fontWeight = FontWeight.Bold),
                color = pulseColors.accentPrimary,
                modifier = Modifier.padding(paddingStandard)
            )
            HorizontalDivider(
                color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.1f),
                thickness = dimensionResource(id = R.dimen.border_thin)
            )

            Column(modifier = Modifier.padding(paddingLarge)) {
                steps.forEachIndexed { index, step ->
                    Row {
                        Column(
                            horizontalAlignment = Alignment.CenterHorizontally,
                            modifier = Modifier.width(dimensionResource(id = R.dimen.timeline_node_width))
                        ) {
                            Box(
                                modifier = Modifier
                                    .size(dimensionResource(id = R.dimen.timeline_dot_size))
                                    .background(pulseColors.accentPrimary, CircleShape)
                            )
                            if (index != steps.lastIndex) {
                                Box(
                                    modifier = Modifier
                                        .width(dimensionResource(id = R.dimen.border_thin))
                                        .height(dimensionResource(id = R.dimen.padding_xxlarge))
                                        .background(pulseColors.onSurfaceMuted.copy(alpha = 0.3f))
                                )
                            }
                        }
                        Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_medium)))
                        Column(modifier = Modifier.padding(bottom = dimensionResource(id = R.dimen.padding_medium))) {
                            Text(
                                step.label,
                                style = MaterialTheme.typography.labelSmall.copy(fontWeight = FontWeight.Bold),
                                color = pulseColors.onSurfaceMuted
                            )
                            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_tiny)))
                            Text(
                                step.text,
                                style = MaterialTheme.typography.bodyMedium,
                                color = MaterialTheme.colorScheme.onSurface
                            )
                        }
                    }
                }
            }
        }
    }
}

@Preview(name = "8. DATA — Timeline steps", showBackground = true)
@Composable
private fun PreviewDataTimeline() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) { DataTimelineSample() }
}

// ============================================================================
// DATA_SPARKLINE — 9. Sparkline asset tile
// Modeled on: dashboard/views/DashboardScreen.kt:468-682 (AssetCard, sparkline-eligible path), stocks/components/StockPreviewCard.kt:69-227
// ============================================================================

private val sampleSparklinePoints = listOf(580.2, 581.0, 579.8, 582.4, 583.1, 582.9, 584.1, 584.6)
    .mapIndexed { index, price ->
        IntradayPoint(
            minutesSinceMidnightEt = 570 + index * 30,
            price = price
        )
    }

@Composable
private fun DataSparklineTileSample() {
    val pulseColors = LocalPulseColors.current
    PulseCard(
        style = PulseCardStyle.DATA_SPARKLINE,
        onClick = {},
        modifier = Modifier.fillMaxWidth()
    ) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Column {
                    Text(
                        "SPY",
                        style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
                        color = MaterialTheme.colorScheme.onSurface
                    )
                    Text(
                        "SPDR S&P 500 ETF",
                        style = MaterialTheme.typography.bodySmall,
                        color = pulseColors.accentPrimary
                    )
                }
                SparklineChart(
                    points = sampleSparklinePoints,
                    previousClose = 580.0,
                    modifier = Modifier
                        .width(dimensionResource(id = R.dimen.stock_preview_sparkline_width))
                        .height(dimensionResource(id = R.dimen.stock_preview_sparkline_space))
                )
            }
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_medium)))
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text(
                    "$584.61",
                    style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
                    color = MaterialTheme.colorScheme.onSurface
                )
                DirectionalChangePill(
                    changeText = "0.71%",
                    direction = ChangeDirection.UP,
                    pillColor = pulseColors.signalBullishPill,
                    contentColor = pulseColors.signalBullishText
                )
            }
        }
    }
}

@Preview(name = "9. DATA_SPARKLINE — Sparkline tile", showBackground = true)
@Composable
private fun PreviewDataSparklineTile() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) { DataSparklineTileSample() }
}

// ============================================================================
// SYNTHESIS — 10. Icon + title header, body text
// Modeled on: stocks/detail/DetailSectionLabels.kt:113-133 (SynthesisCardHeader), used by TechnicalRead.kt/DeepStudy.kt/Scenarios.kt
// ============================================================================

@Composable
private fun SynthesisHeaderBodySample() {
    PulseCard(style = PulseCardStyle.SYNTHESIS, modifier = Modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            SynthesisCardHeader(title = "PLAIN READ")
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_large)))
            Text(
                "Amazon's stock sits at \$274.48, trading 16.04% above its 200-day average, while its cash flow yield of 0.78% is barely above the 0.47% risk-free rate.",
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurface
            )
        }
    }
}

@Preview(name = "10. SYNTHESIS — Icon+title header", showBackground = true)
@Composable
private fun PreviewSynthesisHeaderBody() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) { SynthesisHeaderBodySample() }
}

// ============================================================================
// SYNTHESIS — 11. Expandable hero: eyebrow + headline + tap-to-expand body
// Modeled on: components/SynthesisHeroCard.kt:75-128, indicators/views/IndicatorsScreen.kt:212-308 (AiExecutiveBriefingHero)
// ============================================================================

@Composable
private fun SynthesisExpandableHeroSample() {
    var expanded by remember { mutableStateOf(false) }
    val pulseColors = LocalPulseColors.current

    PulseCard(
        style = PulseCardStyle.SYNTHESIS,
        onClick = { expanded = !expanded },
        modifier = Modifier.fillMaxWidth()
    ) {
        Column(
            modifier = Modifier
                .padding(dimensionResource(id = R.dimen.padding_large))
                .animateContentSize()
        ) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                CardEyebrowLabel(text = "Market Posture", color = pulseColors.accentPrimary)
                Icon(
                    painter = painterResource(id = if (expanded) R.drawable.ic_arrow_up else R.drawable.ic_arrow_down),
                    contentDescription = null,
                    tint = pulseColors.onSurfaceMuted,
                    modifier = Modifier.size(dimensionResource(id = R.dimen.icon_size_small))
                )
            }
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
            Text(
                "Risk-On Regime Intact",
                style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
                color = MaterialTheme.colorScheme.onSurface
            )
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
            Text(
                "Breadth has broadened over the past two weeks, with small caps and cyclicals joining the mega-cap leadership that dominated the first half of the rally. Credit spreads remain tight and volatility has compressed to multi-month lows, both consistent with a durable risk-on backdrop rather than a narrow, late-cycle push.",
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurface,
                maxLines = if (expanded) Int.MAX_VALUE else 3,
                overflow = TextOverflow.Ellipsis
            )
        }
    }
}

@Preview(name = "11. SYNTHESIS — Expandable hero (tap to expand)", showBackground = true)
@Composable
private fun PreviewSynthesisExpandableHero() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) { SynthesisExpandableHeroSample() }
}

// ============================================================================
// SYNTHESIS — 12. Eyebrow + pill + headline, divider, meter
// Modeled on: summary/views/SummaryScreen.kt:341-436 (SignalSection)
// ============================================================================

@Composable
private fun SynthesisHeadlineMeterSample() {
    val pulseColors = LocalPulseColors.current
    PulseCard(style = PulseCardStyle.SYNTHESIS, modifier = Modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                CardEyebrowLabel(text = "Today's Signal", color = pulseColors.accentPrimary)
                Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_medium)))
                SignalPill(
                    text = "RISK ON",
                    pillColor = pulseColors.signalBullishPill,
                    contentColor = pulseColors.signalBullishText
                )
            }
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
            Text(
                "Momentum Broadens Across Sectors",
                style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
                color = MaterialTheme.colorScheme.onSurface
            )
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_large)))
            HorizontalDivider(
                color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.15f),
                thickness = dimensionResource(id = R.dimen.border_thin)
            )
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_large)))
            Text(
                "CONVICTION",
                style = MaterialTheme.typography.labelSmall.copy(fontWeight = FontWeight.Bold),
                color = pulseColors.onSurfaceMuted
            )
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .height(8.dp)
                    .background(
                        MaterialTheme.colorScheme.surfaceVariant,
                        RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_pill))
                    )
            ) {
                Box(
                    modifier = Modifier
                        .fillMaxWidth(0.72f)
                        .height(8.dp)
                        .background(
                            pulseColors.signalBullishText,
                            RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_pill))
                        )
                )
            }
        }
    }
}

@Preview(name = "12. SYNTHESIS — Headline + divider + meter", showBackground = true)
@Composable
private fun PreviewSynthesisHeadlineMeter() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) { SynthesisHeadlineMeterSample() }
}

// ============================================================================
// SYNTHESIS — 13. Kicker + dynamic heading + body + delta chips
// Modeled on: stocks/deepdive/DeepDiveSectionCard.kt, stocks/deepdive/FundamentalsDeltaChips.kt
// ============================================================================

@Composable
private fun SynthesisKickerDeltaChipsSample() {
    val pulseColors = LocalPulseColors.current
    PulseCard(style = PulseCardStyle.SYNTHESIS, modifier = Modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            Text(
                "WHAT'S CHANGED",
                style = MaterialTheme.typography.labelSmall.copy(fontWeight = FontWeight.Bold),
                color = pulseColors.accentPrimary
            )
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_tiny)))
            Text(
                "Analyst Targets Ticked Up on AI Capacity Buildout",
                style = MaterialTheme.typography.titleSmall.copy(fontWeight = FontWeight.Bold),
                color = MaterialTheme.colorScheme.onSurface
            )
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
            Text(
                "Since the last deep dive, Wall Street nudged its outlook higher after forward AWS capacity commitments came into view.",
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurface
            )
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_medium)))
            FlowRow(
                horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_small)),
                verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_small))
            ) {
                SignalPill(
                    text = "Analyst Target: \$327 → \$328",
                    pillColor = pulseColors.signalNeutralPill,
                    contentColor = pulseColors.signalNeutralText
                )
                SignalPill(
                    text = "Forward P/E: 25.64 → 24.75",
                    pillColor = pulseColors.signalNeutralPill,
                    contentColor = pulseColors.signalNeutralText
                )
            }
        }
    }
}

@Preview(name = "13. SYNTHESIS — Kicker + heading + delta chips", showBackground = true)
@Composable
private fun PreviewSynthesisKickerDeltaChips() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) { SynthesisKickerDeltaChipsSample() }
}

// ============================================================================
// SYNTHESIS — 14. Multi-section digest, small-caps sub-headings, dividers between every block
// Modeled on: stocks/detail/sections/DigestCard.kt
// ============================================================================

@Composable
private fun SynthesisMultiSectionDigestSample() {
    val pulseColors = LocalPulseColors.current
    PulseCard(style = PulseCardStyle.SYNTHESIS, modifier = Modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Icon(
                    painter = painterResource(id = R.drawable.ic_ai_sparkle_filled),
                    contentDescription = null,
                    tint = pulseColors.accentPrimary,
                    modifier = Modifier.size(dimensionResource(id = R.dimen.icon_size_small))
                )
                Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_small)))
                Text(
                    "DAILY DIGEST",
                    style = MaterialTheme.typography.labelMedium.copy(fontWeight = FontWeight.Bold),
                    color = pulseColors.accentPrimary
                )
            }
            val blocks = listOf(
                null to "Amazon falls 2% amid DOJ beef-pricing antitrust probe",
                "REGULATORY PRESSURE MOUNTS" to "The Department of Justice expanded its antitrust inquiry into rising beef prices, demanding information from Amazon and other major retailers."
            )
            blocks.forEachIndexed { index, (heading, body) ->
                Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_large)))
                Column {
                    heading?.let {
                        Text(
                            it,
                            style = MaterialTheme.typography.labelMedium.copy(fontWeight = FontWeight.Bold),
                            color = pulseColors.onSurfaceMuted
                        )
                        Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
                    }
                    Text(
                        body,
                        style = if (heading == null) MaterialTheme.typography.titleMedium.copy(
                            fontWeight = FontWeight.Bold
                        ) else MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onSurface
                    )
                }
                if (index != blocks.lastIndex) {
                    Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_large)))
                    HorizontalDivider(
                        color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.1f),
                        thickness = dimensionResource(id = R.dimen.border_thin)
                    )
                }
            }
        }
    }
}

@Preview(name = "14. SYNTHESIS — Multi-section digest, dividers", showBackground = true)
@Composable
private fun PreviewSynthesisMultiSectionDigest() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) { SynthesisMultiSectionDigestSample() }
}

// ============================================================================
// 15. Emphasis border layered ON TOP of PulseCard's own border/shadow -- "this one is selected"
// Modeled on: indicators/detail/MetricDetailScreen.kt:192-240 (BandRow), insights/glossary/GlossaryDetailScreen.kt:157-198, news/views/NewsScreen.kt:206-240 (isHighlighted)
// ============================================================================

@Composable
private fun EmphasisBorderOverlaySample() {
    val pulseColors = LocalPulseColors.current
    PulseCard(
        style = PulseCardStyle.DATA,
        modifier = Modifier
            .fillMaxWidth()
            .border(
                dimensionResource(id = R.dimen.border_medium),
                pulseColors.accentPrimary,
                RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_card_large))
            )
    ) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            Text(
                "62 – 75",
                style = MaterialTheme.typography.titleSmall.copy(fontWeight = FontWeight.Bold),
                color = MaterialTheme.colorScheme.onSurface
            )
            Text(
                "Currently in this band — Neutral",
                style = MaterialTheme.typography.bodySmall,
                color = pulseColors.onSurfaceMuted
            )
        }
    }
}

@Preview(name = "15. Emphasis border overlay (current selection)", showBackground = true)
@Composable
private fun PreviewEmphasisBorderOverlay() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) { EmphasisBorderOverlaySample() }
}

// ============================================================================
// 16. Deliberately OUTSIDE PulseCard -- signal-owned background (documented exception)
// Modeled on: dashboard/views/DashboardScreen.kt:377 (SectorBlock), settings/components/PresetSwatchCard.kt:63
// ============================================================================

@Composable
private fun SignalOwnedBackgroundExceptionSample() {
    val pulseColors = LocalPulseColors.current
    // 💡 NOT PulseCard, on purpose -- per docs/theming-system/theming-spec.md's documented
    // exceptions, a full-saturation signal color owns the entire background here, which is a
    // different contract than "which of PulseCard's two/three standard looks does this use."
    Card(
        colors = CardDefaults.cardColors(containerColor = pulseColors.signalBullishPill),
        shape = RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_small)),
        modifier = Modifier.fillMaxWidth()
    ) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            Text(
                "TECHNOLOGY",
                style = MaterialTheme.typography.labelMedium.copy(fontWeight = FontWeight.Bold),
                color = pulseColors.signalBullishText
            )
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
            Text(
                "+2.4%",
                style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
                color = pulseColors.signalBullishText
            )
        }
    }
}

@Preview(name = "16. NOT PulseCard — signal-owned background", showBackground = true)
@Composable
private fun PreviewSignalOwnedBackgroundException() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) { SignalOwnedBackgroundExceptionSample() }
}

// ============================================================================
// 17. "Tinted inset row" — a plain Surface nested INSIDE an already-PulseCard'd parent
// Modeled on: stocks/detail/sections/ForwardCalls.kt:146-234, stocks/detail/sections/Scenarios.kt:76-125, indicators/views/IndicatorsScreen.kt:315-343 (ShiftRow)
// ============================================================================

@Composable
private fun TintedInsetRowSample() {
    val pulseColors = LocalPulseColors.current
    PulseCard(style = PulseCardStyle.SYNTHESIS, modifier = Modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            SynthesisCardHeader(title = "SCENARIOS")
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_large)))
            OutlinedBadge(text = "BULL CASE")
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
            // 💡 The nested `Surface` -- not another `PulseCard` -- is the point of this sample:
            // a tinted sub-block inside an already-PulseCard'd parent, with no shadow/border of
            // its own, distinct from a second full card-in-card.
            Surface(
                color = pulseColors.surfaceTinted,
                shape = RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_small))
            ) {
                Text(
                    "If AWS reaccelerates and margins hold above 35%, the stock could re-rate toward its 5-year average multiple.",
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurface,
                    modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_medium))
                )
            }
        }
    }
}

@Preview(name = "17. Tinted inset row nested in a card", showBackground = true)
@Composable
private fun PreviewTintedInsetRow() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) { TintedInsetRowSample() }
}

// ============================================================================
// 🎨 THE GALLERY — everything above, stacked with labels, for a side-by-side look
// ============================================================================

@Composable
private fun CardStyleGallery() {
    Column(
        modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large)),
        verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_xxlarge))
    ) {
        GallerySection("1. DATA — Stat tile") { DataStatTileSample() }
        GallerySection("2. DATA — FlowRow clusters + divider") { DataFlowRowClustersSample() }
        GallerySection("3. DATA — Fixed stat strip") { DataFixedStripSample() }
        GallerySection("4. DATA — Colored left-rail") { DataLeftRailSample() }
        GallerySection("5. DATA — Gauge + delta + chevron") { DataGaugeWithChevronSample() }
        GallerySection("6. DATA — Multi-row, per-row click + dividers") { DataMultiRowSample() }
        GallerySection("7. DATA — Reasoning list, colored bar per row") { DataReasoningListSample() }
        GallerySection("8. DATA — Timeline steps") { DataTimelineSample() }
        GallerySection("9. DATA_SPARKLINE — Sparkline tile") { DataSparklineTileSample() }
        GallerySection("10. SYNTHESIS — Icon+title header") { SynthesisHeaderBodySample() }
        GallerySection("11. SYNTHESIS — Expandable hero (tap to expand)") { SynthesisExpandableHeroSample() }
        GallerySection("12. SYNTHESIS — Headline + divider + meter") { SynthesisHeadlineMeterSample() }
        GallerySection("13. SYNTHESIS — Kicker + heading + delta chips") { SynthesisKickerDeltaChipsSample() }
        GallerySection("14. SYNTHESIS — Multi-section digest, dividers") { SynthesisMultiSectionDigestSample() }
        GallerySection("15. Emphasis border overlay (current selection)") { EmphasisBorderOverlaySample() }
        GallerySection("16. NOT PulseCard — signal-owned background") { SignalOwnedBackgroundExceptionSample() }
        GallerySection("17. Tinted inset row nested in a card") { TintedInsetRowSample() }
    }
}

@Composable
private fun GallerySection(label: String, content: @Composable () -> Unit) {
    Column {
        Text(
            label,
            style = MaterialTheme.typography.labelSmall.copy(fontWeight = FontWeight.Bold),
            color = LocalPulseColors.current.onSurfaceMuted
        )
        Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
        content()
    }
}

@Preview(name = "Gallery — Light", showBackground = true, heightDp = 6000)
@Composable
private fun PreviewCardStyleGalleryLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) { CardStyleGallery() }
}

@Preview(
    name = "Gallery — Dark",
    showBackground = true,
    backgroundColor = 0xFF0D0E12,
    heightDp = 6000
)
@Composable
private fun PreviewCardStyleGalleryDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) { CardStyleGallery() }
}
