package com.marketlabs.pulse.ui.components

// Generated by Claude Code.

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.dashboard.AssetOverview
import com.marketlabs.pulse.ui.components.widgets.PercentileBar
import com.marketlabs.pulse.ui.components.widgets.PutCallHorizontalBar
import com.marketlabs.pulse.ui.components.widgets.RingGauge
import com.marketlabs.pulse.ui.components.widgets.ScoreGauge
import com.marketlabs.pulse.ui.components.widgets.SpeedometerGauge
import com.marketlabs.pulse.ui.components.widgets.TriSegmentBar
import com.marketlabs.pulse.ui.components.widgets.VixFullWidthCard
import com.marketlabs.pulse.ui.screens.stocks.detail.PriceRangeBar
import com.marketlabs.pulse.ui.screens.summary.views.PositioningGauge
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme
import com.marketlabs.pulse.utils.enums.AssetType
import com.marketlabs.pulse.utils.enums.SignalColor

/**
 * 💡 THOUGHT PROCESS:
 * A repo-wide-scan-derived reference of every distinct gauge/meter visual currently in use across
 * the app, in one file, with live previews -- the gauge counterpart to [CardStyleShowcase]. Nothing
 * here is wired into any screen or nav route; this file has no production dependency and can be
 * edited/reordered/deleted freely as the design conversation evolves.
 *
 * Unlike [CardStyleShowcase], which recreates each card *pattern* with mock data (because a real
 * card is often tangled into a ViewModel/screen-specific layout), every sample below calls the REAL
 * production composable directly with representative mock data -- gauges in this app are
 * self-contained, presentational widgets with simple typed params (`Double`/`Int`/`Color`/enum), so
 * there's nothing to strip down or recreate. Each sample's doc comment cites the real component file
 * and its actual call site (screen + line), so a color/shape change agreed on here is made in that
 * one real file, not copied into this one.
 *
 * Grouped by drawing technique: arc/ring gauges (a `Canvas` progress arc), bar/track gauges (a
 * `Canvas` or weighted-`Row` linear track), then two composite/schematic gauges that layer a
 * decorative shape under a data-driven marker. [GaugeStyleGallery] stacks all of them in one
 * scrollable-height column for a side-by-side look; each also gets its own file's own `@Preview`
 * already (cited below) for isolated iteration -- this file doesn't duplicate those, just collects
 * them.
 *
 * `DonutScoreCard` (ui/components/widgets/DonutScoreCard.kt) is NOT included here -- confirmed
 * (2026-09) to have zero call sites anywhere in the app outside its own previews, i.e. dead code,
 * not a gauge pattern in current use. Deleted alongside adding this file rather than cataloged.
 */

// ============================================================================
// ARC/RING — 1. 5-band arc dial, floating triangle pointer, contrarian coloring
// Real component: ui/components/widgets/SpeedometerGauge.kt
// Call site: dashboard/views/DashboardScreen.kt:206 (Fear & Greed)
// ============================================================================

@Preview(name = "1. Arc dial — SpeedometerGauge (Fear & Greed)", showBackground = true)
@Composable
private fun PreviewGaugeSpeedometer() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        SpeedometerGauge(score = 72.0, previousScore = 65.0, status = "GREED")
    }
}

// ============================================================================
// ARC/RING — 2. Full-size circular progress ring, centered score + delta + status
// Real component: ui/components/widgets/ScoreGauge.kt
// Call site: ui/components/UnifiedScoreHeaderCard.kt:76 (Risk Radar hero gauge)
// ============================================================================

@Preview(name = "2. Circular ring (large) — ScoreGauge (Risk Radar)", showBackground = true)
@Composable
private fun PreviewGaugeScore() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        ScoreGauge(
            score = 68,
            previousScore = 61,
            isHigherBetter = true,
            statusText = "Bull Trend",
            ringColor = LocalPulseColors.current.signalBullishText
        )
    }
}

// ============================================================================
// ARC/RING — 3. Compact circular progress ring, centered raw value, no baked-in delta/status
// Real component: ui/components/widgets/RingGauge.kt
// Call sites: insights/views/MarketPostureView.kt:221 (NAAIM Exposure), :304 (Dark Pool Index)
// ============================================================================

@Preview(name = "3. Circular ring (small) — RingGauge (NAAIM / DIX)", showBackground = true)
@Composable
private fun PreviewGaugeRing() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        RingGauge(value = 84.2, maxValue = 100.0, ringColor = MaterialTheme.colorScheme.primary)
    }
}

// ============================================================================
// BAR/TRACK — 4. Two-color split gradient bar, center anchor tick
// Real component: ui/components/widgets/PutCallHorizontalBar.kt
// Call site: dashboard/views/DashboardScreen.kt:223 (Put/Call Ratio)
// ============================================================================

@Preview(name = "4. Split bar — PutCallHorizontalBar", showBackground = true)
@Composable
private fun PreviewGaugePutCall() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        PutCallHorizontalBar(ratio = 0.85, change = -4.2, status = "GREED")
    }
}

// ============================================================================
// BAR/TRACK — 5. Three-stop gradient bar + moving needle, inside a full price card
// Real component: ui/components/widgets/VixFullWidthCard.kt (the gauge bar itself is inline Canvas
// code in that file, not its own reusable function -- shown as the whole card rather than
// extracted, since that's the only way to call the real thing)
// Call site: dashboard/views/DashboardScreen.kt:186 (VIX)
// ============================================================================

@Preview(name = "5. Gradient bar + needle — VixFullWidthCard", showBackground = true)
@Composable
private fun PreviewGaugeVix() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        VixFullWidthCard(
            asset = AssetOverview(
                symbol = "VIX",
                name = "CBOE Volatility Index",
                type = AssetType.INDEX,
                price = 18.42,
                changePercent = -3.15,
                rsiStatus = "GREED"
            ),
            onClick = {}
        )
    }
}

// ============================================================================
// BAR/TRACK — 6. 0-100 track, single dot marker
// Real component: ui/components/widgets/PercentileBar.kt
// Call site: insights/views/MarketPositioningView.kt:453 (CFTC COT percentile)
// ============================================================================

@Preview(name = "6. Track + dot marker — PercentileBar", showBackground = true)
@Composable
private fun PreviewGaugePercentileBar() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        PercentileBar(percentile = 42, markerColor = MaterialTheme.colorScheme.primary)
    }
}

// ============================================================================
// BAR/TRACK — 7. Three-way weighted proportion bar (bull/neutral/bear)
// Real component: ui/components/widgets/TriSegmentBar.kt
// Call site: insights/views/MarketPositioningView.kt:282 (AAII retail sentiment split)
// ============================================================================

@Preview(name = "7. 3-way proportion bar — TriSegmentBar", showBackground = true)
@Composable
private fun PreviewGaugeTriSegment() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        TriSegmentBar(bullFraction = 0.355f, neutralFraction = 0.246f, bearFraction = 0.399f)
    }
}

// ============================================================================
// COMPOSITE/SCHEMATIC — 8. Labeled range track, value-area band, support/resistance ticks,
// labeled current-price marker
// Real component: screens/stocks/detail/PriceRangeBar.kt
// Call site: screens/stocks/detail/sections/KeyLevels.kt:97 (52-week range)
// ============================================================================

@Preview(name = "8. Range track + labeled marker — PriceRangeBar", showBackground = true)
@Composable
private fun PreviewGaugePriceRange() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        PriceRangeBar(
            axisLow = 199.0,
            axisHigh = 275.0,
            valueAreaLow = 199.42,
            valueAreaHigh = 254.14,
            fairValueAnchor = 208.54,
            support = 255.19,
            resistance = 274.75,
            currentPrice = 274.48
        )
    }
}

// ============================================================================
// COMPOSITE/SCHEMATIC — 9. Decorative hump silhouette + track + data-driven marker
// Real component: screens/summary/views/PositioningGauge.kt
// Call site: screens/summary/views/SummaryScreen.kt:898 (SPY 52-week range position)
// ============================================================================

@Preview(name = "9. Hump silhouette + marker — PositioningGauge", showBackground = true)
@Composable
private fun PreviewGaugePositioning() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        PositioningGauge(
            rangePosition = 93.17,
            windowLabel = "251-day",
            signalText = "Extended Near Highs",
            signalColor = SignalColor.RED
        )
    }
}

// ============================================================================
// 🎨 THE GALLERY — everything above, stacked with labels, for a side-by-side look
// ============================================================================

@Composable
private fun GaugeStyleGallery() {
    Column(
        modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large)),
        verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_xxlarge))
    ) {
        GaugeGallerySection("1. Arc dial (Fear & Greed)") {
            SpeedometerGauge(score = 72.0, previousScore = 65.0, status = "GREED")
        }
        GaugeGallerySection("2. Circular ring, large (Risk Radar)") {
            ScoreGauge(
                score = 68,
                previousScore = 61,
                isHigherBetter = true,
                statusText = "Bull Trend",
                ringColor = LocalPulseColors.current.signalBullishText
            )
        }
        GaugeGallerySection("3. Circular ring, small (NAAIM / DIX)") {
            RingGauge(value = 84.2, maxValue = 100.0, ringColor = MaterialTheme.colorScheme.primary)
        }
        GaugeGallerySection("4. Split bar (Put/Call)") {
            PutCallHorizontalBar(ratio = 0.85, change = -4.2, status = "GREED")
        }
        GaugeGallerySection("5. Gradient bar + needle (VIX)") {
            VixFullWidthCard(
                asset = AssetOverview(
                    symbol = "VIX",
                    name = "CBOE Volatility Index",
                    type = AssetType.INDEX,
                    price = 18.42,
                    changePercent = -3.15,
                    rsiStatus = "GREED"
                ),
                onClick = {}
            )
        }
        GaugeGallerySection("6. Track + dot marker (COT percentile)") {
            PercentileBar(percentile = 42, markerColor = MaterialTheme.colorScheme.primary)
        }
        GaugeGallerySection("7. 3-way proportion bar (AAII)") {
            TriSegmentBar(bullFraction = 0.355f, neutralFraction = 0.246f, bearFraction = 0.399f)
        }
        GaugeGallerySection("8. Range track + labeled marker (52-week range)") {
            PriceRangeBar(
                axisLow = 199.0,
                axisHigh = 275.0,
                valueAreaLow = 199.42,
                valueAreaHigh = 254.14,
                fairValueAnchor = 208.54,
                support = 255.19,
                resistance = 274.75,
                currentPrice = 274.48
            )
        }
        GaugeGallerySection("9. Hump silhouette + marker (SPY range position)") {
            PositioningGauge(
                rangePosition = 93.17,
                windowLabel = "251-day",
                signalText = "Extended Near Highs",
                signalColor = SignalColor.RED
            )
        }
    }
}

@Composable
private fun GaugeGallerySection(label: String, content: @Composable () -> Unit) {
    Column {
        Text(
            label,
            style = MaterialTheme.typography.labelSmall.copy(fontWeight = FontWeight.Bold),
            color = LocalPulseColors.current.onSurfaceMuted
        )
        Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
        content()
    }
}

@Preview(name = "Gallery — Light", showBackground = true, heightDp = 3400)
@Composable
private fun PreviewGaugeStyleGalleryLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) { GaugeStyleGallery() }
}

@Preview(
    name = "Gallery — Dark",
    showBackground = true,
    backgroundColor = 0xFF0D0E12,
    heightDp = 3400
)
@Composable
private fun PreviewGaugeStyleGalleryDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) { GaugeStyleGallery() }
}
