package com.marketlabs.pulse.ui.components

// Generated by Claude Code.

import androidx.compose.animation.core.FastOutSlowInEasing
import androidx.compose.animation.core.Spring
import androidx.compose.animation.core.animateFloat
import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.animation.core.infiniteRepeatable
import androidx.compose.animation.core.keyframes
import androidx.compose.animation.core.rememberInfiniteTransition
import androidx.compose.animation.core.spring
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.LocalIndication
import androidx.compose.foundation.clickable
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.interaction.collectIsPressedAsState
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.ColumnScope
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.drawBehind
import androidx.compose.ui.draw.shadow
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Shape
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.graphics.luminance
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme
import kotlin.math.sqrt

/**
 * The outer-shell looks every content card in this app uses. Was deliberately just `DATA`/`SYNTHESIS`
 * for a long time -- anything that needs something else entirely (the sector heatmap tiles, the
 * pillar score headers, the theme picker's preset swatches) owns a background a signal color or an
 * external caller controls, which is a different thing from "which of the app's standard card looks
 * does this use," and stays a plain `Card` rather than being forced in here. `DATA_SPARKLINE` is the
 * one deliberate addition to that pair -- see the 2026-08-29 note below for why it exists.
 *
 * There used to be a third, `NEUTRAL` (white/elevated surface, for VIX/Fear & Greed/Put-Call), kept
 * visually distinct from `DATA`'s accent-tinted price cards on the theory that a computed reading
 * shouldn't look like raw data. Retired once that distinction stopped being wanted -- those cards
 * moved onto plain `DATA`, the same tinted background and border every other price card already uses.
 *
 * 💡 2026-08-29 card redesign: `DATA` moved off the accent-tinted background onto a flat
 * white-in-light / greyish-dark-in-dark card (`MaterialTheme.colorScheme.surfaceVariant`, which is
 * already sourced from `PulseTokens.Surface.*.surfaceElevated` -- pure white in every light preset,
 * a lighter grey step above the page background in every dark preset), no hairline border in light
 * mode (the shadow does that job instead), and a soft drop shadow. `SYNTHESIS`'s own background/
 * border are unchanged (still `accentSurfaceStrong` + hairline border) -- AI-authored content was
 * asked to keep its own look. A third style, `DATA_SPARKLINE`, was added rather than folding this
 * into `DATA` because one DATA consumer -- Overview's per-asset price cards that embed a live
 * intraday sparkline -- was asked to keep today's pre-redesign background/border
 * (`surfaceTinted`/hairline) untouched; every other DATA card across the app (Overview's own
 * VIX/Fear & Greed/Put-Call/futures cards included, since they don't carry a sparkline) picks up the
 * new look automatically through this one shared component. The drop shadow itself was later
 * extended to all three styles (see the shadow comment below) -- only background/border still vary
 * per style.
 */
enum class PulseCardStyle {
    /** Raw or computed readings -- prices, ratios, VIX, Fear & Greed, Put/Call. Flat white/greyish-dark background, no border in either mode. */
    DATA,

    /** Curated, AI-generated, or externally-sourced content -- briefings, verdicts, news, disclaimers. `accentSurfaceStrong`, hairline border. */
    SYNTHESIS,

    /** Overview's sparkline-bearing asset cards only -- frozen to `DATA`'s pre-redesign background/border (`surfaceTinted`, hairline border) so the sparkline keeps reading against the same accent-tinted background it always has. */
    DATA_SPARKLINE
}

enum class GlowOrigin {
    TOP_LEFT,
    TOP_RIGHT
}

/**
 * 💡 THOUGHT PROCESS:
 * Before this, every card in the app hand-rolled its own `Card(colors = ..., border = ..., shape =
 * ...)` -- and a large fraction of them (every card in Insights and Summary, plus Indicators' AI
 * briefing) were still doing so with `MaterialTheme.colorScheme.secondaryContainer.copy(alpha =
 * 0.4f)`, a leftover from before this app had its own token system at all. Changing "what a card's
 * background looks like" meant hunting down every one of those call sites individually, and it was
 * easy for a new card to copy the stale pattern instead of the current one (which is exactly what
 * kept happening).
 *
 * This collapses that down to two outer looks (`PulseCardStyle`), each resolving to one
 * background + border + shape combination, defined in exactly one place. Only the OUTER shell is
 * standardized here -- every card's inner content (what it actually says, its own icons, dividers,
 * colored stripes, pills) stays exactly as varied as it already was and is untouched by this;
 * `content` has the same `ColumnScope` signature `Card` itself exposes, so a card whose top-level
 * child is a `Row` (a colored side-stripe layout, for instance) works exactly as before.
 *
 * `shape` defaults per style rather than being a single global default: `DATA` cards (price tiles,
 * computed-reading cards) use the larger `corner_radius_card_large`, while `SYNTHESIS` cards
 * (briefings, articles, verdicts) use the smaller `corner_radius_card` -- matching what every card in
 * each category already used before this consolidation, not a new choice.
 */
@Composable
fun PulseCard(
    style: PulseCardStyle,
    modifier: Modifier = Modifier,
    shape: Shape = RoundedCornerShape(
        dimensionResource(
            id = if (style == PulseCardStyle.SYNTHESIS) R.dimen.corner_radius_card else R.dimen.corner_radius_card_large
        )
    ),
    onClick: (() -> Unit)? = null,
    // 💡 A faint periodic pulse of this color behind the card's content -- built for the two
    // sparkline-bearing cards (Dashboard's asset tile, Stock Analysis' `StockPreviewCard`), which
    // pass their sparkline's own bullish/bearish color here so the card itself echoes the chart's
    // color at a glance. `null` (the default) renders nothing extra -- every other `PulseCard`
    // call site is unaffected.
    glowColor: Color? = null,
    glowOrigin: GlowOrigin = GlowOrigin.TOP_LEFT,
    // 💡 When true, the glow's radius grows from 0 to the full card diagonal over the fade-in/hold
    // window (then fades out as before), so it reads as color filling the card outward from
    // `glowOrigin` instead of a fixed-size gradient just brightening in place -- which on a wide,
    // short banner looks like a glow sitting on one side.
    glowFill: Boolean = false,
    // How opaque the glow gets at its brightest -- a card sitting on a light background can need a
    // stronger one for the same visibility.
    glowPeakAlpha: Float = CardGlowPeakAlpha,
    content: @Composable ColumnScope.() -> Unit
) {
    val pulseColors = LocalPulseColors.current

    val containerColor = when (style) {
        // 💡 `colorScheme.surfaceVariant`, not a `LocalPulseColors` field -- this is one of the
        // plain surface-ramp roles (`PulseTokens.Surface.*.surfaceElevated`) that MarketPulseTheme.kt
        // deliberately resolves onto `MaterialTheme.colorScheme` instead of duplicating onto
        // `PulseColors`, exactly like `background`/`surface`/`onSurface` already are.
        PulseCardStyle.DATA -> MaterialTheme.colorScheme.surfaceVariant
        PulseCardStyle.SYNTHESIS -> pulseColors.accentSurfaceStrong
        PulseCardStyle.DATA_SPARKLINE -> pulseColors.surfaceTinted
    }
    // 💡 `DATA` stays borderless in both modes -- a dark-mode-only `accentPrimary` stroke was tried
    // here and dropped again; the shadow below is what separates the card from the page in both
    // modes now, not a border.
    val border = when (style) {
        PulseCardStyle.DATA -> null
        PulseCardStyle.SYNTHESIS, PulseCardStyle.DATA_SPARKLINE ->
            BorderStroke(dimensionResource(id = R.dimen.border_thin), pulseColors.accentSurfaceBorder)
    }
    val colors = CardDefaults.cardColors(containerColor = containerColor)

    // 💡 Subtle press feedback -- only for cards with an `onClick`, so a non-clickable `PulseCard`
    // never scales. `interactionSource` is built either way (cheap) but only ever receives press
    // events through the `clickable` branch below, so `isPressed`/`scale` stay inert otherwise.
    val interactionSource = remember { MutableInteractionSource() }
    val isPressed by interactionSource.collectIsPressedAsState()
    val pressScale by animateFloatAsState(
        targetValue = if (isPressed) PressedScale else 1f,
        animationSpec = spring(stiffness = Spring.StiffnessMedium),
        label = "card_press_scale"
    )
    val indication = LocalIndication.current
    val clickableModifier = modifier
        .graphicsLayer {
            scaleX = pressScale
            scaleY = pressScale
        }
        .let {
            if (onClick != null) {
                it.clickable(interactionSource = interactionSource, indication = indication, onClick = onClick)
            } else {
                it
            }
        }
    // 💡 Shadow is applied by hand via `Modifier.shadow`, not `CardDefaults.cardElevation` (Card's
    // own `elevation` param is left at its 0dp default below) -- `CardElevation` only exposes one
    // number, which Compose renders as the platform's default key-light shadow: heavy `spotColor`
    // cast that pools at the bottom, near-invisible `ambientColor` halo everywhere else, which read
    // as bottom-heavy rather than a card sitting evenly above the page. `Modifier.shadow` exposes
    // `ambientColor`/`spotColor` separately, so weighting ambient well above spot here trades that
    // directional cast for a soft, roughly even halo on every side instead. Applies to all three
    // styles now (previously `DATA` only) -- `SYNTHESIS`/`DATA_SPARKLINE` still draw their own
    // container color/border on top of it, unchanged.
    //
    // 💡 Light mode's shadow was asked to read stronger than dark mode's -- light-mode cards sit on
    // a near-white/tinted-white page where a soft shadow is the main thing separating a card from
    // it, while dark mode already gets most of that separation from the color step between the
    // near-black background and the lighter-grey card itself. `MaterialTheme.colorScheme.background`
    // has no direct per-mode flag to read here (see the removed border experiment's note, now
    // gone) -- luminance is still the cheapest way to tell the two apart without new plumbing.
    val isDarkMode = MaterialTheme.colorScheme.background.luminance() < 0.5f
    val shadowElevation = if (isDarkMode) {
        dimensionResource(id = R.dimen.elevation_small)
    } else {
        dimensionResource(id = R.dimen.elevation_medium)
    }
    val shadowAmbient = if (isDarkMode) CardShadowAmbientDark else CardShadowAmbientLight
    val shadowSpot = if (isDarkMode) CardShadowSpotDark else CardShadowSpotLight
    val shadowModifier = clickableModifier.shadow(
        elevation = shadowElevation,
        shape = shape,
        ambientColor = shadowAmbient,
        spotColor = shadowSpot
    )

    Card(
        colors = colors,
        border = border,
        shape = shape,
        modifier = shadowModifier
    ) {
        if (glowColor != null) {
            // 💡 A `Box` wrapper (not on `PulseCard`'s own outer modifier -- same shadow/clip
            // gotcha as `animateContentSize()` elsewhere) so the glow layer sits behind the real
            // content and is clipped to the card's own shape automatically (`Card`/`Surface`
            // already clip their content to `shape`, so nothing extra is needed here for corners).
            Box(Modifier.fillMaxWidth()) {
                val glowTransition = rememberInfiniteTransition(label = "card_glow")
                val glowAlpha by glowTransition.animateFloat(
                    initialValue = 0f,
                    targetValue = 0f,
                    animationSpec = infiniteRepeatable(
                        animation = keyframes {
                            durationMillis = CardGlowCycleMs
                            0f at 0
                            glowPeakAlpha at CardGlowFadeInMs using FastOutSlowInEasing
                            glowPeakAlpha at CardGlowHoldMs
                            0f at CardGlowFadeOutMs
                            0f at CardGlowCycleMs
                        }
                    ),
                    label = "card_glow_alpha"
                )
                val fillProgress by glowTransition.animateFloat(
                    initialValue = 0f,
                    targetValue = 0f,
                    animationSpec = infiniteRepeatable(
                        animation = keyframes {
                            durationMillis = CardGlowCycleMs
                            0f at 0
                            1f at CardGlowHoldMs using FastOutSlowInEasing
                            1f at CardGlowCycleMs
                        }
                    ),
                    label = "card_glow_fill"
                )
                // 💡 Radial, anchored at the top-left corner, radius = the card's own diagonal --
                // so the transparent edge of the gradient lands exactly at the far corner and the
                // glow visibly spans/fills the whole card instead of reading as a flat tint.
                Box(
                    Modifier
                        .matchParentSize()
                        .drawBehind {
                            val diagonal = sqrt(size.width * size.width + size.height * size.height)
                            val radius = if (glowFill) (diagonal * fillProgress).coerceAtLeast(1f) else diagonal
                            val centerOffset = when (glowOrigin) {
                                GlowOrigin.TOP_LEFT -> Offset.Zero
                                GlowOrigin.TOP_RIGHT -> Offset(size.width, 0f)
                            }
                            drawRect(
                                brush = Brush.radialGradient(
                                    colorStops = arrayOf(
                                        0f to glowColor.copy(alpha = glowAlpha),
                                        0.6f to glowColor.copy(alpha = glowAlpha * CardGlowMidAlphaFraction),
                                        1f to glowColor.copy(alpha = 0f)
                                    ),
                                    center = centerOffset,
                                    radius = radius
                                )
                            )
                        }
                )
                Column(content = content)
            }
        } else {
            Column(content = content)
        }
    }
}

private const val PressedScale = 0.98f

// 💡 Radial from the top-left corner, ~3.2s cycle (fade in over 500ms, hold near-peak to
// ~1800ms, fade out by 2600ms, idle the rest) -- peak alpha raised from an earlier, too-faint
// 0.07 pass. Adjust here if it reads too strong/weak once running.
private const val CardGlowCycleMs = 3200
private const val CardGlowFadeInMs = 500
private const val CardGlowHoldMs = 1800
private const val CardGlowFadeOutMs = 2600
private const val CardGlowPeakAlpha = 0.32f
private const val CardGlowMidAlphaFraction = 0.5f

// 💡 Weighted heavily toward ambient over spot (see the shadow comment above) so the drop shadow
// every `PulseCard` casts reads as an even halo rather than the platform's default bottom-heavy
// key-light shadow. Plain translucent black in both modes -- the shadow sits behind every preset's
// card, not tinted to any one accent. Light mode's pair is stronger than dark mode's -- see the
// shadow comment in `PulseCard` above for why. Light mode's numbers have gone through three passes
// now (each asking for a stronger shadow than the last), dark mode's were asked to stay untouched
// at their original values every time.
private val CardShadowAmbientLight = Color.Black.copy(alpha = 0.50f)
private val CardShadowSpotLight = Color.Black.copy(alpha = 0.24f)
private val CardShadowAmbientDark = Color.Black.copy(alpha = 0.24f)
private val CardShadowSpotDark = Color.Black.copy(alpha = 0.10f)

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

@Preview(name = "Light — Lilac is dark, so preview Navy for light", showBackground = true)
@Composable
private fun PreviewPulseCardStylesLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        PreviewPulseCardStylesContent()
    }
}

@Preview(name = "Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewPulseCardStylesDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        PreviewPulseCardStylesContent()
    }
}

@Composable
private fun PreviewPulseCardStylesContent() {
    Column(
        modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large)),
        verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_medium))
    ) {
        PulseCard(style = PulseCardStyle.DATA, modifier = Modifier.fillMaxWidth()) {
            Text(text = "DATA", modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large)))
        }
        PulseCard(style = PulseCardStyle.SYNTHESIS, modifier = Modifier.fillMaxWidth()) {
            Text(text = "SYNTHESIS", modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large)))
        }
        PulseCard(style = PulseCardStyle.DATA_SPARKLINE, modifier = Modifier.fillMaxWidth()) {
            Text(text = "DATA_SPARKLINE", modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large)))
        }
    }
}
