package com.marketlabs.pulse.storage.model.stocks

// Generated by Claude Code.

/**
 * A symbol's most recent Deep Dive — fetched and cached separately from `StockDetail` (own table,
 * own `deepVersion`-compare short-circuit in `StockAnalysisRepositoryImpl.refreshDeepDive`), since
 * it's large and refreshes only every ~14 days, and not every session opens the Deep Dive screen.
 * Absent (not fetched, or the symbol has never had a deep dive — a 404 from the backend) rather
 * than a distinct sealed state, per this project's UiState convention.
 */
data class StockDeepDive(
    val symbol: String,
    val lastSyncedTimestamp: Long,

    val deepAnalysisDate: String? = null,
    val deepVersion: Long? = null,
    val earningsTriggered: Boolean? = null,
    val sections: List<DomainDeepDiveSection>? = null,

    /** Empty on a symbol's first-ever deep dive or a same-day rerun with no real change -- both normal, not errors. */
    val fundamentalsDelta: List<DomainFundamentalsDelta>? = null,

    val nextDeepDiveTriggerDate: String? = null,
    val nextDeepDiveTriggerReason: String? = null
)

data class DomainDeepDiveSection(
    val topic: String? = null,
    val heading: String? = null,
    val body: String? = null,
    val headlineStat: DomainDeepDiveHeadlineStat? = null,
    val highlights: List<DomainDeepDiveHighlight> = emptyList()
)

/** The one hero number for a Deep Dive section's quick-view, e.g. "Forward P/E" / "24.75x". No severity/color of its own -- see [DomainDeepDiveSection]'s doc comment. */
data class DomainDeepDiveHeadlineStat(
    val label: String? = null,
    val value: String? = null
)

/** One of 2-5 short figure-only stat chips backing a Deep Dive section's prose. `note`, when present, states a comparison, never a verdict -- the backend's own rule, not enforced client-side. */
data class DomainDeepDiveHighlight(
    val label: String? = null,
    val value: String? = null,
    val note: String? = null
)

/** One changed `market_fundamentals` numeric field between this deep dive and the prior one. `field` is the backend's raw snake_case field name (e.g. "target_mean", "pe_forward"), not a fixed enum. */
data class DomainFundamentalsDelta(
    val field: String? = null,
    val from: Double? = null,
    val fromDate: String? = null,
    val to: Double? = null,
    val toDate: String? = null
)
