package com.marketlabs.pulse.ui.screens.stocks.detail.timeline

// Generated by Claude Code.

import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.marketlabs.pulse.core.stocks.StockAnalysisRepository
import com.marketlabs.pulse.ui.common.UiError
import com.marketlabs.pulse.ui.common.toUiError
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import javax.inject.Inject

/**
 * Drives the pushed "View More" destination for Resolved Calls -- its own destination (own
 * back-stack entry, own `hiltViewModel()` instance), not folded into `StockDetailViewModel`: same
 * reasoning as `DeepDiveViewModel`, no chart/tab state to share. Reads the same
 * `getStockDetailStream(symbol)`/`refreshDetail` pair `StockDetailViewModel` already uses -- by the
 * time this screen is reachable, Stock Detail has already fetched (and cached) the symbol's
 * detail, so `refreshDetail(force = false)` here is normally a cache hit, not a fresh fetch.
 */
@HiltViewModel
class ResolvedCallsListViewModel @Inject constructor(
    private val repository: StockAnalysisRepository,
    savedStateHandle: SavedStateHandle
) : ViewModel() {

    private val symbol: String = checkNotNull(savedStateHandle[ARG_SYMBOL]) {
        "ResolvedCallsListViewModel requires a non-null \"$ARG_SYMBOL\" nav argument"
    }

    private val _isLoading = MutableStateFlow(false)
    private val _error = MutableStateFlow<UiError?>(null)

    val uiState: StateFlow<ResolvedCallsListUiState> = combine(
        repository.getStockDetailStream(symbol), _isLoading, _error
    ) { detail, isLoading, error ->
        ResolvedCallsListUiState(
            symbol = symbol,
            resolvedCalls = detail?.calls?.resolved.orEmpty().sortedByDescending { it.resolvedOn ?: it.madeOn ?: "" },
            isLoading = isLoading && detail == null,
            error = error
        )
    }.stateIn(
        scope = viewModelScope,
        started = SharingStarted.WhileSubscribed(5000),
        initialValue = ResolvedCallsListUiState(symbol = symbol, isLoading = true)
    )

    /** Called by the UI when the screen becomes visible. */
    fun onStart() {
        fetchDetail(force = false)
    }

    /** Clears any active error (e.g. after a Snackbar is dismissed). */
    fun clearError() {
        _error.value = null
    }

    private fun fetchDetail(force: Boolean) {
        viewModelScope.launch {
            _isLoading.value = true
            _error.value = null

            val result = repository.refreshDetail(symbol, force)

            if (result.isFailure) {
                _error.value = result.exceptionOrNull().toUiError()
            }

            _isLoading.value = false
        }
    }

    companion object {
        /** Must match the nav argument name in the `resolvedCallsList/{symbol}` route. */
        const val ARG_SYMBOL = "symbol"
    }
}
