package com.marketlabs.pulse.ui.screens.stocks.detail.timeline

// Generated by Claude Code.

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.stocks.DomainForwardCall
import com.marketlabs.pulse.ui.components.PulseCard
import com.marketlabs.pulse.ui.components.PulseCardStyle
import com.marketlabs.pulse.ui.screens.stocks.detail.DataCardSectionHeader
import com.marketlabs.pulse.ui.screens.stocks.detail.sections.ResolvedCallCard
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme

/**
 * Stateless. Same `PulseCard(DATA)` + [DataCardSectionHeader] + divider-separated [ResolvedCallCard]
 * rows as the capped-to-7 card on Stock Detail's Timeline tab -- just the full, unclipped list,
 * reusing that same row composable so the two never drift apart visually.
 */
@Composable
fun ResolvedCallsListScreen(
    resolvedCalls: List<DomainForwardCall>,
    isLoading: Boolean,
    contentPadding: PaddingValues,
    modifier: Modifier = Modifier
) {
    if (resolvedCalls.isEmpty()) {
        Box(modifier = modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
            Text(
                text = if (isLoading) "" else stringResource(id = R.string.stock_detail_tab_nothing_yet),
                style = MaterialTheme.typography.bodyMedium,
                color = LocalPulseColors.current.onSurfaceMuted
            )
            if (isLoading) {
                CircularProgressIndicator()
            }
        }
        return
    }

    LazyColumn(modifier = modifier.fillMaxSize(), contentPadding = contentPadding) {
        item {
            PulseCard(style = PulseCardStyle.DATA, modifier = Modifier.fillMaxWidth()) {
                Column {
                    DataCardSectionHeader(title = stringResource(id = R.string.stock_detail_resolved_calls_title))
                    resolvedCalls.forEachIndexed { index, call ->
                        ResolvedCallCard(call, modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large)))
                        if (index != resolvedCalls.lastIndex) {
                            HorizontalDivider(
                                color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.1f),
                                thickness = dimensionResource(id = R.dimen.border_thin)
                            )
                        }
                    }
                }
            }
        }
    }
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

private val mockResolvedCalls = listOf(
    DomainForwardCall(
        predicate = "CLOSE_BELOW",
        level = 234.66,
        statement = "Closes below its 200-day moving average of \$234.66 over the next five sessions as distribution pressure persists.",
        outcomeNote = "Closed below \$234.66 within the window.",
        madeOn = "2026-07-28",
        resolveDate = "2026-08-04",
        resolvedOn = "2026-08-04",
        resolvedPrice = 284.02,
        status = "HELD"
    ),
    DomainForwardCall(
        predicate = "CLOSE_ABOVE",
        level = 274.75,
        statement = "Closes above resistance of \$274.75 within the next five sessions as bullish momentum continues.",
        outcomeNote = "Closed above \$274.75 within the window.",
        madeOn = "2026-07-31",
        resolveDate = "2026-08-07",
        resolvedOn = "2026-08-07",
        resolvedPrice = 272.26,
        status = "HELD"
    )
)

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewResolvedCallsListScreen() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        ResolvedCallsListScreen(
            resolvedCalls = mockResolvedCalls,
            isLoading = false,
            contentPadding = PaddingValues(dimensionResource(id = R.dimen.padding_large))
        )
    }
}
