package com.marketlabs.pulse.ui.screens.stocks.detail.timeline

// Generated by Claude Code.

import com.marketlabs.pulse.storage.model.stocks.DomainForwardCall
import com.marketlabs.pulse.ui.common.UiError

/**
 * `symbol` is always known immediately (nav argument). `resolvedCalls` is already sorted
 * newest-first (by `resolvedOn`, falling back to `madeOn`) -- same sort `ResolvedCallsSection` on
 * Stock Detail itself applies before capping to 7, just unclipped here.
 */
data class ResolvedCallsListUiState(
    val symbol: String,
    val resolvedCalls: List<DomainForwardCall> = emptyList(),
    val isLoading: Boolean = false,
    val error: UiError? = null
)
