package com.marketlabs.pulse.ui.screens.stocks.detail.timeline

// Generated by Claude Code.

import com.marketlabs.pulse.storage.model.stocks.DomainEventLogItem
import com.marketlabs.pulse.ui.common.UiError

/**
 * `symbol` is always known immediately (nav argument). `events` is already sorted newest-first --
 * same sort `EventLog` on Stock Detail itself applies before capping to 7, just unclipped here.
 */
data class TechnicalTimelineListUiState(
    val symbol: String,
    val events: List<DomainEventLogItem> = emptyList(),
    val isLoading: Boolean = false,
    val error: UiError? = null
)
