package com.marketlabs.pulse.ui.components.widgets

// Generated by Claude Code.

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.res.stringResource
import com.marketlabs.pulse.R
import com.marketlabs.pulse.ui.components.bottomSheet.ScreenGuideSheet

/** Bundles one screen's guide copy -- `AppTopBar` takes this as a single nullable param rather
 * than three separate ones, since every call site either has all three or none. */
data class ScreenGuideContent(
    val screenTitle: String,
    val overview: String,
    val howToInterpret: String
)

/**
 * Once-per-screen "?" -- explains what the screen is about and how to interpret the different
 * things on it (a screen-level guide, distinct from a single value's own explainer or a single AI
 * card's "how generated" disclosure). Self-contained sheet-visibility state, same pattern
 * [MetricInfoAction] already uses, so a call site just drops this into its top bar/header with no
 * external state to thread.
 *
 * `IconButton` + `icon_size_large` (24dp), not a raw `Modifier.clickable` Icon at `icon_size_medium`
 * (20dp) -- this sits directly beside `AppTopBar`'s Settings gear (a plain, unsized `Icon` inside
 * `IconButton`, which renders at its drawable's own intrinsic 24dp), so it needs the exact same
 * icon size AND the same `IconButton` touch-target/ripple treatment to read as two equally-weighted
 * actions in the same bar, not one bigger with a real touch target and one smaller as an afterthought.
 */
@Composable
fun ScreenGuideAction(
    screenTitle: String,
    overview: String,
    howToInterpret: String,
    modifier: Modifier = Modifier
) {
    var showSheet by remember { mutableStateOf(false) }

    IconButton(onClick = { showSheet = true }, modifier = modifier) {
        Icon(
            painter = painterResource(id = R.drawable.ic_help),
            contentDescription = stringResource(id = R.string.screen_guide_content_description, screenTitle),
            tint = MaterialTheme.colorScheme.onSurfaceVariant,
            modifier = Modifier.size(dimensionResource(id = R.dimen.icon_size_large))
        )
    }

    if (showSheet) {
        ScreenGuideSheet(
            screenTitle = screenTitle,
            overview = overview,
            howToInterpret = howToInterpret,
            onDismiss = { showSheet = false }
        )
    }
}
