package com.marketlabs.pulse.ui.screens.legal

// Generated by Claude Code.

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.ui.components.DocumentSectionsScreen
import com.marketlabs.pulse.ui.theme.MarketPulseTheme

/**
 * spec-20260915-compliance-disclaimers.md §4. Claude-generated content — NOT LEGAL ADVICE, needs
 * real legal review before shipping. Assumes Firebase Analytics, Firestore, and App Check
 * (Play Integrity) are the active Firebase products (confirmed dependencies as of this writing);
 * Crashlytics is deliberately NOT mentioned — confirmed not a dependency in this app. `[TODO: ...]`
 * markers stand in for a contact email not yet supplied.
 */
@Composable
fun PrivacyPolicyScreen(onNavigateUp: () -> Unit) {
    val sections = listOf(
        stringResource(id = R.string.privacy_section_1_title) to stringResource(id = R.string.privacy_section_1_body),
        stringResource(id = R.string.privacy_section_2_title) to stringResource(id = R.string.privacy_section_2_body),
        stringResource(id = R.string.privacy_section_3_title) to stringResource(id = R.string.privacy_section_3_body),
        stringResource(id = R.string.privacy_section_4_title) to stringResource(id = R.string.privacy_section_4_body),
        stringResource(id = R.string.privacy_section_5_title) to stringResource(id = R.string.privacy_section_5_body),
        stringResource(id = R.string.privacy_section_6_title) to stringResource(id = R.string.privacy_section_6_body),
        stringResource(id = R.string.privacy_section_7_title) to stringResource(id = R.string.privacy_section_7_body),
        stringResource(id = R.string.privacy_section_8_title) to stringResource(id = R.string.privacy_section_8_body),
        stringResource(id = R.string.privacy_section_9_title) to stringResource(id = R.string.privacy_section_9_body)
    )

    DocumentSectionsScreen(
        title = stringResource(id = R.string.privacy_policy_screen_title),
        lastUpdatedLabel = stringResource(id = R.string.legal_last_updated_todo),
        sections = sections,
        onNavigateUp = onNavigateUp
    )
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewPrivacyPolicyScreenLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        PrivacyPolicyScreen(onNavigateUp = {})
    }
}

@Preview(name = "Dark", showBackground = true)
@Composable
private fun PreviewPrivacyPolicyScreenDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        PrivacyPolicyScreen(onNavigateUp = {})
    }
}
