package com.marketlabs.pulse.ui.screens.legal

// Generated by Claude Code.

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.ui.components.DocumentSectionsScreen
import com.marketlabs.pulse.ui.theme.MarketPulseTheme

/**
 * spec-20260915-compliance-disclaimers.md §3. Claude-generated content grounded in common patterns
 * for financial-data apps — NOT LEGAL ADVICE, needs real legal review before shipping. `[TODO: ...]`
 * markers in the section bodies stand in for entity name / jurisdiction / contact email not yet
 * supplied.
 */
@Composable
fun TermsConditionsScreen(onNavigateUp: () -> Unit) {
    val sections = listOf(
        stringResource(id = R.string.terms_section_1_title) to stringResource(id = R.string.terms_section_1_body),
        stringResource(id = R.string.terms_section_2_title) to stringResource(id = R.string.terms_section_2_body),
        stringResource(id = R.string.terms_section_3_title) to stringResource(id = R.string.terms_section_3_body),
        stringResource(id = R.string.terms_section_4_title) to stringResource(id = R.string.terms_section_4_body),
        stringResource(id = R.string.terms_section_5_title) to stringResource(id = R.string.terms_section_5_body),
        stringResource(id = R.string.terms_section_6_title) to stringResource(id = R.string.terms_section_6_body),
        stringResource(id = R.string.terms_section_7_title) to stringResource(id = R.string.terms_section_7_body),
        stringResource(id = R.string.terms_section_8_title) to stringResource(id = R.string.terms_section_8_body),
        stringResource(id = R.string.terms_section_9_title) to stringResource(id = R.string.terms_section_9_body),
        stringResource(id = R.string.terms_section_10_title) to stringResource(id = R.string.terms_section_10_body),
        stringResource(id = R.string.terms_section_11_title) to stringResource(id = R.string.terms_section_11_body),
        stringResource(id = R.string.terms_section_12_title) to stringResource(id = R.string.terms_section_12_body),
        stringResource(id = R.string.terms_section_13_title) to stringResource(id = R.string.terms_section_13_body)
    )

    DocumentSectionsScreen(
        title = stringResource(id = R.string.terms_conditions_screen_title),
        lastUpdatedLabel = stringResource(id = R.string.legal_last_updated_todo),
        sections = sections,
        onNavigateUp = onNavigateUp
    )
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewTermsConditionsScreenLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        TermsConditionsScreen(onNavigateUp = {})
    }
}

@Preview(name = "Dark", showBackground = true)
@Composable
private fun PreviewTermsConditionsScreenDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        TermsConditionsScreen(onNavigateUp = {})
    }
}
