package com.marketlabs.pulse.ui.screens.stocks.detail

// Generated by Claude Code.

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import com.marketlabs.pulse.R
import com.marketlabs.pulse.ui.theme.LocalPulseColors

/**
 * The three label styles every Detail section reuses, factored out once rather than duplicated
 * across 15 section files (the Design mockups repeat each of these verbatim across the sections
 * that use them):
 *
 * - [SectionDividerLabel]: a page-level heading sitting directly on the background between cards
 *   (WHAT TO WATCH, SIGNAL CONDITIONS, CONSIDER, FORWARD CALLS, EVENT LOG, DIRECT NEWS) -- accent-
 *   colored, bold, all-caps, with an optional muted trailing bit of context on the same row
 *   ("tap a chip for why", "2 of 2 recent calls held").
 * - [DataCardTitleLabel]: the muted title sitting inside a `PulseCard(DATA)` (KEY LEVELS,
 *   FUNDAMENTALS).
 * - [SynthesisCardHeader]: the Ai-glyph + title pairing inside a `PulseCard(SYNTHESIS)` (PLAIN
 *   READ, DEEP STUDY, SCENARIOS) -- same icon+sizing-to-text-height treatment
 *   `DashboardScreen`'s Technical Briefing card and `StockPreviewCard` already use elsewhere.
 */
@Composable
fun SectionDividerLabel(title: String, trailing: String? = null) {
    val pulseColors = LocalPulseColors.current

    Row(verticalAlignment = Alignment.CenterVertically) {
        Text(
            text = title,
            style = MaterialTheme.typography.labelLarge.copy(fontWeight = FontWeight.Bold),
            color = pulseColors.accentPrimary,
            modifier = Modifier.weight(1f, fill = false)
        )
        trailing?.let {
            Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_medium)))
            Text(
                text = it,
                style = MaterialTheme.typography.labelMedium,
                color = pulseColors.onSurfaceMuted
            )
        }
    }
}

@Composable
fun DataCardTitleLabel(title: String) {
    Text(
        text = title,
        style = MaterialTheme.typography.labelLarge,
        color = LocalPulseColors.current.onSurfaceMuted
    )
}

/**
 * [DataCardTitleLabel] plus a trailing info icon -- for a section whose card groups several
 * metrics at once (Key Levels, Fundamentals, Macro, Setup Reasoning), tapping this icon opens one
 * `StockAnalysisGlossaryBottomSheet` covering everything in that card, instead of a tooltip per
 * metric. A metric with no such grouping card (HeadlineMetricsStrip, which sits directly on the
 * background) keeps its own per-metric [InfoIcon] via [LabelWithInfo] -- this is the alternative
 * for when a "whole view" already exists to hang the explanation off of.
 */
@Composable
fun DataCardTitleWithInfo(title: String, onInfoClick: () -> Unit) {
    val pulseColors = LocalPulseColors.current

    Row(verticalAlignment = Alignment.CenterVertically) {
        DataCardTitleLabel(title = title)
        Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_tiny)))
        Icon(
            painter = painterResource(id = R.drawable.ic_info),
            contentDescription = stringResource(id = R.string.stock_detail_view_definitions_content_description, title),
            tint = pulseColors.onSurfaceMuted,
            modifier = Modifier
                .size(dimensionResource(id = R.dimen.icon_size_small))
                .clickable(onClick = onInfoClick)
        )
    }
}

@Composable
fun SynthesisCardHeader(title: String) {
    val pulseColors = LocalPulseColors.current
    val titleStyle = MaterialTheme.typography.labelLarge.copy(fontWeight = FontWeight.Bold)
    val glyphSize = with(LocalDensity.current) { titleStyle.fontSize.toDp() }

    Row(verticalAlignment = Alignment.CenterVertically) {
        Icon(
            painter = painterResource(id = R.drawable.ic_engine_ai_sparkles),
            contentDescription = stringResource(id = R.string.stock_analysis_ai_glyph_content_description),
            tint = pulseColors.accentPrimary,
            modifier = Modifier.size(glyphSize)
        )
        Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_small)))
        Text(text = title, style = titleStyle, color = pulseColors.accentPrimary)
    }
}

/** The small accent-colored cluster labels inside Fundamentals (VALUATION, PROFITABILITY, ...). */
@Composable
fun SubClusterLabel(title: String) {
    Text(
        text = title,
        style = MaterialTheme.typography.labelMedium.copy(fontWeight = FontWeight.Bold),
        color = LocalPulseColors.current.accentPrimary
    )
}

/**
 * An unfilled, bordered pill for a classification that isn't a signal read on its own -- the
 * `technical_setup` badge on `DetailHeader` and the impact-level badge on `DirectNews` both use
 * this same treatment.
 */
@Composable
fun OutlinedBadge(text: String) {
    val pulseColors = LocalPulseColors.current

    Surface(
        color = MaterialTheme.colorScheme.background,
        shape = RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_pill)),
        border = BorderStroke(dimensionResource(id = R.dimen.border_thin), pulseColors.accentSurfaceBorder)
    ) {
        Text(
            text = text,
            style = MaterialTheme.typography.labelMedium,
            color = pulseColors.onSurfaceMuted,
            modifier = Modifier.padding(
                horizontal = dimensionResource(id = R.dimen.padding_medium),
                vertical = dimensionResource(id = R.dimen.padding_small)
            )
        )
    }
}
