package com.marketlabs.pulse.ui.screens.stocks.detail

// Generated by Claude Code.

import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.stocks.DomainWatchItem
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme

/**
 * A callout at the top of every tab's content -- the first `HIGH`-urgency `watch_list` item, if
 * any, shown as its full sentence (no truncation). Separate from the full `WatchList` section
 * (unmodified, still living in the Technicals tab) -- that renders every watch item regardless of
 * urgency; this promotes just the most urgent one to the top of whichever tab a user is on.
 * Colored `signal.bearish` (not `signal.warning`, which is what `WatchList`'s own HIGH items use)
 * -- a deliberately more alarming treatment for the one item pulled out here. Renders nothing if
 * there's no HIGH item.
 */
@Composable
fun HighUrgencyAlertRow(watchList: List<DomainWatchItem>?, modifier: Modifier = Modifier) {
    val text = watchList.orEmpty().firstOrNull { it.urgency?.uppercase() == "HIGH" }?.text ?: return
    val pulseColors = LocalPulseColors.current

    Surface(
        color = pulseColors.signalBearishPill,
        shape = RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_small)),
        modifier = modifier.fillMaxWidth()
    ) {
        Text(
            text = text,
            style = MaterialTheme.typography.bodySmall,
            color = pulseColors.signalBearishText,
            modifier = Modifier.padding(
                horizontal = dimensionResource(id = R.dimen.padding_large),
                vertical = dimensionResource(id = R.dimen.padding_medium)
            )
        )
    }
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

private val mockWatchList = listOf(
    DomainWatchItem(kind = "LEVEL_DISTANCE", text = "Resistance at \$274.75 is 0.1% away — about 0.0 typical daily moves.", urgency = "HIGH"),
    DomainWatchItem(kind = "LEVEL_DISTANCE", text = "Support at \$255.19 is 7.0% away, about 2.1 typical daily moves.", urgency = "MEDIUM")
)

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewHighUrgencyAlertRowLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        HighUrgencyAlertRow(watchList = mockWatchList)
    }
}

@Preview(name = "Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewHighUrgencyAlertRowDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        HighUrgencyAlertRow(watchList = mockWatchList)
    }
}
