package com.marketlabs.pulse.ui.screens.stocks.detail

// Generated by Claude Code.

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.statusBars
import androidx.compose.foundation.layout.windowInsetsPadding
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.SnackbarHost
import androidx.compose.material3.SnackbarHostState
import androidx.compose.material3.pulltorefresh.PullToRefreshBox
import androidx.compose.material3.pulltorefresh.PullToRefreshDefaults.Indicator
import androidx.compose.material3.pulltorefresh.rememberPullToRefreshState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalLifecycleOwner
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.stringResource
import androidx.hilt.lifecycle.viewmodel.compose.hiltViewModel
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.LifecycleEventObserver
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.marketlabs.pulse.R
import com.marketlabs.pulse.ui.components.PulseTabRow
import com.marketlabs.pulse.ui.screens.stocks.StockDetailViewModel
import com.marketlabs.pulse.ui.screens.stocks.detail.sections.DeepDiveCard
import com.marketlabs.pulse.ui.screens.stocks.detail.sections.DetailHeader
import com.marketlabs.pulse.ui.screens.stocks.views.StockAnalysisErrorState

/**
 * Stateful entry point for the pushed `stockAnalysis/{symbol}` destination. Only `DetailHeader`
 * and the pill tab bar are pinned now -- `TechnicalRead` and the HIGH-urgency alert moved into the
 * scrollable tab content (see `StockDetailScreen`) so they don't permanently eat into the tabs'
 * share of the screen. `StockDetailScreen` (the selected tab's content) sits inside the
 * pull-to-refresh area, so pulling down works from any tab but never disturbs the pinned zone
 * above it. `Modifier.windowInsetsPadding(WindowInsets.statusBars)` handles the status-bar inset
 * directly -- this route has no Material `TopAppBar` to lean on for that (see `MainActivity`'s
 * `isPushedDestination`, which excludes this route from the global collapsing top bar entirely).
 * The floating bottom nav is hidden here too (same `isPushedDestination` check) -- only the pinned
 * zone and tab bar act as this screen's chrome.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun StockDetailRoute(
    scaffoldPadding: PaddingValues,
    onNavigateUp: () -> Unit,
    onNavigateToWebView: (String) -> Unit,
    onNavigateToDeepDive: (String) -> Unit,
    viewModel: StockDetailViewModel = hiltViewModel()
) {
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()
    val snackbarHostState = remember { SnackbarHostState() }
    val pullRefreshState = rememberPullToRefreshState()
    val lifecycleOwner = LocalLifecycleOwner.current

    DisposableEffect(lifecycleOwner) {
        val observer = LifecycleEventObserver { _, event ->
            when (event) {
                Lifecycle.Event.ON_START -> viewModel.onStart()
                Lifecycle.Event.ON_STOP -> viewModel.onStop()
                else -> {}
            }
        }
        lifecycleOwner.lifecycle.addObserver(observer)
        onDispose {
            lifecycleOwner.lifecycle.removeObserver(observer)
        }
    }

    LaunchedEffect(uiState.error) {
        uiState.error?.message?.let { message ->
            snackbarHostState.showSnackbar(message)
            viewModel.clearError()
        }
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .windowInsetsPadding(WindowInsets.statusBars)
    ) {
        DetailHeader(
            symbol = uiState.symbol,
            name = uiState.preview?.name,
            price = uiState.preview?.price,
            changePercent = uiState.preview?.changePercent,
            technicalSetup = uiState.preview?.technicalSetup,
            regimeAtAnalysis = uiState.preview?.regimeAtAnalysis,
            analyzedAsOfTimestamp = uiState.detail?.timestamp,
            onNavigateUp = onNavigateUp,
            modifier = Modifier.fillMaxWidth()
        )

        // 💡 Chrome-level, not tab content -- visible regardless of which tab is selected, per the
        // per-symbol-intelligence spec's "a banner ... on the detailed page" placement.
        DeepDiveCard(
            deepAnalysisDate = uiState.preview?.deepAnalysisDate,
            nextDeepDiveTriggerDate = uiState.preview?.nextDeepDiveTriggerDate,
            onClick = { onNavigateToDeepDive(uiState.symbol) },
            modifier = Modifier
                .fillMaxWidth()
                .padding(
                    horizontal = dimensionResource(id = R.dimen.padding_large),
                    vertical = dimensionResource(id = R.dimen.padding_small)
                )
        )

        PulseTabRow(
            tabs = DetailTab.entries.map { stringResource(id = it.labelRes) },
            selectedTabIndex = uiState.selectedTabIndex,
            onTabSelected = viewModel::onTabSelected
        )

        Box(modifier = Modifier.fillMaxSize()) {
            PullToRefreshBox(
                isRefreshing = uiState.isRefreshing,
                onRefresh = { viewModel.refresh() },
                state = pullRefreshState,
                indicator = {
                    Indicator(
                        modifier = Modifier.align(Alignment.TopCenter),
                        isRefreshing = uiState.isRefreshing,
                        state = pullRefreshState
                    )
                }
            ) {
                when {
                    uiState.detail != null -> {
                        StockDetailScreen(
                            detail = uiState.detail,
                            preview = uiState.preview,
                            selectedTabIndex = uiState.selectedTabIndex,
                            expandedChipIds = uiState.expandedChipIds,
                            expandedNewsIds = uiState.expandedNewsIds,
                            chartSeries = uiState.chartSeries,
                            selectedChartRange = uiState.selectedChartRange,
                            isChartLoading = uiState.isChartLoading,
                            intradaySeries = uiState.intradaySeries,
                            availableChartRanges = uiState.availableChartRanges,
                            onChartRangeSelected = viewModel::selectChartRange,
                            onToggleChip = viewModel::toggleChipExpanded,
                            onToggleNews = viewModel::toggleNewsExpanded,
                            onArticleClick = onNavigateToWebView,
                            scaffoldPadding = scaffoldPadding
                        )
                    }

                    uiState.isLoading -> {
                        Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                            CircularProgressIndicator()
                        }
                    }

                    uiState.error != null -> {
                        StockAnalysisErrorState(error = uiState.error!!, onRetry = { viewModel.refresh() })
                    }

                    // Defensive fallback only -- `detail`/`isLoading`/`error` in practice always
                    // cover the real states (the ViewModel starts `isLoading = true` and a fetch
                    // is always in flight by the time this composes).
                    else -> {
                        Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                            CircularProgressIndicator()
                        }
                    }
                }
            }

            SnackbarHost(
                hostState = snackbarHostState,
                modifier = Modifier
                    .align(Alignment.BottomCenter)
                    .padding(bottom = scaffoldPadding.calculateBottomPadding())
            )
        }
    }
}

