package com.marketlabs.pulse.network.store.stocks

// Generated by Claude Code.

import android.util.Log
import com.marketlabs.pulse.network.api.StocksApi
import com.marketlabs.pulse.storage.model.stocks.StockDeepDive
import com.marketlabs.pulse.storage.model.stocks.StockDetail
import com.marketlabs.pulse.storage.model.stocks.StockPreview
import com.marketlabs.pulse.storage.model.stocks.mappers.toDomain
import retrofit2.HttpException
import javax.inject.Inject

/**
 * 💡 THOUGHT PROCESS:
 * `getStockPreviews()` replaces the old tracked-symbols-then-N-fetches dance with a single call to
 * `GET /stocks/previews` — the backend's own comment on that route says this exists specifically
 * to replace that N+1 pattern. `getStockDetail(symbol)` is fetched on demand, one symbol at a
 * time, when the (future) UI opens a symbol — not batched, since the detail payload is ~6x the
 * size of a preview and there's no reason to pull all of them upfront.
 */
class RemoteStockDataSourceImpl @Inject constructor(
    private val api: StocksApi
) : RemoteStockDataSource {

    override suspend fun getStockPreviews(): Result<List<StockPreview>> {
        return try {
            val syncTimestamp = System.currentTimeMillis()
            val response = api.getStockPreviews()

            val previews = response.previews
                .orEmpty()
                .mapNotNull { it.toDomain(lastSyncedTimestamp = syncTimestamp) }

            Result.success(previews)
        } catch (e: Exception) {
            Log.e("StockAnalysis", "Failed to fetch stock previews", e)
            Result.failure(e)
        }
    }

    override suspend fun getStockDetail(symbol: String): Result<StockDetail> {
        return try {
            val syncTimestamp = System.currentTimeMillis()
            val detail = api.getStockDetail(symbol).toDomain(symbol = symbol, lastSyncedTimestamp = syncTimestamp)

            Result.success(detail)
        } catch (e: Exception) {
            Log.e("StockAnalysis", "Failed to fetch stock detail for $symbol", e)
            Result.failure(e)
        }
    }

    /** 404 means this symbol has never had a deep dive run (cold start) -- a normal, expected state, not an error. */
    override suspend fun getStockDeepDive(symbol: String): Result<StockDeepDive?> {
        return try {
            val syncTimestamp = System.currentTimeMillis()
            val deepDive = api.getStockDeepDive(symbol).toDomain(symbol = symbol, lastSyncedTimestamp = syncTimestamp)

            Result.success(deepDive)
        } catch (e: HttpException) {
            if (e.code() == 404) {
                Log.d("StockAnalysis", "No deep dive yet for $symbol")
                Result.success(null)
            } else {
                Log.e("StockAnalysis", "Failed to fetch deep dive for $symbol", e)
                Result.failure(e)
            }
        } catch (e: Exception) {
            Log.e("StockAnalysis", "Failed to fetch deep dive for $symbol", e)
            Result.failure(e)
        }
    }
}
