package com.marketlabs.pulse.network.store.stocks

// Generated by Claude Code.

import com.marketlabs.pulse.storage.model.stocks.StockDeepDive
import com.marketlabs.pulse.storage.model.stocks.StockDetail
import com.marketlabs.pulse.storage.model.stocks.StockPreview

interface RemoteStockDataSource {

    /** Fetches every analyzed symbol's preview from `GET /stocks/previews` in one call. */
    suspend fun getStockPreviews(): Result<List<StockPreview>>

    /** Fetches one symbol's full detail from `GET /stocks/{symbol}/detail`. */
    suspend fun getStockDetail(symbol: String): Result<StockDetail>

    /** Fetches one symbol's Deep Dive from `GET /stocks/{symbol}/detail/deep`. A 404 (no deep dive yet) is a successful `null`, not a failure. */
    suspend fun getStockDeepDive(symbol: String): Result<StockDeepDive?>
}
