package com.marketlabs.pulse.storage.database.entity

// Generated by Claude Code.

import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.TypeConverters
import com.marketlabs.pulse.storage.database.converters.StocksConverters
import com.marketlabs.pulse.storage.model.stocks.DomainDeepDiveSection
import com.marketlabs.pulse.storage.model.stocks.DomainFundamentalsDelta

/**
 * A symbol's most recent Deep Dive — its own table, separate from `market_stock_details`, since
 * it's large, refreshes only every ~14 days, and is fetched only when the Deep Dive screen is
 * first opened (not eagerly with the rest of detail). Cached with no TTL, same "shown until told
 * to refresh" convention as every other domain in this codebase — staleness is instead handled by
 * comparing `deepVersion` against the cached preview's own `deepVersion` before ever hitting the
 * network (see `StockAnalysisRepositoryImpl.refreshDeepDive`).
 */
@Entity(tableName = "market_stock_deep_dives")
@TypeConverters(StocksConverters::class)
data class StockDeepDiveEntity(
    @PrimaryKey val symbol: String,
    val lastSyncedTimestamp: Long,

    val deepAnalysisDate: String? = null,
    val deepVersion: Long? = null,
    val earningsTriggered: Boolean? = null,
    val sections: List<DomainDeepDiveSection>? = null,
    val fundamentalsDelta: List<DomainFundamentalsDelta>? = null,
    val nextDeepDiveTriggerDate: String? = null,
    val nextDeepDiveTriggerReason: String? = null
)
