package com.marketlabs.pulse.ui.screens.stocks.deepdive

// Generated by Claude Code.

import com.marketlabs.pulse.storage.model.stocks.StockDeepDive
import com.marketlabs.pulse.ui.common.UiError

/**
 * `symbol` is always known immediately (nav argument, not a network fetch). `deepDive` stays null
 * both while loading AND when the symbol has genuinely never had a deep dive (a 404, mapped to
 * `Result.success(null)` by `RemoteStockDataSourceImpl`) -- `isLoading` is what distinguishes the
 * two so the Screen can show a spinner in one case and the honest cold-start empty state in the
 * other, never a skeleton stuck on a symbol that simply has nothing yet.
 */
data class DeepDiveUiState(
    val symbol: String,
    val deepDive: StockDeepDive? = null,
    /** The cached preview's `name`, cross-referenced by symbol -- `StockDeepDive` carries no company name of its own, only the preview doc does (same reasoning as `StockDetailViewModel`'s `matchingPreview`). */
    val previewName: String? = null,
    val isLoading: Boolean = false,
    val error: UiError? = null
)
