package com.marketlabs.pulse.ui.screens.stocks.deepdive

// Generated by Claude Code.

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.stocks.DomainDeepDiveSection
import com.marketlabs.pulse.storage.model.stocks.DomainFundamentalsDelta
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme

/**
 * Stateless. One [DeepDiveSectionCard] per entry in `sections` -- NOT one card holding all of
 * them; "Deep Dive" itself is a page-level title rendered outside any card by `DeepDiveRoute`. The
 * cold-start empty state (a symbol that's never had a deep dive -- a 404, not an error) is a plain
 * static text, not a skeleton or the generic error screen, per the spec's "honest empty state" rule.
 *
 * `fundamentalsDelta` is only ever passed to the WHATS_CHANGED section's card -- the deltas are
 * what that section's prose narrates, so they're anchored there rather than a separate top-level
 * block. Empty/absent (a symbol's first-ever deep dive, or a same-day rerun with no real change)
 * renders no chips at all, not an empty-state placeholder.
 */
@Composable
fun DeepDiveScreen(
    sections: List<DomainDeepDiveSection>,
    fundamentalsDelta: List<DomainFundamentalsDelta>,
    isEmpty: Boolean,
    contentPadding: PaddingValues,
    modifier: Modifier = Modifier
) {
    if (isEmpty) {
        Box(modifier = modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
            Text(
                text = stringResource(id = R.string.deep_dive_empty_state),
                style = MaterialTheme.typography.bodyMedium,
                color = LocalPulseColors.current.onSurfaceMuted
            )
        }
        return
    }

    LazyColumn(
        modifier = modifier.fillMaxSize(),
        contentPadding = contentPadding,
        verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_large))
    ) {
        items(sections) { section ->
            DeepDiveSectionCard(
                kicker = topicKickerRes(section.topic)?.let { stringResource(id = it) },
                heading = section.heading.orEmpty(),
                body = section.body.orEmpty(),
                deltaChips = if (section.topic == "WHATS_CHANGED") fundamentalsDelta else emptyList()
            )
        }
    }
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

private val mockSections = listOf(
    DomainDeepDiveSection(
        topic = "WHAT_THE_COMPANY_IS",
        heading = "E-Commerce Pioneer and Cloud Infrastructure Giant",
        body = "Amazon.com, Inc. is a global giant operating in the consumer cyclical sector, spanning e-commerce retail, third-party marketplace services, subscription memberships, advertising, and cloud infrastructure through Amazon Web Services."
    ),
    DomainDeepDiveSection(
        topic = "WHATS_CHANGED",
        heading = "Analyst Targets Ticked Up on AI Capacity Buildout",
        body = "Since the last deep dive, Wall Street nudged its outlook higher after Amazon's forward AWS capacity commitments came into view."
    )
)

private val mockFundamentalsDelta = listOf(
    DomainFundamentalsDelta(field = "target_mean", from = 327.0, to = 328.0),
    DomainFundamentalsDelta(field = "pe_forward", from = 25.64, to = 24.75)
)

@Preview(name = "Populated", showBackground = true)
@Composable
private fun PreviewDeepDiveScreenPopulated() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        DeepDiveScreen(
            sections = mockSections,
            fundamentalsDelta = mockFundamentalsDelta,
            isEmpty = false,
            contentPadding = PaddingValues(dimensionResource(id = R.dimen.padding_large))
        )
    }
}

@Preview(name = "Cold start empty", showBackground = true)
@Composable
private fun PreviewDeepDiveScreenEmpty() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        DeepDiveScreen(
            sections = emptyList(),
            fundamentalsDelta = emptyList(),
            isEmpty = true,
            contentPadding = PaddingValues(dimensionResource(id = R.dimen.padding_large))
        )
    }
}
