package com.marketlabs.pulse.ui.screens.stocks.deepdive

// Generated by Claude Code.

import androidx.annotation.StringRes
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.FlowRow
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.stocks.DomainFundamentalsDelta
import com.marketlabs.pulse.ui.components.widgets.SignalPill
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme
import java.util.Locale

/**
 * Small chips under the WHATS_CHANGED section only (`DeepDiveSectionCard`'s `deltaChips` param) --
 * the structured form of what that section's prose already narrates in sentence form. Reuses
 * `SignalPill`, the same pill primitive `ConditionChipRow` renders condition chips with on the
 * tactical side -- no new chip component. Neutral-toned throughout: a delta isn't inherently
 * bullish/bearish (a higher P/E isn't a directional read on its own), so this doesn't attempt the
 * BULLISH/BEARISH/NEUTRAL coloring `ConditionChipRow` uses for actual signal chips.
 *
 * Empty `deltas` -> renders nothing (a symbol's first-ever deep dive, or a same-day rerun with no
 * real change, are both normal and expected, not an error state).
 */
@Composable
fun FundamentalsDeltaChips(deltas: List<DomainFundamentalsDelta>, modifier: Modifier = Modifier) {
    if (deltas.isEmpty()) return
    val pulseColors = LocalPulseColors.current

    FlowRow(
        modifier = modifier,
        horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_small)),
        verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_small))
    ) {
        deltas.forEach { delta ->
            fundamentalsDeltaChipText(delta)?.let { text ->
                SignalPill(text = text, pillColor = pulseColors.signalNeutralPill, contentColor = pulseColors.signalNeutralText)
            }
        }
    }
}

/** "{label}: {from} → {to}", e.g. "Analyst Target: $327 → $328". Null when `field`/`from`/`to` are missing -- a malformed entry is skipped, not rendered blank. `from_date`/`to_date` are deliberately not shown (v1 scope). */
@Composable
private fun fundamentalsDeltaChipText(delta: DomainFundamentalsDelta): String? {
    val field = delta.field ?: return null
    val from = delta.from ?: return null
    val to = delta.to ?: return null

    val meta = deltaFieldMeta[field]
    val label = meta?.let { stringResource(id = it.labelRes) }
        ?: field.replace('_', ' ').replaceFirstChar { it.titlecase(Locale.US) }
    val format = meta?.format ?: DeltaFieldFormat.RATIO

    return "$label: ${formatDeltaValue(from, format)} → ${formatDeltaValue(to, format)}"
}

private enum class DeltaFieldFormat { PERCENT, RATIO, DOLLAR }

private data class DeltaFieldMeta(@StringRes val labelRes: Int, val format: DeltaFieldFormat)

/**
 * Only the `market_fundamentals` numeric fields realistically expected to appear in a delta --
 * same "small lookup, same pattern as the topic kicker map" scope the field-label mapping was
 * asked to follow. An unmapped field (a future backend addition) falls back to a humanized version
 * of its raw snake_case name with plain formatting, rather than disappearing.
 */
private val deltaFieldMeta: Map<String, DeltaFieldMeta> = mapOf(
    "pe_trailing" to DeltaFieldMeta(R.string.fundamentals_delta_field_pe_trailing, DeltaFieldFormat.RATIO),
    "pe_forward" to DeltaFieldMeta(R.string.fundamentals_delta_field_pe_forward, DeltaFieldFormat.RATIO),
    "pe_median_5y" to DeltaFieldMeta(R.string.fundamentals_delta_field_pe_median_5y, DeltaFieldFormat.RATIO),
    "pe_percentile_5y" to DeltaFieldMeta(R.string.fundamentals_delta_field_pe_percentile_5y, DeltaFieldFormat.PERCENT),
    "pe_spread" to DeltaFieldMeta(R.string.fundamentals_delta_field_pe_spread, DeltaFieldFormat.RATIO),
    "pe_vs_median_pct" to DeltaFieldMeta(R.string.fundamentals_delta_field_pe_vs_median_pct, DeltaFieldFormat.PERCENT),
    "peg_ratio" to DeltaFieldMeta(R.string.fundamentals_delta_field_peg_ratio, DeltaFieldFormat.RATIO),
    "ev_ebitda" to DeltaFieldMeta(R.string.fundamentals_delta_field_ev_ebitda, DeltaFieldFormat.RATIO),
    "ev_revenue" to DeltaFieldMeta(R.string.fundamentals_delta_field_ev_revenue, DeltaFieldFormat.RATIO),
    "price_to_book" to DeltaFieldMeta(R.string.fundamentals_delta_field_price_to_book, DeltaFieldFormat.RATIO),
    "price_to_sales" to DeltaFieldMeta(R.string.fundamentals_delta_field_price_to_sales, DeltaFieldFormat.RATIO),
    "dividend_yield_pct" to DeltaFieldMeta(R.string.fundamentals_delta_field_dividend_yield_pct, DeltaFieldFormat.PERCENT),
    "gross_margin_pct" to DeltaFieldMeta(R.string.fundamentals_delta_field_gross_margin_pct, DeltaFieldFormat.PERCENT),
    "operating_margin_pct" to DeltaFieldMeta(R.string.fundamentals_delta_field_operating_margin_pct, DeltaFieldFormat.PERCENT),
    "profit_margin_pct" to DeltaFieldMeta(R.string.fundamentals_delta_field_profit_margin_pct, DeltaFieldFormat.PERCENT),
    "fcf_yield_pct" to DeltaFieldMeta(R.string.fundamentals_delta_field_fcf_yield_pct, DeltaFieldFormat.PERCENT),
    "roic_pct" to DeltaFieldMeta(R.string.fundamentals_delta_field_roic_pct, DeltaFieldFormat.PERCENT),
    "roe_pct" to DeltaFieldMeta(R.string.fundamentals_delta_field_roe_pct, DeltaFieldFormat.PERCENT),
    "roa_pct" to DeltaFieldMeta(R.string.fundamentals_delta_field_roa_pct, DeltaFieldFormat.PERCENT),
    "revenue_growth_yoy_pct" to DeltaFieldMeta(R.string.fundamentals_delta_field_revenue_growth_yoy_pct, DeltaFieldFormat.PERCENT),
    "eps_growth_yoy_pct" to DeltaFieldMeta(R.string.fundamentals_delta_field_eps_growth_yoy_pct, DeltaFieldFormat.PERCENT),
    "earnings_yield_pct" to DeltaFieldMeta(R.string.fundamentals_delta_field_earnings_yield_pct, DeltaFieldFormat.PERCENT),
    "consensus_strength_pct" to DeltaFieldMeta(R.string.fundamentals_delta_field_consensus_strength_pct, DeltaFieldFormat.PERCENT),
    "target_dispersion_pct" to DeltaFieldMeta(R.string.fundamentals_delta_field_target_dispersion_pct, DeltaFieldFormat.PERCENT),
    "capex_to_ocf_pct" to DeltaFieldMeta(R.string.fundamentals_delta_field_capex_to_ocf_pct, DeltaFieldFormat.PERCENT),
    "beta" to DeltaFieldMeta(R.string.fundamentals_delta_field_beta, DeltaFieldFormat.RATIO),
    "debt_to_equity" to DeltaFieldMeta(R.string.fundamentals_delta_field_debt_to_equity, DeltaFieldFormat.RATIO),
    "current_ratio" to DeltaFieldMeta(R.string.fundamentals_delta_field_current_ratio, DeltaFieldFormat.RATIO),
    "recommendation_mean" to DeltaFieldMeta(R.string.fundamentals_delta_field_recommendation_mean, DeltaFieldFormat.RATIO),
    "short_pct_float" to DeltaFieldMeta(R.string.fundamentals_delta_field_short_pct_float, DeltaFieldFormat.PERCENT),
    "short_ratio" to DeltaFieldMeta(R.string.fundamentals_delta_field_short_ratio, DeltaFieldFormat.RATIO),
    "target_mean" to DeltaFieldMeta(R.string.fundamentals_delta_field_target_mean, DeltaFieldFormat.DOLLAR),
    "target_high" to DeltaFieldMeta(R.string.fundamentals_delta_field_target_high, DeltaFieldFormat.DOLLAR),
    "target_low" to DeltaFieldMeta(R.string.fundamentals_delta_field_target_low, DeltaFieldFormat.DOLLAR),
    "forward_eps" to DeltaFieldMeta(R.string.fundamentals_delta_field_forward_eps, DeltaFieldFormat.DOLLAR),
    "trailing_eps" to DeltaFieldMeta(R.string.fundamentals_delta_field_trailing_eps, DeltaFieldFormat.DOLLAR)
)

private fun formatDeltaValue(value: Double, format: DeltaFieldFormat): String {
    val decimal = String.format(Locale.US, "%.2f", value)
    return when (format) {
        DeltaFieldFormat.PERCENT -> "$decimal%"
        DeltaFieldFormat.DOLLAR -> "$$decimal"
        DeltaFieldFormat.RATIO -> decimal
    }
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

private val mockDeltas = listOf(
    DomainFundamentalsDelta(field = "target_mean", from = 327.0, to = 328.0),
    DomainFundamentalsDelta(field = "pe_forward", from = 25.64, to = 24.75)
)

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewFundamentalsDeltaChipsLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        FundamentalsDeltaChips(deltas = mockDeltas)
    }
}

@Preview(name = "Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewFundamentalsDeltaChipsDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        FundamentalsDeltaChips(deltas = mockDeltas)
    }
}
