package com.marketlabs.pulse.ui.screens.stocks.detail.sections

// Generated by Claude Code.

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.ui.components.widgets.ChangeDirection
import com.marketlabs.pulse.ui.components.widgets.DirectionalChangePill
import com.marketlabs.pulse.ui.components.widgets.FavoriteStarToggle
import com.marketlabs.pulse.ui.components.widgets.GlossaryTapChevron
import com.marketlabs.pulse.ui.components.widgets.SignalPill
import com.marketlabs.pulse.ui.components.widgets.animateFlashColor
import com.marketlabs.pulse.ui.screens.stocks.detail.OutlinedBadge
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme
import com.marketlabs.pulse.utils.extensions.toAnalyzedAsOfString
import com.marketlabs.pulse.utils.extensions.toShortDateString
import java.util.Locale
import kotlin.math.abs

/**
 * The Detail screen's pinned header -- per the spec this stays fixed while everything below it
 * (SetupReasoning through NotCoveredFooter) scrolls underneath, so `StockDetailRoute` renders this
 * outside the scrollable container rather than as its first `LazyColumn` item. Not a Material
 * `TopAppBar` -- the row of symbol/price/badges is too rich for that slot, so this suppresses the
 * global collapsing top bar (`MainActivity`'s `hasOwnTopBar`) and stands in for it entirely.
 *
 * `technicalSetup` and `regimeAtAnalysis` get deliberately different pill treatments, matching the
 * Design mockup: `technicalSetup` (a classification, not a signal) is an outlined/unfilled pill in
 * a muted tone, while `regimeAtAnalysis` (the market-wide backdrop this analysis was run against)
 * is a filled accent pill -- neither is a `signal.*` color, since neither is a bullish/bearish
 * read on its own.
 *
 * `price`/`changePercent` come from the same `market_stocks/{symbol}` doc the analysis lives on --
 * `intradayPoller` overwrites just those two fields on it every 5 minutes during regular market
 * hours, so this is a live quote during the session, tagged with the small "LIVE" label above it
 * (gated on `isEquityOpen`, the same `market_overview/market_state.is_equity_open` flag the
 * Dashboard's own hero card badge reads, so it can't drift from what the app calls "open" anywhere
 * else) -- not something frozen at the last analysis run. That means the big number up top and the analysis
 * below it can legitimately be reasoning about two different prices -- `previousClose` is what
 * closes that gap: it's written once per day at EOD from that same day's own last live tick
 * (`timeline.ts`'s `previous_close: prevPreview.price`) and `intradayPoller` never touches it, so it
 * stays pinned to the close the still-current analysis was actually generated against for the
 * entire next session, even while `price` drifts away from it live. Spelled out below "Analyzed as
 * of" with `analysisDate` so a mid-day viewer sees explicitly which price the write-up used.
 *
 * 2026-09-06: both badges are tap-to-explain, matching the same "tap a signal, see what it means"
 * bottom sheet Market Signal and other Summary cards use -- `onTechnicalSetupClick`/`onRegimeClick`
 * are wired by `StockDetailRoute` to open `MarketGlossaryBottomSheet` with `currentStockSetup`/
 * `currentDirection` respectively. `technicalSetup`'s 6 values (BREAKDOWN/BREAKOUT/ACCUMULATION/
 * DISTRIBUTION/MEAN_REVERSION/RANGE_BOUND) are a per-stock chart-pattern read with no overlap with
 * Summary's own `setups` glossary (a market-wide RSI/momentum-extreme read that just happens to
 * share the word "setup") -- see `market_glossary.json`'s new `stock_setups` section, backed by
 * the backend's actual trigger logic, not guessed. `regimeAtAnalysis` (`risk_on`/`risk_off`/
 * `neutral`) is confirmed (backend-side) to be the *same* underlying `system/market_regime` token
 * Summary's `direction` field reads, just kept in its raw snake_case form here -- reuses that
 * existing `directions` glossary section rather than adding a duplicate one.
 */
@Composable
fun DetailHeader(
    symbol: String,
    name: String?,
    assetType: String?,
    price: Double?,
    changePercent: Double?,
    previousClose: Double?,
    analysisDate: String?,
    isEquityOpen: Boolean,
    technicalSetup: String?,
    regimeAtAnalysis: String?,
    analyzedAsOfTimestamp: Long?,
    isFavorite: Boolean,
    onNavigateUp: () -> Unit,
    onFavoriteClick: () -> Unit,
    onTechnicalSetupClick: () -> Unit = {},
    onRegimeClick: () -> Unit = {},
    modifier: Modifier = Modifier
) {
    val pulseColors = LocalPulseColors.current

    Column(
        modifier = modifier
            .fillMaxWidth()
            .background(MaterialTheme.colorScheme.background)
            .padding(dimensionResource(id = R.dimen.padding_large))
    ) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Row(
                verticalAlignment = Alignment.CenterVertically,
                modifier = Modifier.clickable(onClick = onNavigateUp)
            ) {
                Icon(
                    painter = painterResource(id = R.drawable.ic_back),
                    contentDescription = stringResource(id = R.string.nav_back_content_description),
                    tint = pulseColors.onSurfaceMuted
                )
                Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_small)))
                Text(
                    text = stringResource(id = R.string.stock_detail_back_label),
                    style = MaterialTheme.typography.labelMedium,
                    color = pulseColors.onSurfaceMuted
                )
            }
            // 💡 Sibling of the back row, not inside its `clickable` -- a plain append would have
            // made tapping the star also trigger back-navigation.
            FavoriteStarToggle(
                isFavorite = isFavorite,
                onClick = onFavoriteClick,
                contentDescription = stringResource(
                    id = if (isFavorite) R.string.stock_analysis_remove_favorite_content_description
                    else R.string.stock_analysis_add_favorite_content_description,
                    symbol
                )
            )
        }

        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Column(modifier = Modifier.weight(1f)) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Text(
                        text = symbol,
                        style = MaterialTheme.typography.headlineMedium.copy(fontWeight = FontWeight.Bold),
                        color = MaterialTheme.colorScheme.onSurface
                    )
                    // 💡 Same disclosure badge `StockPreviewCard` shows next to the symbol -- flags
                    // a symbol that isn't a single-company stock (SPY as an ETF, ^GSPC as an index,
                    // ...). Omitted for "STOCK" (the majority) and for a null/missing value.
                    assetType?.takeIf { it != "STOCK" }?.let {
                        Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_small)))
                        OutlinedBadge(text = it)
                    }
                }
                name?.let {
                    Text(
                        text = it,
                        style = MaterialTheme.typography.bodyMedium,
                        color = pulseColors.accentPrimary,
                        maxLines = 1,
                        overflow = TextOverflow.Ellipsis
                    )
                }
            }

            // 💡 Hoisted above both the price text and the pill below (was computed inline only
            // for the pill) -- the price text's refresh-flash reuses the same bullish/bearish/
            // neutral read so the two never disagree.
            val direction = when {
                (changePercent ?: 0.0) > 0 -> ChangeDirection.UP
                (changePercent ?: 0.0) < 0 -> ChangeDirection.DOWN
                else -> ChangeDirection.FLAT
            }
            val (pillColor, textColor) = when (direction) {
                ChangeDirection.UP -> pulseColors.signalBullishPill to pulseColors.signalBullishText
                ChangeDirection.DOWN -> pulseColors.signalBearishPill to pulseColors.signalBearishText
                ChangeDirection.FLAT -> pulseColors.signalNeutralPill to pulseColors.signalNeutralText
            }

            Column(horizontalAlignment = Alignment.End) {
                price?.let {
                    if (isEquityOpen) {
                        Text(
                            text = stringResource(id = R.string.stock_price_live_label),
                            style = MaterialTheme.typography.labelSmall,
                            color = pulseColors.onSurfaceMuted
                        )
                    }
                    Text(
                        text = "$${String.format(Locale.US, "%.2f", it)}",
                        style = MaterialTheme.typography.headlineMedium.copy(fontWeight = FontWeight.Bold),
                        color = animateFlashColor(
                            value = it,
                            flashColor = textColor,
                            restingColor = MaterialTheme.colorScheme.onSurface
                        )
                    )
                }
                changePercent?.let { changeValue ->
                    Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
                    DirectionalChangePill(
                        changeText = "${String.format(Locale.US, "%.2f", abs(changeValue))}%",
                        direction = direction,
                        pillColor = pillColor,
                        contentColor = textColor
                    )
                }
            }
        }

        if (technicalSetup != null || regimeAtAnalysis != null) {
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_medium)))
            Row(horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_small))) {
                technicalSetup?.let {
                    OutlinedBadge(text = it.replace('_', ' ').uppercase(Locale.US), onClick = onTechnicalSetupClick)
                }
                regimeAtAnalysis?.let {
                    val label = stringResource(
                        id = R.string.stock_detail_regime_suffix,
                        it.replace('_', '-').uppercase(Locale.US)
                    )
                    SignalPill(
                        text = label,
                        pillColor = pulseColors.accentSurface,
                        contentColor = pulseColors.accentPrimary,
                        trailingIcon = { GlossaryTapChevron(tint = pulseColors.accentPrimary) },
                        onClick = onRegimeClick
                    )
                }
            }
        }

        analyzedAsOfTimestamp?.let {
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_medium)))
            Text(
                text = stringResource(id = R.string.analyzed_at, it.toAnalyzedAsOfString()),
                style = MaterialTheme.typography.labelSmall,
                color = pulseColors.onSurfaceMuted
            )
        }

        if (previousClose != null && analysisDate != null) {
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
            Text(
                text = stringResource(
                    id = R.string.stock_analysis_close_caption,
                    String.format(Locale.US, "%.2f", previousClose),
                    analysisDate.toShortDateString()
                ),
                style = MaterialTheme.typography.labelSmall,
                color = pulseColors.accentPrimary
            )
        }
    }
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewDetailHeaderLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        DetailHeader(
            symbol = "AMZN",
            name = "Amazon.com, Inc.",
            assetType = "STOCK",
            price = 274.48,
            changePercent = 0.82,
            previousClose = 269.10,
            analysisDate = "2026-09-11",
            isEquityOpen = true,
            technicalSetup = "MEAN_REVERSION",
            regimeAtAnalysis = "risk_on",
            analyzedAsOfTimestamp = System.currentTimeMillis(),
            isFavorite = false,
            onNavigateUp = {},
            onFavoriteClick = {}
        )
    }
}

@Preview(name = "Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewDetailHeaderDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        DetailHeader(
            symbol = "AMZN",
            name = "Amazon.com, Inc.",
            assetType = "STOCK",
            price = 274.48,
            changePercent = 0.82,
            previousClose = 269.10,
            analysisDate = "2026-09-11",
            isEquityOpen = true,
            technicalSetup = "MEAN_REVERSION",
            regimeAtAnalysis = "risk_on",
            analyzedAsOfTimestamp = System.currentTimeMillis(),
            isFavorite = true,
            onNavigateUp = {},
            onFavoriteClick = {}
        )
    }
}

@Preview(name = "ETF disclosure badge", showBackground = true)
@Composable
private fun PreviewDetailHeaderEtf() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        DetailHeader(
            symbol = "SPY",
            name = "SPDR S&P 500 ETF Trust",
            assetType = "ETF",
            price = 574.20,
            changePercent = -0.31,
            previousClose = 576.00,
            analysisDate = "2026-09-11",
            isEquityOpen = true,
            technicalSetup = null,
            regimeAtAnalysis = "risk_on",
            analyzedAsOfTimestamp = System.currentTimeMillis(),
            isFavorite = false,
            onNavigateUp = {},
            onFavoriteClick = {}
        )
    }
}
