package com.marketlabs.pulse.ui.screens.stocks.detail.sections

// Generated by Claude Code.

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.ui.components.widgets.ChangeDirection
import com.marketlabs.pulse.ui.components.widgets.DirectionalChangePill
import com.marketlabs.pulse.ui.components.widgets.SignalPill
import com.marketlabs.pulse.ui.screens.stocks.detail.OutlinedBadge
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme
import com.marketlabs.pulse.utils.extensions.toAnalyzedAsOfString
import java.util.Locale
import kotlin.math.abs

/**
 * The Detail screen's pinned header -- per the spec this stays fixed while everything below it
 * (SetupReasoning through NotCoveredFooter) scrolls underneath, so `StockDetailRoute` renders this
 * outside the scrollable container rather than as its first `LazyColumn` item. Not a Material
 * `TopAppBar` -- the row of symbol/price/badges is too rich for that slot, so this suppresses the
 * global collapsing top bar (`MainActivity`'s `hasOwnTopBar`) and stands in for it entirely.
 *
 * `technicalSetup` and `regimeAtAnalysis` get deliberately different pill treatments, matching the
 * Design mockup: `technicalSetup` (a classification, not a signal) is an outlined/unfilled pill in
 * a muted tone, while `regimeAtAnalysis` (the market-wide backdrop this analysis was run against)
 * is a filled accent pill -- neither is a `signal.*` color, since neither is a bullish/bearish
 * read on its own.
 */
@Composable
fun DetailHeader(
    symbol: String,
    name: String?,
    price: Double?,
    changePercent: Double?,
    technicalSetup: String?,
    regimeAtAnalysis: String?,
    analyzedAsOfTimestamp: Long?,
    onNavigateUp: () -> Unit,
    modifier: Modifier = Modifier
) {
    val pulseColors = LocalPulseColors.current

    Column(
        modifier = modifier
            .fillMaxWidth()
            .background(MaterialTheme.colorScheme.background)
            .padding(dimensionResource(id = R.dimen.padding_large))
    ) {
        Row(
            verticalAlignment = Alignment.CenterVertically,
            modifier = Modifier.clickable(onClick = onNavigateUp)
        ) {
            Icon(
                painter = painterResource(id = R.drawable.ic_back),
                contentDescription = stringResource(id = R.string.nav_back_content_description),
                tint = pulseColors.onSurfaceMuted
            )
            Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_small)))
            Text(
                text = stringResource(id = R.string.stock_detail_back_label),
                style = MaterialTheme.typography.labelMedium,
                color = pulseColors.onSurfaceMuted
            )
        }

        Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_large)))

        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween
        ) {
            Column(modifier = Modifier.weight(1f)) {
                Text(
                    text = symbol,
                    style = MaterialTheme.typography.headlineMedium.copy(fontWeight = FontWeight.Bold),
                    color = MaterialTheme.colorScheme.onSurface
                )
                name?.let {
                    Text(
                        text = it,
                        style = MaterialTheme.typography.bodyMedium,
                        color = pulseColors.onSurfaceMuted,
                        maxLines = 1,
                        overflow = TextOverflow.Ellipsis
                    )
                }
            }

            Column(horizontalAlignment = Alignment.End) {
                price?.let {
                    Text(
                        text = "$${String.format(Locale.US, "%.2f", it)}",
                        style = MaterialTheme.typography.headlineMedium.copy(fontWeight = FontWeight.Bold),
                        color = MaterialTheme.colorScheme.onSurface
                    )
                }
                changePercent?.let { changeValue ->
                    Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
                    val direction = when {
                        changeValue > 0 -> ChangeDirection.UP
                        changeValue < 0 -> ChangeDirection.DOWN
                        else -> ChangeDirection.FLAT
                    }
                    val (pillColor, textColor) = when (direction) {
                        ChangeDirection.UP -> pulseColors.signalBullishPill to pulseColors.signalBullishText
                        ChangeDirection.DOWN -> pulseColors.signalBearishPill to pulseColors.signalBearishText
                        ChangeDirection.FLAT -> pulseColors.signalNeutralPill to pulseColors.signalNeutralText
                    }
                    DirectionalChangePill(
                        changeText = "${String.format(Locale.US, "%.2f", abs(changeValue))}%",
                        direction = direction,
                        pillColor = pillColor,
                        contentColor = textColor
                    )
                }
            }
        }

        if (technicalSetup != null || regimeAtAnalysis != null) {
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_medium)))
            Row(horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_small))) {
                technicalSetup?.let {
                    OutlinedBadge(text = it.replace('_', ' ').uppercase(Locale.US))
                }
                regimeAtAnalysis?.let {
                    val label = stringResource(
                        id = R.string.stock_detail_regime_suffix,
                        it.replace('_', '-').uppercase(Locale.US)
                    )
                    SignalPill(text = label, pillColor = pulseColors.accentSurface, contentColor = pulseColors.accentPrimary)
                }
            }
        }

        analyzedAsOfTimestamp?.let {
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_medium)))
            Text(
                text = stringResource(id = R.string.analyzed_at, it.toAnalyzedAsOfString()),
                style = MaterialTheme.typography.labelSmall,
                color = pulseColors.onSurfaceMuted
            )
        }
    }
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewDetailHeaderLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        DetailHeader(
            symbol = "AMZN",
            name = "Amazon.com, Inc.",
            price = 274.48,
            changePercent = 0.82,
            technicalSetup = "MEAN_REVERSION",
            regimeAtAnalysis = "risk_on",
            analyzedAsOfTimestamp = System.currentTimeMillis(),
            onNavigateUp = {}
        )
    }
}

@Preview(name = "Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewDetailHeaderDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        DetailHeader(
            symbol = "AMZN",
            name = "Amazon.com, Inc.",
            price = 274.48,
            changePercent = 0.82,
            technicalSetup = "MEAN_REVERSION",
            regimeAtAnalysis = "risk_on",
            analyzedAsOfTimestamp = System.currentTimeMillis(),
            onNavigateUp = {}
        )
    }
}
