package com.marketlabs.pulse.ui.screens.stocks.detail.sections

// Generated by Claude Code.

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.stocks.DomainDigestSection
import com.marketlabs.pulse.ui.components.PulseCard
import com.marketlabs.pulse.ui.components.PulseCardStyle
import com.marketlabs.pulse.ui.components.widgets.CardEyebrowLabel
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme
import com.marketlabs.pulse.utils.extensions.smartTitleCase

/**
 * ONE `PulseCard(SYNTHESIS)` for the whole Digest tab (unlike Deep Dive, which is multiple cards)
 * -- a small-caps "DAILY DIGEST" header, the headline, then each section's own (model-written, no
 * fixed topic) `heading` rendered small-caps in place of a separate kicker, followed by its body.
 * Consecutive blocks (headline, then each section) are separated by a divider spanning the full
 * card width. At least one of `headline`/`sections` is always non-null when this is called --
 * `StockDetailScreen.DigestTabContent` gates on that before rendering this at all.
 */
@Composable
fun DigestCard(headline: String?, sections: List<DomainDigestSection>, modifier: Modifier = Modifier) {
    val pulseColors = LocalPulseColors.current

    PulseCard(style = PulseCardStyle.SYNTHESIS, modifier = modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            // 💡 `CardEyebrowLabel`, not `SynthesisCardHeader` -- Digest is an "ai style card" in
            // the app-wide sense (Market Signal/Market Sentiment/Today's Read/Insights' Digest),
            // not Stock Detail's own screen-local `SynthesisCardHeader` family (TechnicalRead/
            // DeepStudy/Scenarios). No `iconRes` -- every card on the Stock Detail screen mixes
            // quant data and AI narrative, so the AI-sparkle glyph singling this one out as "the AI
            // card" is misleading here (unlike Today's Read/Insights' Digest, which carry it).
            CardEyebrowLabel(
                text = stringResource(id = R.string.stock_detail_digest_header),
                color = pulseColors.accentPrimary
            )

            val blocks: List<@Composable () -> Unit> = buildList {
                headline?.let { text ->
                    add {
                        Text(
                            text = text.smartTitleCase(),
                            style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
                            color = MaterialTheme.colorScheme.onSurface
                        )
                    }
                }
                sections.forEach { section ->
                    add {
                        Column {
                            // 💡 accentPrimary, matching the card's own "DAILY DIGEST" eyebrow above
                            // -- was onSurfaceMuted, which read as a different, disconnected label
                            // family from the header it sits under.
                            Text(
                                text = section.heading.orEmpty().uppercase(),
                                style = MaterialTheme.typography.labelMedium.copy(fontWeight = FontWeight.Bold),
                                color = pulseColors.accentPrimary
                            )
                            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
                            Text(
                                text = section.body.orEmpty(),
                                style = MaterialTheme.typography.bodyMedium,
                                color = MaterialTheme.colorScheme.onSurface
                            )
                        }
                    }
                }
            }

            blocks.forEachIndexed { index, block ->
                // 💡 Header -> first block is `padding_medium` (the header-to-content gap every
                // other SYNTHESIS card uses); `padding_large` for every later block is
                // block-to-block separation around the divider below, a different gap.
                val gapAbove = if (index == 0) R.dimen.padding_medium else R.dimen.padding_large
                Spacer(modifier = Modifier.height(dimensionResource(id = gapAbove)))
                block()
                if (index != blocks.lastIndex) {
                    Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_large)))
                    HorizontalDivider(
                        color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.1f),
                        thickness = dimensionResource(id = R.dimen.border_thin)
                    )
                }
            }
        }
    }
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

private val mockSections = listOf(
    DomainDigestSection(
        heading = "Regulatory Pressure Mounts",
        body = "The Department of Justice expanded its antitrust inquiry into rising beef prices, demanding information from Amazon and other major retailers."
    )
)

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewDigestCardLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        DigestCard(headline = "Amazon falls 2% amid DOJ beef-pricing antitrust probe", sections = mockSections)
    }
}

@Preview(name = "Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewDigestCardDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        DigestCard(headline = "Amazon falls 2% amid DOJ beef-pricing antitrust probe", sections = mockSections)
    }
}
