package com.marketlabs.pulse.ui.screens.stocks.detail.sections

// Generated by Claude Code.

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.relocation.BringIntoViewRequester
import androidx.compose.foundation.relocation.bringIntoViewRequester
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.stocks.DomainCallRecord
import com.marketlabs.pulse.storage.model.stocks.DomainForwardCall
import com.marketlabs.pulse.ui.components.widgets.SignalPill
import com.marketlabs.pulse.ui.screens.stocks.detail.SectionDividerLabel
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme
import com.marketlabs.pulse.utils.extensions.toLongDateString
import kotlinx.coroutines.launch
import java.util.Locale

/**
 * `calls.open[]` and `calls.resolved[]` -- both reuse the same `DomainForwardCall` type (resolved
 * entries additionally populate `resolved_on`/`resolved_price`/`outcome_note`/`status`). Header
 * line combines `calls.stats.held`/`total_resolved`/`hit_rate_pct`/`failed`. `predicate` is a
 * confirmed fixed 5-value backend enum (`CLOSE_ABOVE` / `CLOSE_BELOW` / `HOLDS_ABOVE` /
 * `HOLDS_BELOW` / `STAYS_WITHIN`) -- the backend doesn't tag a bullish/bearish direction on it
 * directly, so the pill color here is derived from the ABOVE/BELOW/WITHIN keyword itself (a call
 * that price stays above a level reads bullish, below reads bearish, within is non-directional).
 *
 * Resolved calls stay collapsed to just a tappable header until expanded -- unlike Open calls,
 * they're historical record rather than something needing attention, so nothing renders until the
 * user asks for it. `BringIntoViewRequester` on the header handles collapsing a long expanded list
 * back down (same fix `EventLog.kt` uses for its own collapse, see that file's doc comment for why
 * it's anchored to the header specifically and not the whole section).
 */
@Composable
fun ForwardCalls(calls: DomainCallRecord?, modifier: Modifier = Modifier) {
    val open = calls?.open.orEmpty()
    val resolved = calls?.resolved.orEmpty()
    if (open.isEmpty() && resolved.isEmpty()) return

    Column(modifier = modifier.fillMaxWidth()) {
        if (open.isNotEmpty()) {
            val stats = calls?.stats
            val trailing = if (stats?.held != null && stats.totalResolved != null) {
                buildString {
                    append(stringResource(id = R.string.stock_detail_calls_held_of_total, stats.held, stats.totalResolved))
                    // 💡 The space before each suffix is added here, not baked into the XML string
                    // resource -- Android's resource compiler trims leading whitespace from string
                    // values, which would silently collapse "held (100%)" into "held(100%)".
                    stats.hitRatePct?.let { append(" ").append(stringResource(id = R.string.stock_detail_calls_hit_rate_suffix, it)) }
                    stats.failed?.takeIf { it > 0 }?.let { append(stringResource(id = R.string.stock_detail_calls_failed_suffix, it)) }
                }
            } else null
            SectionDividerLabel(title = stringResource(id = R.string.stock_detail_forward_calls_title), trailing = trailing)
            Spacer()

            Column(verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_medium))) {
                open.forEach { call -> ForwardCallCard(call) }
            }
        }

        if (resolved.isNotEmpty()) {
            if (open.isNotEmpty()) {
                androidx.compose.foundation.layout.Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_xxlarge)))
            }
            ResolvedCallsSection(resolved = resolved)
        }
    }
}

@Composable
private fun ResolvedCallsSection(resolved: List<DomainForwardCall>) {
    var expanded by remember { mutableStateOf(false) }
    val bringIntoViewRequester = remember { BringIntoViewRequester() }
    val coroutineScope = rememberCoroutineScope()
    val pulseColors = LocalPulseColors.current

    Column {
        Row(
            verticalAlignment = Alignment.CenterVertically,
            modifier = Modifier
                .fillMaxWidth()
                .bringIntoViewRequester(bringIntoViewRequester)
                .clickable {
                    val wasExpanded = expanded
                    expanded = !expanded
                    if (wasExpanded) {
                        coroutineScope.launch { bringIntoViewRequester.bringIntoView() }
                    }
                }
        ) {
            Box(modifier = Modifier.weight(1f, fill = false)) {
                SectionDividerLabel(title = stringResource(id = R.string.stock_detail_resolved_calls_title))
            }
            Icon(
                painter = painterResource(id = if (expanded) R.drawable.ic_arrow_up else R.drawable.ic_arrow_down),
                contentDescription = null,
                tint = pulseColors.accentPrimary,
                modifier = Modifier.size(dimensionResource(id = R.dimen.icon_size_small))
            )
        }

        if (expanded) {
            Spacer()
            Column(verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_medium))) {
                resolved.forEach { call -> ResolvedCallCard(call) }
            }
        }
    }
}

@Composable
private fun ResolvedCallCard(call: DomainForwardCall) {
    val pulseColors = LocalPulseColors.current
    val (predicateLabel, predicateColor, predicatePillColor) = predicateStyle(call, pulseColors)
    val (statusLabel, statusColor, statusPillColor) = resolvedStatusStyle(call.status, pulseColors)

    // 💡 fillMaxWidth -- was sizing to its own content instead of the full card width, unlike
    // every other card on this screen.
    Surface(
        color = pulseColors.surfaceTinted,
        shape = RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_small)),
        modifier = Modifier.fillMaxWidth()
    ) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            if (predicateLabel != null || statusLabel != null) {
                androidx.compose.foundation.layout.Row(
                    horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_small))
                ) {
                    predicateLabel?.let { SignalPill(text = it, pillColor = predicatePillColor, contentColor = predicateColor) }
                    statusLabel?.let { SignalPill(text = it, pillColor = statusPillColor, contentColor = statusColor) }
                }
                Spacer()
            }

            (call.outcomeNote ?: call.statement)?.let {
                Text(text = it, style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onSurface)
            }

            if (call.resolvedOn != null) {
                Spacer()
                val resolvedLine = if (call.resolvedPrice != null) {
                    stringResource(id = R.string.stock_detail_call_resolved_on_at, call.resolvedOn.toLongDateString(), formatPrice(call.resolvedPrice))
                } else {
                    stringResource(id = R.string.stock_detail_call_resolved_on, call.resolvedOn.toLongDateString())
                }
                Text(text = resolvedLine, style = MaterialTheme.typography.labelSmall, color = pulseColors.onSurfaceMuted)
            }
        }
    }
}

/** HELD reads bullish (the call played out), FAILED reads bearish -- null/unrecognized status renders no pill. */
@Composable
private fun resolvedStatusStyle(status: String?, pulseColors: com.marketlabs.pulse.ui.theme.PulseColors): Triple<String?, Color, Color> =
    when (status?.uppercase(Locale.US)) {
        "HELD" -> Triple(stringResource(id = R.string.stock_detail_call_status_held), pulseColors.signalBullishText, pulseColors.signalBullishPill)
        "FAILED" -> Triple(stringResource(id = R.string.stock_detail_call_status_failed), pulseColors.signalBearishText, pulseColors.signalBearishPill)
        else -> Triple(null, Color.Unspecified, Color.Unspecified)
    }

@Composable
private fun ForwardCallCard(call: DomainForwardCall) {
    val pulseColors = LocalPulseColors.current
    val (predicateLabel, predicateColor, pillColor) = predicateStyle(call, pulseColors)

    // 💡 fillMaxWidth -- was sizing to its own content instead of the full card width, same fix
    // as `ResolvedCallCard` below.
    Surface(
        color = pulseColors.surfaceTinted,
        shape = RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_small)),
        modifier = Modifier.fillMaxWidth()
    ) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            if (predicateLabel != null) {
                Surface(color = pillColor, shape = RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_pill))) {
                    Text(
                        text = predicateLabel,
                        style = MaterialTheme.typography.labelMedium.copy(fontWeight = FontWeight.Bold),
                        color = predicateColor,
                        modifier = Modifier.padding(
                            horizontal = dimensionResource(id = R.dimen.padding_medium),
                            vertical = dimensionResource(id = R.dimen.padding_small)
                        )
                    )
                }
                Spacer()
            }

            call.statement?.let {
                Text(text = it, style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onSurface)
            }

            if (call.madeOn != null && call.resolveDate != null) {
                Spacer()
                Text(
                    text = stringResource(
                        id = R.string.stock_detail_call_made_resolves,
                        call.madeOn.toLongDateString(),
                        call.resolveDate.toLongDateString()
                    ),
                    style = MaterialTheme.typography.labelSmall,
                    color = pulseColors.onSurfaceMuted
                )
            }
        }
    }
}

/** Returns (humanized predicate + level label, pill text color, pill background color), or a null label if `predicate`/`level` is missing. */
@Composable
private fun predicateStyle(call: DomainForwardCall, pulseColors: com.marketlabs.pulse.ui.theme.PulseColors): Triple<String?, Color, Color> {
    val level = call.level ?: return Triple(null, Color.Unspecified, Color.Unspecified)

    return when (call.predicate?.uppercase(Locale.US)) {
        "CLOSE_ABOVE" -> Triple(
            "${stringResource(id = R.string.stock_detail_predicate_close_above)} $${formatPrice(level)}",
            pulseColors.signalBullishText, pulseColors.signalBullishPill
        )
        "HOLDS_ABOVE" -> Triple(
            "${stringResource(id = R.string.stock_detail_predicate_holds_above)} $${formatPrice(level)}",
            pulseColors.signalBullishText, pulseColors.signalBullishPill
        )
        "CLOSE_BELOW" -> Triple(
            "${stringResource(id = R.string.stock_detail_predicate_close_below)} $${formatPrice(level)}",
            pulseColors.signalBearishText, pulseColors.signalBearishPill
        )
        "HOLDS_BELOW" -> Triple(
            "${stringResource(id = R.string.stock_detail_predicate_holds_below)} $${formatPrice(level)}",
            pulseColors.signalBearishText, pulseColors.signalBearishPill
        )
        "STAYS_WITHIN" -> {
            val upper = call.levelUpper
            val range = if (upper != null) "$${formatPrice(level)}–$${formatPrice(upper)}" else "$${formatPrice(level)}"
            Triple(
                "${stringResource(id = R.string.stock_detail_predicate_stays_within)} $range",
                pulseColors.signalNeutralText, pulseColors.signalNeutralPill
            )
        }
        else -> Triple(null, Color.Unspecified, Color.Unspecified)
    }
}

private fun formatPrice(value: Double): String = String.format(Locale.US, "%.2f", value)

@Composable
private fun Spacer() {
    androidx.compose.foundation.layout.Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_medium)))
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

private val mockCalls = DomainCallRecord(
    open = listOf(
        DomainForwardCall(
            predicate = "HOLDS_ABOVE",
            level = 255.19,
            statement = "Amazon holds above support of \$255.19 over the next five sessions despite the current low-volume pullback.",
            madeOn = "2026-08-04",
            resolveDate = "2026-08-11"
        ),
        DomainForwardCall(
            predicate = "CLOSE_BELOW",
            level = 274.75,
            statement = "Amazon closes below resistance of \$274.75 over the next five sessions as buying volume continues to dry up.",
            madeOn = "2026-08-07",
            resolveDate = "2026-08-14"
        )
    ),
    resolved = listOf(
        DomainForwardCall(
            predicate = "CLOSE_BELOW",
            level = 234.66,
            statement = "Closes below its 200-day moving average of \$234.66 over the next five sessions as distribution pressure persists.",
            outcomeNote = "Closed below \$234.66 within the window.",
            madeOn = "2026-07-28",
            resolveDate = "2026-08-04",
            resolvedOn = "2026-08-04",
            resolvedPrice = 284.02,
            status = "HELD"
        ),
        DomainForwardCall(
            predicate = "CLOSE_ABOVE",
            level = 274.75,
            statement = "Closes above resistance of \$274.75 within the next five sessions as bullish momentum continues.",
            outcomeNote = "Closed above \$274.75 within the window.",
            madeOn = "2026-07-31",
            resolveDate = "2026-08-07",
            resolvedOn = "2026-08-07",
            resolvedPrice = 272.26,
            status = "HELD"
        )
    ),
    stats = com.marketlabs.pulse.storage.model.stocks.DomainCallStats(totalResolved = 2, held = 2, hitRatePct = 100)
)

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewForwardCallsLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        ForwardCalls(calls = mockCalls)
    }
}

@Preview(name = "Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewForwardCallsDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        ForwardCalls(calls = mockCalls)
    }
}
