package com.marketlabs.pulse.ui.screens.stocks.detail.sections

// Generated by Claude Code.

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.stocks.DomainCallRecord
import com.marketlabs.pulse.storage.model.stocks.DomainForwardCall
import com.marketlabs.pulse.ui.screens.stocks.detail.SectionDividerLabel
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme
import com.marketlabs.pulse.utils.extensions.toLongDateString
import java.util.Locale

/**
 * `calls.open[]`, header line from `calls.stats.held`/`total_resolved`. `predicate` is a confirmed
 * fixed 5-value backend enum (`CLOSE_ABOVE` / `CLOSE_BELOW` / `HOLDS_ABOVE` / `HOLDS_BELOW` /
 * `STAYS_WITHIN`) -- the backend doesn't tag a bullish/bearish direction on it directly, so the
 * pill color here is derived from the ABOVE/BELOW/WITHIN keyword itself (a call that price stays
 * above a level reads bullish, below reads bearish, within is non-directional).
 */
@Composable
fun ForwardCalls(calls: DomainCallRecord?, modifier: Modifier = Modifier) {
    val open = calls?.open.orEmpty()
    if (open.isEmpty()) return

    Column(modifier = modifier.fillMaxWidth()) {
        val stats = calls?.stats
        val trailing = if (stats?.held != null && stats.totalResolved != null) {
            stringResource(id = R.string.stock_detail_calls_held_of_total, stats.held, stats.totalResolved)
        } else null
        SectionDividerLabel(title = stringResource(id = R.string.stock_detail_forward_calls_title), trailing = trailing)
        Spacer()

        Column(verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_medium))) {
            open.forEach { call -> ForwardCallCard(call) }
        }
    }
}

@Composable
private fun ForwardCallCard(call: DomainForwardCall) {
    val pulseColors = LocalPulseColors.current
    val (predicateLabel, predicateColor, pillColor) = predicateStyle(call, pulseColors)

    Surface(color = pulseColors.surfaceTinted, shape = RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_small))) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            if (predicateLabel != null) {
                Surface(color = pillColor, shape = RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_pill))) {
                    Text(
                        text = predicateLabel,
                        style = MaterialTheme.typography.labelMedium.copy(fontWeight = FontWeight.Bold),
                        color = predicateColor,
                        modifier = Modifier.padding(
                            horizontal = dimensionResource(id = R.dimen.padding_medium),
                            vertical = dimensionResource(id = R.dimen.padding_small)
                        )
                    )
                }
                Spacer()
            }

            call.statement?.let {
                Text(text = it, style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onSurface)
            }

            if (call.madeOn != null && call.resolveDate != null) {
                Spacer()
                Text(
                    text = stringResource(
                        id = R.string.stock_detail_call_made_resolves,
                        call.madeOn.toLongDateString(),
                        call.resolveDate.toLongDateString()
                    ),
                    style = MaterialTheme.typography.labelSmall,
                    color = pulseColors.onSurfaceMuted
                )
            }
        }
    }
}

/** Returns (humanized predicate + level label, pill text color, pill background color), or a null label if `predicate`/`level` is missing. */
@Composable
private fun predicateStyle(call: DomainForwardCall, pulseColors: com.marketlabs.pulse.ui.theme.PulseColors): Triple<String?, Color, Color> {
    val level = call.level ?: return Triple(null, Color.Unspecified, Color.Unspecified)

    return when (call.predicate?.uppercase(Locale.US)) {
        "CLOSE_ABOVE" -> Triple(
            "${stringResource(id = R.string.stock_detail_predicate_close_above)} $${formatPrice(level)}",
            pulseColors.signalBullishText, pulseColors.signalBullishPill
        )
        "HOLDS_ABOVE" -> Triple(
            "${stringResource(id = R.string.stock_detail_predicate_holds_above)} $${formatPrice(level)}",
            pulseColors.signalBullishText, pulseColors.signalBullishPill
        )
        "CLOSE_BELOW" -> Triple(
            "${stringResource(id = R.string.stock_detail_predicate_close_below)} $${formatPrice(level)}",
            pulseColors.signalBearishText, pulseColors.signalBearishPill
        )
        "HOLDS_BELOW" -> Triple(
            "${stringResource(id = R.string.stock_detail_predicate_holds_below)} $${formatPrice(level)}",
            pulseColors.signalBearishText, pulseColors.signalBearishPill
        )
        "STAYS_WITHIN" -> {
            val upper = call.levelUpper
            val range = if (upper != null) "$${formatPrice(level)}–$${formatPrice(upper)}" else "$${formatPrice(level)}"
            Triple(
                "${stringResource(id = R.string.stock_detail_predicate_stays_within)} $range",
                pulseColors.signalNeutralText, pulseColors.signalNeutralPill
            )
        }
        else -> Triple(null, Color.Unspecified, Color.Unspecified)
    }
}

private fun formatPrice(value: Double): String = String.format(Locale.US, "%.2f", value)

@Composable
private fun Spacer() {
    androidx.compose.foundation.layout.Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_medium)))
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

private val mockCalls = DomainCallRecord(
    open = listOf(
        DomainForwardCall(
            predicate = "HOLDS_ABOVE",
            level = 255.19,
            statement = "Amazon holds above support of \$255.19 over the next five sessions despite the current low-volume pullback.",
            madeOn = "2026-08-04",
            resolveDate = "2026-08-11"
        ),
        DomainForwardCall(
            predicate = "CLOSE_BELOW",
            level = 274.75,
            statement = "Amazon closes below resistance of \$274.75 over the next five sessions as buying volume continues to dry up.",
            madeOn = "2026-08-07",
            resolveDate = "2026-08-14"
        )
    ),
    stats = com.marketlabs.pulse.storage.model.stocks.DomainCallStats(totalResolved = 2, held = 2)
)

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewForwardCallsLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        ForwardCalls(calls = mockCalls)
    }
}

@Preview(name = "Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewForwardCallsDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        ForwardCalls(calls = mockCalls)
    }
}
