package com.marketlabs.pulse.ui.screens.stocks.detail.sections

// Generated by Claude Code.

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.FlowRow
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.stocks.DomainFundamentals
import com.marketlabs.pulse.ui.components.PulseCard
import com.marketlabs.pulse.ui.components.PulseCardStyle
import com.marketlabs.pulse.ui.components.bottomSheet.GlossaryEntry
import com.marketlabs.pulse.ui.components.bottomSheet.StockAnalysisGlossaryBottomSheet
import com.marketlabs.pulse.ui.screens.stocks.detail.DataCardTitleWithInfo
import com.marketlabs.pulse.ui.screens.stocks.detail.SubClusterLabel
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme
import com.marketlabs.pulse.utils.extensions.toLongDateString
import java.util.Locale

/**
 * `PulseCard(DATA)` from `fundamentals` -- 4 clusters (Valuation, Profitability, Growth, Analyst
 * view). Stats within Valuation/Profitability/Growth render in a `FlowRow` (wrapping to a second
 * row on narrower widths) rather than hand-coded fixed rows-of-3 -- the Design mockup's exact
 * row breaks aren't a meaningful contract, just wherever 3 items happened to fit that viewport.
 * No value gets signal-colored here (unlike the mockup, which tints a couple of valuation figures)
 * -- there's no stated rule for which fundamentals warrant it and guessing one risks implying a
 * bullish/bearish read the data doesn't actually support, so every value stays plain `onSurface`.
 * `recommendationKey` is an unconstrained Yahoo passthrough (confirmed against the backend, not
 * a fixed enum), so its pill color is a best-effort `contains("BUY")`/`contains("SELL")` read
 * rather than an exhaustive switch.
 */
@Composable
fun Fundamentals(fundamentals: DomainFundamentals?, modifier: Modifier = Modifier) {
    if (fundamentals == null) return

    var showGlossary by remember { mutableStateOf(false) }
    val title = stringResource(id = R.string.stock_detail_fundamentals_title)

    val valuationStats = listOfNotNull(
        fundamentals.peTrailing?.let { stat(R.string.stock_detail_metric_trailing_pe, formatDecimal(it), "TRAILING_PE") },
        fundamentals.peForward?.let { stat(R.string.stock_detail_metric_forward_pe, formatDecimal(it), "FORWARD_PE") },
        fundamentals.peVsMedianPct?.let { stat(R.string.stock_detail_metric_pe_vs_5y_med, formatSignedPercent(it), "PE_VS_5Y_MED") },
        fundamentals.evEbitda?.let { stat(R.string.stock_detail_metric_ev_ebitda, formatDecimal(it), "EV_EBITDA") },
        fundamentals.pegRatio?.let { stat(R.string.stock_detail_metric_peg, formatDecimal(it), "PEG") },
        // 💡 New field -- only present for dividend-paying symbols, so this naturally disappears
        // for the (majority) non-dividend-paying stocks rather than needing its own null-state UI.
        fundamentals.dividendYieldPct?.let { stat(R.string.stock_detail_metric_dividend_yield, formatPercent(it), "DIVIDEND_YIELD") },
        // 💡 `pe_history_5y` as a lightweight min/max range rather than a sparkline -- a real chart
        // is a bigger lift consistent with the deferred main price chart (`ChartPlaceholder` in
        // `StockDetailScreen.kt`); this surfaces the data now without that scope.
        fundamentals.peHistory5y?.takeIf { it.isNotEmpty() }?.let {
            stat(R.string.stock_detail_metric_pe_5y_range, "$${formatDecimal(it.min())}–$${formatDecimal(it.max())}", "TRAILING_PE")
        }
    )
    val balanceSheetStats = listOfNotNull(
        fundamentals.marketCap?.let { stat(R.string.stock_detail_metric_market_cap, formatCompactCurrency(it), "MARKET_CAP") },
        fundamentals.beta?.let { stat(R.string.stock_detail_metric_beta, formatDecimal(it), "BETA") },
        fundamentals.debtToEquity?.let { stat(R.string.stock_detail_metric_debt_to_equity, formatDecimal(it), "DEBT_TO_EQUITY") },
        fundamentals.currentRatio?.let { stat(R.string.stock_detail_metric_current_ratio, formatDecimal(it), "CURRENT_RATIO") },
        fundamentals.priceToBook?.let { stat(R.string.stock_detail_metric_price_to_book, formatDecimal(it), "PRICE_TO_BOOK") },
        fundamentals.priceToSales?.let { stat(R.string.stock_detail_metric_price_to_sales, formatDecimal(it), "PRICE_TO_SALES") },
        fundamentals.evRevenue?.let { stat(R.string.stock_detail_metric_ev_revenue, formatDecimal(it), "EV_REVENUE") }
    )
    val profitabilityStats = listOfNotNull(
        fundamentals.roicPct?.let { stat(R.string.stock_detail_metric_roic, formatPercent(it), "ROIC") },
        fundamentals.roePct?.let { stat(R.string.stock_detail_metric_roe, formatPercent(it), "ROE") },
        fundamentals.grossMarginPct?.let { stat(R.string.stock_detail_metric_gross_margin, formatPercent(it), "GROSS_MARGIN") },
        fundamentals.operatingMarginPct?.let { stat(R.string.stock_detail_metric_op_margin, formatPercent(it), "OP_MARGIN") },
        fundamentals.fcfYieldPct?.let { stat(R.string.stock_detail_metric_fcf_yield, formatPercent(it), "FCF_YIELD") }
    )
    val growthStats = listOfNotNull(
        fundamentals.revenueGrowthYoyPct?.let { stat(R.string.stock_detail_metric_revenue_yoy, formatSignedPercent(it), "REVENUE_YOY") },
        fundamentals.epsGrowthYoyPct?.let { stat(R.string.stock_detail_metric_eps_yoy, formatSignedPercent(it), "EPS_YOY") }
    )
    val hasAnalystView = fundamentals.targetMean != null || fundamentals.recommendationKey != null ||
        fundamentals.analystCount != null || fundamentals.nextEarningsDate != null

    PulseCard(style = PulseCardStyle.DATA, modifier = modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            DataCardTitleWithInfo(title = title, onInfoClick = { showGlossary = true })
            Spacer()

            // 💡 A thin divider between clusters so Valuation/Profitability/Growth/Analyst View
            // read as 4 distinct groups instead of running together -- only inserted between two
            // clusters that both actually rendered, so an empty cluster (e.g. no growth data)
            // never leaves a stray divider next to nothing.
            var precededByCluster = false
            if (valuationStats.isNotEmpty()) {
                Cluster(title = stringResource(id = R.string.stock_detail_cluster_valuation), stats = valuationStats)
                precededByCluster = true
            }
            if (profitabilityStats.isNotEmpty()) {
                if (precededByCluster) ClusterDivider()
                Cluster(title = stringResource(id = R.string.stock_detail_cluster_profitability), stats = profitabilityStats)
                precededByCluster = true
            }
            if (growthStats.isNotEmpty()) {
                if (precededByCluster) ClusterDivider()
                Cluster(title = stringResource(id = R.string.stock_detail_cluster_growth), stats = growthStats)
                precededByCluster = true
            }
            if (balanceSheetStats.isNotEmpty()) {
                if (precededByCluster) ClusterDivider()
                Cluster(title = stringResource(id = R.string.stock_detail_cluster_balance_sheet), stats = balanceSheetStats)
                precededByCluster = true
            }
            if (hasAnalystView) {
                if (precededByCluster) ClusterDivider()
                AnalystView(fundamentals)
            }
        }
    }

    if (showGlossary) {
        val entries = (valuationStats + profitabilityStats + growthStats + balanceSheetStats)
            .map { GlossaryEntry(stringResource(id = it.labelRes), it.term) }
        StockAnalysisGlossaryBottomSheet(title = title, entries = entries, onDismiss = { showGlossary = false })
    }
}

private data class Stat(val labelRes: Int, val value: String, val term: String)
private fun stat(labelRes: Int, value: String, term: String) = Stat(labelRes, value, term)

@Composable
private fun Cluster(title: String, stats: List<Stat>) {
    if (stats.isEmpty()) return

    Column {
        SubClusterLabel(title = title)
        Spacer()
        FlowRow(
            horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_xlarge)),
            verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_medium))
        ) {
            stats.forEach { s ->
                Column(modifier = Modifier.width(dimensionResource(id = R.dimen.detail_stat_width))) {
                    Text(
                        text = s.value,
                        style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
                        color = MaterialTheme.colorScheme.onSurface
                    )
                    Text(
                        text = stringResource(id = s.labelRes),
                        style = MaterialTheme.typography.labelSmall,
                        color = LocalPulseColors.current.onSurfaceMuted
                    )
                }
            }
        }
        Spacer()
    }
}

@Composable
private fun AnalystView(fundamentals: DomainFundamentals) {
    val hasAny = fundamentals.targetMean != null || fundamentals.recommendationKey != null ||
        fundamentals.analystCount != null || fundamentals.nextEarningsDate != null
    if (!hasAny) return

    val pulseColors = LocalPulseColors.current

    Column {
        SubClusterLabel(title = stringResource(id = R.string.stock_detail_cluster_analyst_view))
        Spacer()

        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
            if (fundamentals.targetMean != null) {
                Column {
                    Text(
                        text = "$${formatDecimal(fundamentals.targetMean)}",
                        style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
                        color = MaterialTheme.colorScheme.onSurface
                    )
                    if (fundamentals.targetLow != null && fundamentals.targetHigh != null) {
                        Text(
                            text = stringResource(
                                id = R.string.stock_detail_mean_target_label,
                                formatWhole(fundamentals.targetLow),
                                formatWhole(fundamentals.targetHigh)
                            ),
                            style = MaterialTheme.typography.labelSmall,
                            color = pulseColors.onSurfaceMuted
                        )
                    }
                }
            }
            fundamentals.recommendationKey?.let { key ->
                val readable = key.replace('_', ' ').uppercase(Locale.US)
                val (pillColor, textColor) = when {
                    readable.contains("BUY") -> pulseColors.signalBullishPill to pulseColors.signalBullishText
                    readable.contains("SELL") -> pulseColors.signalBearishPill to pulseColors.signalBearishText
                    else -> pulseColors.signalNeutralPill to pulseColors.signalNeutralText
                }
                Surface(color = pillColor, shape = RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_pill))) {
                    Text(
                        text = readable,
                        style = MaterialTheme.typography.labelMedium.copy(fontWeight = FontWeight.Bold),
                        color = textColor,
                        modifier = Modifier.padding(
                            horizontal = dimensionResource(id = R.dimen.padding_medium),
                            vertical = dimensionResource(id = R.dimen.padding_small)
                        )
                    )
                }
            }
        }

        if (fundamentals.analystCount != null || fundamentals.nextEarningsDate != null) {
            Spacer()
            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                fundamentals.analystCount?.let {
                    Text(
                        text = stringResource(id = R.string.stock_detail_analysts_covering, it),
                        style = MaterialTheme.typography.bodySmall,
                        color = pulseColors.onSurfaceMuted
                    )
                }
                fundamentals.nextEarningsDate?.let {
                    Text(
                        text = stringResource(id = R.string.stock_detail_next_earnings, it.toLongDateString()),
                        style = MaterialTheme.typography.bodySmall,
                        color = pulseColors.onSurfaceMuted
                    )
                }
            }
        }
    }
}

private fun formatDecimal(value: Double): String = String.format(Locale.US, "%.2f", value)
private fun formatWhole(value: Double): String = String.format(Locale.US, "%.0f", value)
private fun formatPercent(value: Double): String = "${formatDecimal(value)}%"
private fun formatSignedPercent(value: Double): String = "${if (value >= 0) "+" else ""}${formatDecimal(value)}%"

/** `market_cap` arrives as a raw dollar figure (e.g. `2921415835648`) -- compacted to "$2.92T"/"$B"/"$M" rather than a long string of digits. */
private fun formatCompactCurrency(value: Double): String {
    val magnitude = kotlin.math.abs(value)
    return when {
        magnitude >= 1_000_000_000_000.0 -> "$${formatDecimal(value / 1_000_000_000_000.0)}T"
        magnitude >= 1_000_000_000.0 -> "$${formatDecimal(value / 1_000_000_000.0)}B"
        magnitude >= 1_000_000.0 -> "$${formatDecimal(value / 1_000_000.0)}M"
        else -> "$${formatDecimal(value)}"
    }
}

@Composable
private fun Spacer() {
    androidx.compose.foundation.layout.Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_medium)))
}

@Composable
private fun ClusterDivider() {
    HorizontalDivider(
        color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.1f),
        thickness = dimensionResource(id = R.dimen.border_thin)
    )
    Spacer()
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

private val mockFundamentals = DomainFundamentals(
    peTrailing = 21.83,
    peForward = 26.44,
    peVsMedianPct = -72.98,
    evEbitda = 17.93,
    pegRatio = 1.46,
    peHistory5y = listOf(80.8, 83.9, 54.93, 30.71, 598.17),
    dividendYieldPct = 1.42,
    marketCap = 2921415835648.0,
    beta = 1.46,
    debtToEquity = 0.4,
    currentRatio = 1.03,
    priceToBook = 6.61,
    priceToSales = 3.7663,
    evRevenue = 3.9,
    roicPct = 24.48,
    roePct = 30.56,
    grossMarginPct = 50.77,
    operatingMarginPct = 13.69,
    fcfYieldPct = 0.78,
    revenueGrowthYoyPct = 19.6,
    epsGrowthYoyPct = 242.3,
    targetMean = 321.95,
    targetLow = 207.0,
    targetHigh = 400.0,
    recommendationKey = "strong_buy",
    analystCount = 61,
    nextEarningsDate = "2026-10-29"
)

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewFundamentalsLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        Fundamentals(fundamentals = mockFundamentals)
    }
}

@Preview(name = "Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewFundamentalsDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        Fundamentals(fundamentals = mockFundamentals)
    }
}
