package com.marketlabs.pulse.ui.screens.stocks.detail.sections

// Generated by Claude Code.

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.stocks.DomainTechnicalIndicators
import com.marketlabs.pulse.ui.components.PulseCard
import com.marketlabs.pulse.ui.components.PulseCardStyle
import com.marketlabs.pulse.ui.components.bottomSheet.GlossaryEntry
import com.marketlabs.pulse.ui.components.bottomSheet.StockAnalysisGlossaryBottomSheet
import com.marketlabs.pulse.ui.screens.stocks.detail.DataCardTitleWithInfo
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme
import java.util.Locale

/**
 * The 5-stat row (ATR / DIST SMA200 / 52W RANGE / RSI / RVOL) from `technical_indicators` --
 * distinct from `StockPreview`'s own `headline_metrics` field, which backs the (unused-here)
 * preview card metrics. Now its own `PulseCard(DATA)`, same "title + one info icon opens a
 * bottom sheet for everything in the card" pattern Key Levels/Fundamentals/Macro use -- this used
 * to sit bare on the background with a tooltip per metric, but that was the only section left
 * without a grouping card once the others moved to the single-icon-per-card pattern. Renders
 * nothing if `indicators` is null.
 */
@Composable
fun HeadlineMetricsStrip(indicators: DomainTechnicalIndicators?, modifier: Modifier = Modifier) {
    if (indicators == null) return

    var showGlossary by remember { mutableStateOf(false) }
    val title = stringResource(id = R.string.stock_detail_headline_metrics_title)

    PulseCard(style = PulseCardStyle.DATA, modifier = modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            DataCardTitleWithInfo(title = title, onInfoClick = { showGlossary = true })
            androidx.compose.foundation.layout.Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_large)))

            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                indicators.atrPct?.let {
                    MetricStat(
                        value = "${String.format(Locale.US, "%.2f", it)}%",
                        label = stringResource(id = R.string.stock_detail_metric_atr)
                    )
                }
                indicators.distSma200Pct?.let {
                    val sign = if (it >= 0) "+" else ""
                    MetricStat(
                        value = "$sign${String.format(Locale.US, "%.2f", it)}%",
                        label = stringResource(id = R.string.stock_detail_metric_dist_sma200)
                    )
                }
                indicators.rangePosition52w?.let {
                    MetricStat(
                        value = "${String.format(Locale.US, "%.1f", it)}%",
                        label = stringResource(id = R.string.stock_detail_metric_52w_range)
                    )
                }
                indicators.rsi?.let {
                    MetricStat(
                        value = String.format(Locale.US, "%.1f", it),
                        label = stringResource(id = R.string.stock_detail_metric_rsi)
                    )
                }
                indicators.rvol?.let {
                    MetricStat(
                        value = "${String.format(Locale.US, "%.2f", it)}x",
                        label = stringResource(id = R.string.stock_detail_metric_rvol)
                    )
                }
            }
        }
    }

    if (showGlossary) {
        val entries = listOfNotNull(
            indicators.atrPct?.let { GlossaryEntry(stringResource(id = R.string.stock_detail_metric_atr), "ATR") },
            indicators.distSma200Pct?.let { GlossaryEntry(stringResource(id = R.string.stock_detail_metric_dist_sma200), "DIST_SMA200") },
            indicators.rangePosition52w?.let { GlossaryEntry(stringResource(id = R.string.stock_detail_metric_52w_range), "52W_RANGE") },
            indicators.rsi?.let { GlossaryEntry(stringResource(id = R.string.stock_detail_metric_rsi), "RSI") },
            indicators.rvol?.let { GlossaryEntry(stringResource(id = R.string.stock_detail_metric_rvol), "RVOL") }
        )
        StockAnalysisGlossaryBottomSheet(title = title, entries = entries, onDismiss = { showGlossary = false })
    }
}

@Composable
private fun MetricStat(value: String, label: String) {
    Column {
        Text(
            text = value,
            style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
            color = MaterialTheme.colorScheme.onSurface
        )
        Text(
            text = label,
            style = MaterialTheme.typography.labelSmall,
            color = LocalPulseColors.current.onSurfaceMuted
        )
    }
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

private val mockIndicators = DomainTechnicalIndicators(
    atrPct = 3.40,
    distSma200Pct = 16.04,
    rangePosition52w = 86.1,
    rsi = 64.2,
    rvol = 0.63
)

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewHeadlineMetricsStripLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        HeadlineMetricsStrip(indicators = mockIndicators)
    }
}

@Preview(name = "Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewHeadlineMetricsStripDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        HeadlineMetricsStrip(indicators = mockIndicators)
    }
}
