package com.marketlabs.pulse.ui.screens.stocks.detail.sections

// Generated by Claude Code.

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.FlowRow
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.stocks.DomainMacro
import com.marketlabs.pulse.ui.components.PulseCard
import com.marketlabs.pulse.ui.components.PulseCardStyle
import com.marketlabs.pulse.ui.components.bottomSheet.GlossaryEntry
import com.marketlabs.pulse.ui.components.bottomSheet.StockAnalysisGlossaryBottomSheet
import com.marketlabs.pulse.ui.screens.stocks.detail.DataCardTitleWithInfo
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme
import java.util.Locale

/**
 * `PulseCard(DATA)` per the spec's token table ("Data cards (levels, fundamentals, macro, setup
 * reasoning)"). `rate_sensitivity` is a confirmed 4-value backend enum (`HIGH_NEGATIVE` /
 * `MODERATE_NEGATIVE` / `POSITIVE` / `NEGLIGIBLE`) -- the `_NEGATIVE` variants mean the stock is
 * hurt by rising rates (bearish-toned), `POSITIVE` means it benefits (bullish-toned), `NEGLIGIBLE`
 * is neutral. `excess_return_63d` exists on the domain model but isn't shown -- the spec names
 * only "excess return 21d".
 */
@Composable
fun Macro(macro: DomainMacro?, modifier: Modifier = Modifier) {
    if (macro == null) return

    val pulseColors = LocalPulseColors.current
    var showGlossary by remember { mutableStateOf(false) }
    val title = stringResource(id = R.string.stock_detail_macro_title)

    PulseCard(style = PulseCardStyle.DATA, modifier = modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            DataCardTitleWithInfo(title = title, onInfoClick = { showGlossary = true })
            // 💡 `benchmark` (e.g. "SPY") was fetched and mapped but never shown -- without it, the
            // Excess Return/Excess EY stats below never said what they were excess *over*.
            macro.benchmark?.let {
                androidx.compose.foundation.layout.Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_tiny)))
                Text(
                    text = stringResource(id = R.string.stock_detail_macro_benchmark_caption, it),
                    style = MaterialTheme.typography.labelSmall,
                    color = pulseColors.onSurfaceMuted
                )
            }
            androidx.compose.foundation.layout.Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_large)))

            // 💡 A fixed 4-item `Row(SpaceBetween)` squeezed "Rate Sens" against its neighbors --
            // its value can be a full word ("MODERATE NEGATIVE"), not a short number like the
            // other three. `FlowRow` with a fixed width per stat (same pattern Fundamentals' own
            // metric grid already uses) lets a long value wrap within its own column, or the whole
            // stat wrap to a second line, instead of cramming every stat into equal-width slots.
            FlowRow(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_xlarge)),
                verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_medium))
            ) {
                macro.riskFree10yPct?.let {
                    MacroStat(
                        value = "${formatDecimal(it)}%",
                        label = stringResource(id = R.string.stock_detail_metric_10y_yield)
                    )
                }
                macro.excessEarningsYieldPct?.let {
                    MacroStat(
                        value = formatSigned(it),
                        label = stringResource(id = R.string.stock_detail_metric_excess_ey),
                        valueColor = signedColor(it, pulseColors)
                    )
                }
                macro.excessReturn21dPct?.let {
                    MacroStat(
                        value = formatSigned(it),
                        label = stringResource(id = R.string.stock_detail_metric_excess_21d),
                        valueColor = signedColor(it, pulseColors)
                    )
                }
                macro.rateSensitivity?.let {
                    MacroStat(
                        value = it.replace('_', ' ').uppercase(Locale.US),
                        label = stringResource(id = R.string.stock_detail_metric_rate_sens),
                        valueColor = rateSensitivityColor(it, pulseColors)
                    )
                }
            }
        }
    }

    if (showGlossary) {
        val entries = listOfNotNull(
            macro.riskFree10yPct?.let { GlossaryEntry(stringResource(id = R.string.stock_detail_metric_10y_yield), "10Y_YIELD") },
            // 💡 EXCESS_EY compares against the 10-year Treasury yield (the risk-free rate), not
            // against `benchmark` -- it stays on the static glossary definition. `benchmark` only
            // applies to Excess Return 21D below, which is the one figure actually computed
            // relative to it.
            macro.excessEarningsYieldPct?.let { GlossaryEntry(stringResource(id = R.string.stock_detail_metric_excess_ey), "EXCESS_EY") },
            macro.excessReturn21dPct?.let {
                GlossaryEntry(
                    label = stringResource(id = R.string.stock_detail_metric_excess_21d),
                    term = "EXCESS_21D",
                    // 💡 Names the actual benchmark (e.g. "SPY") instead of the static glossary's
                    // generic "its benchmark" -- matches the "vs. SPY" caption under the card title
                    // above. Falls back to that generic definition if `benchmark` is ever null.
                    definitionOverride = macro.benchmark?.let { benchmark ->
                        stringResource(id = R.string.stock_detail_metric_excess_21d_definition, benchmark)
                    }
                )
            },
            macro.rateSensitivity?.let { GlossaryEntry(stringResource(id = R.string.stock_detail_metric_rate_sens), "RATE_SENS") }
        )
        StockAnalysisGlossaryBottomSheet(title = title, entries = entries, onDismiss = { showGlossary = false })
    }
}

@Composable
private fun MacroStat(value: String, label: String, valueColor: Color = MaterialTheme.colorScheme.onSurface) {
    Column(modifier = Modifier.width(dimensionResource(id = R.dimen.detail_stat_width))) {
        Text(
            text = value,
            style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
            color = valueColor
        )
        Text(
            text = label,
            style = MaterialTheme.typography.labelSmall,
            color = LocalPulseColors.current.onSurfaceMuted
        )
    }
}

private fun signedColor(value: Double, pulseColors: com.marketlabs.pulse.ui.theme.PulseColors): Color = when {
    value > 0 -> pulseColors.signalBullishText
    value < 0 -> pulseColors.signalBearishText
    else -> pulseColors.signalNeutralText
}

private fun rateSensitivityColor(rateSensitivity: String, pulseColors: com.marketlabs.pulse.ui.theme.PulseColors): Color =
    when (rateSensitivity.uppercase(Locale.US)) {
        "HIGH_NEGATIVE", "MODERATE_NEGATIVE" -> pulseColors.signalBearishText
        "POSITIVE" -> pulseColors.signalBullishText
        else -> pulseColors.signalNeutralText
    }

private fun formatDecimal(value: Double): String = String.format(Locale.US, "%.2f", value)
private fun formatSigned(value: Double): String = "${if (value >= 0) "+" else ""}${formatDecimal(value)}%"

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

private val mockMacro = DomainMacro(
    benchmark = "SPY",
    riskFree10yPct = 0.47,
    excessEarningsYieldPct = 4.11,
    excessReturn21dPct = 8.24,
    rateSensitivity = "NEGLIGIBLE"
)

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewMacroLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        Macro(macro = mockMacro)
    }
}

@Preview(name = "Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewMacroDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        Macro(macro = mockMacro)
    }
}
