package com.marketlabs.pulse.ui.screens.stocks.detail.sections

// Generated by Claude Code.

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.IntrinsicSize
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.stocks.DomainSetupSignal
import com.marketlabs.pulse.ui.components.PulseCard
import com.marketlabs.pulse.ui.components.PulseCardStyle
import com.marketlabs.pulse.ui.components.bottomSheet.GlossaryEntry
import com.marketlabs.pulse.ui.components.bottomSheet.StockAnalysisGlossaryBottomSheet
import com.marketlabs.pulse.ui.screens.stocks.detail.DataCardTitleWithInfo
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme
import java.util.Locale

/**
 * "Why {technical_setup}" -- `PulseCard(DATA)` per the spec, from `setup_confirming` +
 * `setup_conflicting`. Renders nothing if both `setupConfirming` and `setupConflicting` are
 * null/empty (the whole point of a "why" card is having something to confirm/conflict with).
 * `setupConfidence`/`setupNetBias` render as small dark badges next to the title even when the
 * confirms/conflicts lists are present but one of the two scores is null -- they're independent
 * pieces of data, not derived from the list contents.
 *
 * 2026-09-06 backend change: each entry is now a [DomainSetupSignal] (`label`/`meaning`/
 * `direction`), not a plain string -- `meaning` is a plain-English explanation of `label`, the
 * same "explanatory style" `condition_labels` already established (`SignalConditions.kt`'s
 * `CategoryGroup`). Mirrors that exact interaction here: `label` renders in the row's existing
 * position (no change from before), and tapping the row toggles `meaning` open as a smaller
 * caption beneath it, rather than always showing it and crowding an already-dense card.
 */
@Composable
fun SetupReasoning(
    technicalSetup: String?,
    setupConfidence: Int?,
    setupNetBias: Int?,
    setupConfirming: List<DomainSetupSignal>?,
    setupConflicting: List<DomainSetupSignal>?,
    modifier: Modifier = Modifier
) {
    val confirming = setupConfirming.orEmpty()
    val conflicting = setupConflicting.orEmpty()
    if (confirming.isEmpty() && conflicting.isEmpty()) return

    val pulseColors = LocalPulseColors.current
    var showGlossary by remember { mutableStateOf(false) }
    var expandedLabels by remember { mutableStateOf(emptySet<String>()) }
    val title = stringResource(
        id = R.string.stock_detail_why_setup,
        (technicalSetup ?: "").replace('_', ' ').uppercase(Locale.US)
    )

    PulseCard(style = PulseCardStyle.DATA, modifier = modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                DataCardTitleWithInfo(title = title, onInfoClick = { showGlossary = true })
                Spacer(modifier = Modifier.weight(1f))
                setupConfidence?.let {
                    MetricBadge(value = it.toString(), label = stringResource(id = R.string.stock_detail_conf_label))
                    Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_small)))
                }
                setupNetBias?.let {
                    val biasColor = when {
                        it > 0 -> pulseColors.signalBullishText
                        it < 0 -> pulseColors.signalBearishText
                        else -> pulseColors.signalNeutralText
                    }
                    MetricBadge(
                        value = if (it > 0) "+$it" else it.toString(),
                        label = stringResource(id = R.string.stock_detail_bias_label),
                        valueColor = biasColor
                    )
                }
            }

            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_large)))

            val toggleLabel = { text: String ->
                expandedLabels = if (expandedLabels.contains(text)) expandedLabels - text else expandedLabels + text
            }

            Column(verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_medium))) {
                confirming.forEach { signal ->
                    val text = signal.label ?: return@forEach
                    ReasoningRow(
                        label = stringResource(id = R.string.stock_detail_confirms_label),
                        text = text,
                        meaning = signal.meaning,
                        isExpanded = expandedLabels.contains(text),
                        onToggle = { toggleLabel(text) },
                        barColor = pulseColors.signalBullishText
                    )
                }
                conflicting.forEach { signal ->
                    val text = signal.label ?: return@forEach
                    ReasoningRow(
                        label = stringResource(id = R.string.stock_detail_conflicts_label),
                        text = text,
                        meaning = signal.meaning,
                        isExpanded = expandedLabels.contains(text),
                        onToggle = { toggleLabel(text) },
                        barColor = pulseColors.signalWarningText
                    )
                }
            }
        }
    }

    if (showGlossary) {
        val entries = listOfNotNull(
            setupConfidence?.let { GlossaryEntry(stringResource(id = R.string.stock_detail_conf_label), "CONF") },
            setupNetBias?.let { GlossaryEntry(stringResource(id = R.string.stock_detail_bias_label), "BIAS") }
        )
        StockAnalysisGlossaryBottomSheet(title = title, entries = entries, onDismiss = { showGlossary = false })
    }
}

@Composable
private fun MetricBadge(value: String, label: String, valueColor: Color = MaterialTheme.colorScheme.onSurface) {
    val pulseColors = LocalPulseColors.current

    Row(
        verticalAlignment = Alignment.CenterVertically,
        modifier = Modifier
            .background(pulseColors.surfaceTinted, RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_pill)))
            .padding(
                horizontal = dimensionResource(id = R.dimen.padding_medium),
                vertical = dimensionResource(id = R.dimen.padding_small)
            )
    ) {
        Text(text = value, style = MaterialTheme.typography.labelMedium.copy(fontWeight = FontWeight.Bold), color = valueColor)
        Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_tiny)))
        Text(text = label, style = MaterialTheme.typography.labelSmall, color = pulseColors.onSurfaceMuted)
    }
}

/**
 * `meaning`, when present, is only ever shown on tap -- toggled by [onToggle]. Was the exact same
 * whole-row-clickable-with-no-visual-hint interaction `SignalConditions.kt`'s `CategoryGroup` still
 * uses for `condition_labels`' own `meaning` field -- both were reported not obviously tappable
 * (nothing distinguishes an expandable row from a plain one). Fixed here (not yet in
 * `SignalConditions.kt`, which has the identical gap -- flagged, not silently changed) with a
 * trailing up/down chevron (`ic_arrow_up`/`ic_arrow_down`, same in-place-expand-toggle icon
 * `SynthesisExpandableHeroSample`/every other reveal-more-of-this-card control in the app uses,
 * per `compose-conventions.md`'s "See more" section distinguishing this from a navigate-away
 * chevron), shown ONLY when `meaning != null` -- a row with nothing to reveal isn't clickable and
 * doesn't show the icon, so the affordance never lies about what tapping does. The expanded caption
 * is indented to align under [text], not under the bar/[label] columns, so it reads as elaborating
 * on the reasoning text specifically.
 */
@Composable
private fun ReasoningRow(
    label: String,
    text: String,
    meaning: String?,
    isExpanded: Boolean,
    onToggle: () -> Unit,
    barColor: Color
) {
    val pulseColors = LocalPulseColors.current
    val textIndent = dimensionResource(id = R.dimen.border_medium) +
        dimensionResource(id = R.dimen.padding_medium) +
        dimensionResource(id = R.dimen.setup_reasoning_label_width) +
        dimensionResource(id = R.dimen.padding_medium)

    Column(
        modifier = if (meaning != null) Modifier.clickable(onClick = onToggle) else Modifier
    ) {
        Row(modifier = Modifier.height(IntrinsicSize.Min)) {
            ReasoningBar(barColor)
            Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_medium)))
            Text(
                text = label,
                style = MaterialTheme.typography.labelSmall.copy(fontWeight = FontWeight.Bold),
                color = barColor,
                modifier = Modifier.width(dimensionResource(id = R.dimen.setup_reasoning_label_width))
            )
            Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_medium)))
            Text(
                text = text,
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurface,
                modifier = Modifier.weight(1f)
            )
            if (meaning != null) {
                Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_small)))
                Icon(
                    painter = painterResource(id = if (isExpanded) R.drawable.ic_arrow_up else R.drawable.ic_arrow_down),
                    // 💡 Decorative, null on purpose -- same reasoning GlossaryChevron uses: the
                    // row's own reasoning text is already what a screen reader announces for this
                    // tap target, a second "arrow up/down" announcement on top adds nothing.
                    contentDescription = null,
                    tint = pulseColors.onSurfaceMuted,
                    modifier = Modifier.size(dimensionResource(id = R.dimen.icon_size_small))
                )
            }
        }
        if (isExpanded && meaning != null) {
            Text(
                text = meaning,
                style = MaterialTheme.typography.bodySmall,
                color = pulseColors.onSurfaceMuted,
                modifier = Modifier.padding(
                    top = dimensionResource(id = R.dimen.padding_small),
                    start = textIndent
                )
            )
        }
    }
}

@Composable
private fun ReasoningBar(color: Color) {
    Box(
        modifier = Modifier
            .width(dimensionResource(id = R.dimen.border_medium))
            .fillMaxHeight()
            .background(color)
    )
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewSetupReasoningLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        SetupReasoning(
            technicalSetup = "MEAN_REVERSION",
            setupConfidence = 100,
            setupNetBias = 80,
            setupConfirming = listOf(
                DomainSetupSignal(
                    label = "MACD bullish, crossed 5 sessions ago",
                    meaning = "MACD's signal line turned up 5 sessions ago, marking a shift in short-term momentum.",
                    direction = "BULLISH"
                ),
                DomainSetupSignal(label = "Price above 200-day (16.04%)", direction = "BULLISH")
            ),
            setupConflicting = listOf(
                DomainSetupSignal(
                    label = "Up/down volume 0.85",
                    meaning = "Down-day volume has outpaced up-day volume recently, a mild headwind for the bullish case.",
                    direction = "BEARISH"
                )
            )
        )
    }
}

@Preview(name = "Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewSetupReasoningDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        SetupReasoning(
            technicalSetup = "MEAN_REVERSION",
            setupConfidence = 100,
            setupNetBias = 80,
            setupConfirming = listOf(
                DomainSetupSignal(
                    label = "MACD bullish, crossed 5 sessions ago",
                    meaning = "MACD's signal line turned up 5 sessions ago, marking a shift in short-term momentum.",
                    direction = "BULLISH"
                ),
                DomainSetupSignal(label = "Price above 200-day (16.04%)", direction = "BULLISH")
            ),
            setupConflicting = listOf(
                DomainSetupSignal(
                    label = "Up/down volume 0.85",
                    meaning = "Down-day volume has outpaced up-day volume recently, a mild headwind for the bullish case.",
                    direction = "BEARISH"
                )
            )
        )
    }
}
