package com.marketlabs.pulse.ui.screens.stocks.detail.sections

// Generated by Claude Code.

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.stocks.DomainTechnicalIndicators
import com.marketlabs.pulse.ui.components.PulseCard
import com.marketlabs.pulse.ui.components.PulseCardStyle
import com.marketlabs.pulse.ui.components.bottomSheet.GlossaryEntry
import com.marketlabs.pulse.ui.components.bottomSheet.StockAnalysisGlossaryBottomSheet
import com.marketlabs.pulse.ui.screens.stocks.detail.DataCardTitleWithInfo
import com.marketlabs.pulse.ui.screens.stocks.detail.StatGrid
import com.marketlabs.pulse.ui.screens.stocks.detail.StatItem
import com.marketlabs.pulse.ui.theme.MarketPulseTheme
import java.util.Locale
import kotlin.math.abs

/**
 * The 20/50/200-day SMA stat card on Stock Detail's Technicals tab -- same shape (and the same
 * `StatGrid`/`DataCardTitleWithInfo` building blocks) as Dashboard's own SMA card on
 * `AssetDetailScreen`, so a reader sees the identical presentation whether they're looking at a
 * Dashboard asset or a tracked stock. The value nearest `currentPrice` is highlighted in
 * `colorScheme.primary`, same "which average is price actually hugging right now" cue Dashboard's
 * card gives. Unlike Dashboard's `AssetOverview` (which has its own `sma20/50/200` fields fed by a
 * separate pipeline), this reads `DomainTechnicalIndicators.sma20/50/200` -- already on the stock
 * detail model, just never rendered anywhere until now (only their `distSma*Pct` derived siblings
 * were shown, in `HeadlineMetricsStrip`/`MomentumAndTrend`). Renders nothing when `indicators` is
 * null or none of its three SMA fields are set (a symbol whose EOD run hasn't backfilled these yet).
 */
private enum class SmaPeriod { TWENTY, FIFTY, TWO_HUNDRED }

@Composable
fun SmaCard(indicators: DomainTechnicalIndicators?, currentPrice: Double?, modifier: Modifier = Modifier) {
    if (indicators == null) return
    val sma20 = indicators.sma20
    val sma50 = indicators.sma50
    val sma200 = indicators.sma200
    if (sma20 == null && sma50 == null && sma200 == null) return

    var showGlossary by remember { mutableStateOf(false) }
    val title = stringResource(id = R.string.stock_detail_sma_title)

    val smaDistances = listOfNotNull(
        sma20?.let { SmaPeriod.TWENTY to abs((currentPrice ?: 0.0) - it) },
        sma50?.let { SmaPeriod.FIFTY to abs((currentPrice ?: 0.0) - it) },
        sma200?.let { SmaPeriod.TWO_HUNDRED to abs((currentPrice ?: 0.0) - it) }
    )
    val nearestSma = if (currentPrice != null) smaDistances.minByOrNull { it.second }?.first else null

    PulseCard(style = PulseCardStyle.DATA, modifier = modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            DataCardTitleWithInfo(title = title, onInfoClick = { showGlossary = true })
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_large)))

            StatGrid(
                stats = listOf(
                    StatItem(
                        value = sma20?.let { "$${String.format(Locale.US, "%.2f", it)}" } ?: "--",
                        label = stringResource(id = R.string.stock_detail_sma_20),
                        valueColor = if (nearestSma == SmaPeriod.TWENTY) MaterialTheme.colorScheme.primary else null
                    ),
                    StatItem(
                        value = sma50?.let { "$${String.format(Locale.US, "%.2f", it)}" } ?: "--",
                        label = stringResource(id = R.string.stock_detail_sma_50),
                        valueColor = if (nearestSma == SmaPeriod.FIFTY) MaterialTheme.colorScheme.primary else null
                    ),
                    StatItem(
                        value = sma200?.let { "$${String.format(Locale.US, "%.2f", it)}" } ?: "--",
                        label = stringResource(id = R.string.stock_detail_sma_200),
                        valueColor = if (nearestSma == SmaPeriod.TWO_HUNDRED) MaterialTheme.colorScheme.primary else null
                    )
                )
            )
        }
    }

    if (showGlossary) {
        val entries = listOfNotNull(
            sma20?.let { GlossaryEntry(stringResource(id = R.string.stock_detail_sma_20), "SMA20") },
            sma50?.let { GlossaryEntry(stringResource(id = R.string.stock_detail_sma_50), "SMA50") },
            sma200?.let { GlossaryEntry(stringResource(id = R.string.stock_detail_sma_200), "SMA200") }
        )
        StockAnalysisGlossaryBottomSheet(title = title, entries = entries, onDismiss = { showGlossary = false })
    }
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

private val mockIndicators = DomainTechnicalIndicators(
    sma20 = 268.40,
    sma50 = 255.10,
    sma200 = 236.75
)

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewSmaCardLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        SmaCard(indicators = mockIndicators, currentPrice = 274.48)
    }
}

@Preview(name = "Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewSmaCardDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        SmaCard(indicators = mockIndicators, currentPrice = 274.48)
    }
}
