package com.marketlabs.pulse.ui.screens.stocks.detail.sections

// Generated by Claude Code.

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.ui.components.PulseCard
import com.marketlabs.pulse.ui.components.PulseCardStyle
import com.marketlabs.pulse.ui.components.widgets.CardEyebrowLabel
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme

/**
 * `PulseCard(SYNTHESIS)` from `detail.technicalRead`. Originally named/labeled "Plain Read," but
 * the backend's own prompt schema (`analysisPrompt.ts`) draws a deliberate line between two
 * separate fields: `plain_read` ("no jargon, for a non-trader") and `technical_read` ("dense with
 * figures, indicator names fine") -- the opposite of plain. `StockDetail` only carries
 * `technicalRead` (the real `plain_read` field lives on `StockPreview`, backing the list card's
 * prose instead), so labeling this section "Plain Read" was describing the wrong field's intent.
 * Renamed to match what it actually is.
 *
 * Header is [CardEyebrowLabel] (the app-wide "ai style card" family -- Market Signal/Today's
 * Read/Insights' Digest), not Stock Detail's own `SynthesisCardHeader` -- moved 2026-09-05 as the
 * first of this screen's SYNTHESIS cards to converge on that convention; see
 * `docs/theming-system/card-heading-conventions.md` for the norm going forward.
 */
@Composable
fun TechnicalRead(technicalRead: String?, modifier: Modifier = Modifier) {
    if (technicalRead == null) return
    val pulseColors = LocalPulseColors.current

    PulseCard(style = PulseCardStyle.SYNTHESIS, modifier = modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            CardEyebrowLabel(
                text = stringResource(id = R.string.stock_detail_technical_read_title),
                color = pulseColors.accentPrimary
            )
            androidx.compose.foundation.layout.Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_medium)))
            Text(
                text = technicalRead,
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurface
            )
        }
    }
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

private const val MOCK_TEXT = "Amazon's stock sits at \$274.48, trading 16.04% above its 200-day average, while its cash flow yield of 0.78% is barely above the 0.47% risk-free rate."

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewTechnicalReadLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        TechnicalRead(technicalRead = MOCK_TEXT)
    }
}

@Preview(name = "Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewTechnicalReadDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        TechnicalRead(technicalRead = MOCK_TEXT)
    }
}
