package com.marketlabs.pulse.ui.screens.stocks.detail.sections

// Generated by Claude Code.

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.IntrinsicSize
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.stocks.DomainWatchItem
import com.marketlabs.pulse.ui.components.widgets.SignalPill
import com.marketlabs.pulse.ui.screens.stocks.detail.SectionDividerLabel
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme

/**
 * "What to watch" -- the 5 `watch_list` items, sorted HIGH → MEDIUM → LOW (defensive resort here;
 * the backend already writes them in this order, but nothing guarantees that stays true). Only
 * `HIGH` items get the colored left-border highlight and `signal.warning` treatment per the spec's
 * token table ("Warning chips (WatchList HIGH items) → signal.warning.*"); `MEDIUM`/`LOW` aren't
 * assigned a token there, so this uses the same `signal.warning` family at plain (unbordered)
 * weight for `MEDIUM` and the neutral tokens for `LOW` -- the simplest scheme that still reads as
 * 3 distinct urgency levels without inventing a new token.
 */
@Composable
fun WatchList(items: List<DomainWatchItem>?, modifier: Modifier = Modifier) {
    val sorted = items.orEmpty().sortedBy { it.urgency.urgencyRank() }
    if (sorted.isEmpty()) return

    Column(modifier = modifier.fillMaxWidth()) {
        SectionDividerLabel(title = stringResource(id = R.string.stock_detail_what_to_watch_title))
        Spacer()
        Column(verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_medium))) {
            sorted.forEach { item -> WatchListRow(item) }
        }
    }
}

private fun String?.urgencyRank(): Int = when (this?.uppercase()) {
    "HIGH" -> 0
    "MEDIUM" -> 1
    "LOW" -> 2
    else -> 3
}

@Composable
private fun WatchListRow(item: DomainWatchItem) {
    val pulseColors = LocalPulseColors.current
    val isHigh = item.urgency?.uppercase() == "HIGH"
    val (pillColor, textColor) = when (item.urgency?.uppercase()) {
        "HIGH", "MEDIUM" -> pulseColors.signalWarningPill to pulseColors.signalWarningText
        else -> pulseColors.signalNeutralPill to pulseColors.signalNeutralText
    }
    val urgencyLabel = when (item.urgency?.uppercase()) {
        "HIGH" -> stringResource(id = R.string.watch_urgency_high)
        "MEDIUM" -> stringResource(id = R.string.watch_urgency_medium)
        else -> stringResource(id = R.string.watch_urgency_low)
    }

    Surface(
        color = pulseColors.surfaceTinted,
        shape = RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_small))
    ) {
        Row(modifier = Modifier.height(IntrinsicSize.Min)) {
            if (isHigh) {
                Box(
                    modifier = Modifier
                        .width(dimensionResource(id = R.dimen.border_medium))
                        .fillMaxHeight()
                        .background(pulseColors.signalWarningText)
                )
            }
            Row(
                verticalAlignment = Alignment.CenterVertically,
                modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_medium))
            ) {
                SignalPill(text = urgencyLabel, pillColor = pillColor, contentColor = textColor)
                androidx.compose.foundation.layout.Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_medium)))
                item.text?.let {
                    Text(
                        text = it,
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onSurface,
                        modifier = Modifier.weight(1f)
                    )
                }
            }
        }
    }
}

@Composable
private fun Spacer() {
    androidx.compose.foundation.layout.Spacer(modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_medium)))
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

private val mockWatchItems = listOf(
    DomainWatchItem(kind = "LEVEL_DISTANCE", text = "Resistance at \$274.75 is 0.1% away — about 0.0 typical daily moves.", urgency = "HIGH"),
    DomainWatchItem(kind = "LEVEL_DISTANCE", text = "Support at \$255.19 is 7.0% away, about 2.1 typical daily moves.", urgency = "MEDIUM"),
    DomainWatchItem(kind = "LEVEL_DISTANCE", text = "The 200-day average at \$236.54 is 13.8% away, about 4.1 typical daily moves.", urgency = "LOW")
)

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewWatchListLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        WatchList(items = mockWatchItems)
    }
}

@Preview(name = "Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewWatchListDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        WatchList(items = mockWatchItems)
    }
}
