package com.marketlabs.pulse.ui.screens.stocks.detail.sections

// Generated by Claude Code.

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.stocks.DomainWatchItem
import com.marketlabs.pulse.ui.components.PulseCard
import com.marketlabs.pulse.ui.components.PulseCardStyle
import com.marketlabs.pulse.ui.components.widgets.SignalPill
import com.marketlabs.pulse.ui.screens.stocks.detail.DataCardSectionHeader
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme

/**
 * "What to watch" -- the 5 `watch_list` items, sorted HIGH → MEDIUM → LOW (defensive resort here;
 * the backend already writes them in this order, but nothing guarantees that stays true). Urgency
 * reads entirely from the `SignalPill` per row now (`signal.warning` for HIGH/MEDIUM, neutral for
 * LOW) -- no separate colored left-border box for HIGH items, same call Summary's Macro Mix made
 * when it dropped its own accent-tinted left-rail.
 *
 * One `PulseCard(DATA)` for the whole list, header inside (`DataCardSectionHeader`), each row its
 * own padded entry separated by a full-width divider -- Macro Mix's merged-card structure exactly,
 * not a tinted `Surface` per row. No cards (or card-like tinted boxes) nested inside this one.
 */
@Composable
fun WatchList(items: List<DomainWatchItem>?, modifier: Modifier = Modifier) {
    val sorted = items.orEmpty().sortedBy { it.urgency.urgencyRank() }
    if (sorted.isEmpty()) return

    PulseCard(style = PulseCardStyle.DATA, modifier = modifier.fillMaxWidth()) {
        Column {
            DataCardSectionHeader(title = stringResource(id = R.string.stock_detail_what_to_watch_title))
            sorted.forEachIndexed { index, item ->
                WatchListRow(item, modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large)))
                if (index != sorted.lastIndex) {
                    HorizontalDivider(
                        color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.1f),
                        thickness = dimensionResource(id = R.dimen.border_thin)
                    )
                }
            }
        }
    }
}

private fun String?.urgencyRank(): Int = when (this?.uppercase()) {
    "HIGH" -> 0
    "MEDIUM" -> 1
    "LOW" -> 2
    else -> 3
}

@Composable
private fun WatchListRow(item: DomainWatchItem, modifier: Modifier = Modifier) {
    val pulseColors = LocalPulseColors.current
    val (pillColor, textColor) = when (item.urgency?.uppercase()) {
        "HIGH", "MEDIUM" -> pulseColors.signalWarningPill to pulseColors.signalWarningText
        else -> pulseColors.signalNeutralPill to pulseColors.signalNeutralText
    }
    val urgencyLabel = when (item.urgency?.uppercase()) {
        "HIGH" -> stringResource(id = R.string.watch_urgency_high)
        "MEDIUM" -> stringResource(id = R.string.watch_urgency_medium)
        else -> stringResource(id = R.string.watch_urgency_low)
    }

    Row(verticalAlignment = Alignment.CenterVertically, modifier = modifier) {
        SignalPill(text = urgencyLabel, pillColor = pillColor, contentColor = textColor)
        androidx.compose.foundation.layout.Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_medium)))
        item.text?.let {
            Text(
                text = it,
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurface,
                modifier = Modifier.weight(1f)
            )
        }
    }
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

private val mockWatchItems = listOf(
    DomainWatchItem(kind = "LEVEL_DISTANCE", text = "Resistance at \$274.75 is 0.1% away — about 0.0 typical daily moves.", urgency = "HIGH"),
    DomainWatchItem(kind = "LEVEL_DISTANCE", text = "Support at \$255.19 is 7.0% away, about 2.1 typical daily moves.", urgency = "MEDIUM"),
    DomainWatchItem(kind = "LEVEL_DISTANCE", text = "The 200-day average at \$236.54 is 13.8% away, about 4.1 typical daily moves.", urgency = "LOW")
)

@Preview(name = "Light", showBackground = true)
@Composable
private fun PreviewWatchListLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        WatchList(items = mockWatchItems)
    }
}

@Preview(name = "Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewWatchListDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        WatchList(items = mockWatchItems)
    }
}
