package com.marketlabs.pulse.ui.screens.stocks.views

// Generated by Claude Code.

import android.content.Intent
import android.net.Uri
import androidx.compose.foundation.background
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.FilterChip
import androidx.compose.material3.FilterChipDefaults
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.stocks.DomainBattlegroundLevels
import com.marketlabs.pulse.storage.model.stocks.DomainExecutiveThesis
import com.marketlabs.pulse.storage.model.stocks.DomainStockNewsItem
import com.marketlabs.pulse.ui.theme.PulseStatusColors
import dev.jeziellago.compose.markdowntext.MarkdownText

/**
 * AI-authored macro/order-flow narrative for a single tracked symbol, rendered as Markdown
 * (per `stockAnalysisEngine.ts`'s prompt, the AI is instructed to write dense analytical prose —
 * `MarkdownText` gives us bold/line-break support for free, same as `TechnicalSummaryCard`).
 */
@Composable
fun ExecutiveThesisCard(
    thesis: DomainExecutiveThesis,
    modifier: Modifier = Modifier
) {
    val paddingLarge = dimensionResource(id = R.dimen.padding_large)
    val paddingMedium = dimensionResource(id = R.dimen.padding_medium)

    Card(
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.4f)),
        shape = RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_card)),
        modifier = modifier.fillMaxWidth()
    ) {
        Column(modifier = Modifier.padding(paddingLarge)) {
            Text(
                text = stringResource(id = R.string.stock_executive_thesis_title),
                style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
                color = MaterialTheme.colorScheme.primary
            )

            Spacer(modifier = Modifier.height(paddingMedium))

            thesis.macroTransmissionVector?.let { macro ->
                Text(
                    text = stringResource(id = R.string.stock_macro_transmission_label),
                    style = MaterialTheme.typography.labelMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
                MarkdownText(
                    markdown = macro,
                    style = MaterialTheme.typography.bodyMedium.copy(color = MaterialTheme.colorScheme.onSurface)
                )
                Spacer(modifier = Modifier.height(paddingMedium))
            }

            thesis.institutionalOrderFlow?.let { flow ->
                Text(
                    text = stringResource(id = R.string.stock_institutional_flow_label),
                    style = MaterialTheme.typography.labelMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
                MarkdownText(
                    markdown = flow,
                    style = MaterialTheme.typography.bodyMedium.copy(color = MaterialTheme.colorScheme.onSurface)
                )
            }
        }
    }
}

/**
 * Renders the AI-flagged accumulation floor / distribution ceiling price levels plus the
 * accompanying order-book-dynamics narrative — the "key levels" battle map for the symbol.
 */
@Composable
fun BattlegroundLevelsCard(
    levels: DomainBattlegroundLevels,
    modifier: Modifier = Modifier
) {
    val paddingLarge = dimensionResource(id = R.dimen.padding_large)
    val paddingMedium = dimensionResource(id = R.dimen.padding_medium)

    Card(
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.4f)),
        shape = RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_card)),
        modifier = modifier.fillMaxWidth()
    ) {
        Column(modifier = Modifier.padding(paddingLarge)) {
            Text(
                text = stringResource(id = R.string.stock_battleground_title),
                style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
                color = MaterialTheme.colorScheme.primary
            )

            Spacer(modifier = Modifier.height(paddingMedium))

            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                LevelReadout(
                    label = stringResource(id = R.string.stock_accumulation_floor_label),
                    value = levels.accumulationFloor,
                    valueColor = PulseStatusColors.BullishText
                )
                LevelReadout(
                    label = stringResource(id = R.string.stock_distribution_ceiling_label),
                    value = levels.distributionCeiling,
                    valueColor = PulseStatusColors.BearishText
                )
            }

            levels.orderBookDynamics?.let { dynamics ->
                Spacer(modifier = Modifier.height(paddingMedium))
                HorizontalDivider(color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.1f))
                Spacer(modifier = Modifier.height(paddingMedium))

                Text(
                    text = stringResource(id = R.string.stock_order_book_dynamics_label),
                    style = MaterialTheme.typography.labelMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
                Text(
                    text = dynamics,
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurface
                )
            }
        }
    }
}

@Composable
private fun LevelReadout(label: String, value: Double?, valueColor: Color) {
    Column {
        Text(text = label, style = MaterialTheme.typography.labelMedium, color = MaterialTheme.colorScheme.onSurfaceVariant)
        Text(
            text = value?.let { "$${"%.2f".format(it)}" } ?: "--",
            style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
            color = valueColor
        )
    }
}

/**
 * A vertical stack of AI-enriched news items for the symbol — headline, source date, the AI's
 * article synthesis, and the transmission-mechanism narrative, plus a launcher-Intent button to
 * open the source article in the device's default browser.
 */
@Composable
fun StockNewsStreamCard(
    newsItems: List<DomainStockNewsItem>,
    modifier: Modifier = Modifier
) {
    val paddingLarge = dimensionResource(id = R.dimen.padding_large)
    val paddingMedium = dimensionResource(id = R.dimen.padding_medium)

    Card(
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.4f)),
        shape = RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_card)),
        modifier = modifier.fillMaxWidth()
    ) {
        Column(modifier = Modifier.padding(paddingLarge)) {
            Text(
                text = stringResource(id = R.string.stock_news_stream_title),
                style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
                color = MaterialTheme.colorScheme.primary
            )

            newsItems.forEachIndexed { index, item ->
                Spacer(modifier = Modifier.height(paddingMedium))
                if (index > 0) {
                    HorizontalDivider(color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.1f))
                    Spacer(modifier = Modifier.height(paddingMedium))
                }
                StockNewsItemRow(item)
            }
        }
    }
}

@Composable
private fun StockNewsItemRow(item: DomainStockNewsItem) {
    val context = LocalContext.current

    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
        Column(modifier = Modifier.weight(1f)) {
            item.headline?.let {
                Text(text = it, style = MaterialTheme.typography.bodyLarge.copy(fontWeight = FontWeight.SemiBold))
            }
            item.sourceDate?.let {
                Text(text = it, style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
            }
            item.articleSynthesis?.let {
                Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
                Text(text = it, style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onSurface)
            }
            item.transmissionMechanism?.let {
                Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
                Text(
                    text = stringResource(id = R.string.stock_transmission_mechanism_label),
                    style = MaterialTheme.typography.labelMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
                Text(text = it, style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onSurface)
            }
        }

        item.url?.let { url ->
            IconButton(onClick = {
                context.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(url)))
            }) {
                Icon(
                    painter = painterResource(id = R.drawable.ic_open_link),
                    contentDescription = stringResource(id = R.string.stock_open_article_content_description),
                    tint = MaterialTheme.colorScheme.primary
                )
            }
        }
    }
}

/**
 * Horizontally scrollable row of selectable ticker chips (e.g. the tracked Magnificent 7 basket)
 * used to drive which symbol's deep study is currently displayed.
 */
@Composable
fun Mag7SelectorRow(
    symbols: List<String>,
    selectedSymbol: String?,
    onSymbolSelected: (String) -> Unit,
    modifier: Modifier = Modifier
) {
    Row(
        modifier = modifier
            .fillMaxWidth()
            .horizontalScroll(rememberScrollState()),
        horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_small))
    ) {
        symbols.forEach { symbol ->
            val isSelected = symbol == selectedSymbol

            FilterChip(
                selected = isSelected,
                onClick = { onSymbolSelected(symbol) },
                label = { Text(text = symbol) },
                shape = RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_chip)),
                colors = FilterChipDefaults.filterChipColors(
                    selectedContainerColor = PulseStatusColors.BullishBg,
                    selectedLabelColor = PulseStatusColors.BullishText
                )
            )
        }
    }
}

/**
 * Price/change/technical-setup header for `StockAnalysisScreen` — the symbol's current quote
 * plus the AI-classified structural regime badge (ACCUMULATION/DISTRIBUTION/etc.), analogous to
 * the price readout in `AssetCard` but for a single full-screen symbol rather than a grid tile.
 */
@Composable
fun StockPriceHeader(
    symbol: String,
    price: Double?,
    changePercent: Double?,
    technicalSetup: String?,
    modifier: Modifier = Modifier
) {
    val isPositive = (changePercent ?: 0.0) >= 0
    val changeColor = if (isPositive) PulseStatusColors.BullishText else PulseStatusColors.BearishText

    Column(modifier = modifier.fillMaxWidth()) {
        Text(
            text = symbol,
            style = MaterialTheme.typography.headlineSmall.copy(fontWeight = FontWeight.Bold),
            color = MaterialTheme.colorScheme.onSurface
        )

        Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_tiny)))

        Row(verticalAlignment = Alignment.CenterVertically) {
            Text(
                text = price?.let { "$${"%.2f".format(it)}" } ?: "--",
                style = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.Bold),
                color = MaterialTheme.colorScheme.onSurface
            )

            Spacer(modifier = Modifier.width(dimensionResource(id = R.dimen.padding_small)))

            changePercent?.let {
                val sign = if (isPositive) "+" else ""
                Text(
                    text = "$sign${"%.2f".format(it)}%",
                    style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold),
                    color = changeColor
                )
            }
        }

        technicalSetup?.let {
            Spacer(modifier = Modifier.height(dimensionResource(id = R.dimen.padding_small)))
            Surface(
                color = MaterialTheme.colorScheme.surfaceVariant,
                shape = RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_pill))
            ) {
                Text(
                    text = it,
                    style = MaterialTheme.typography.labelSmall.copy(fontWeight = FontWeight.Bold),
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    modifier = Modifier.padding(
                        horizontal = dimensionResource(id = R.dimen.padding_medium),
                        vertical = dimensionResource(id = R.dimen.padding_small)
                    )
                )
            }
        }
    }
}

// ==========================================
// 🖼️ PREVIEWS
// ==========================================

@Preview(showBackground = true, backgroundColor = 0xFF121212)
@Composable
private fun PreviewExecutiveThesisCard() {
    MaterialTheme {
        ExecutiveThesisCard(
            thesis = DomainExecutiveThesis(
                macroTransmissionVector = "Elevated real yields are compressing the multiple on long-duration growth names, with gamma concentration near the 220 strike amplifying intraday moves.",
                institutionalOrderFlow = "Desks are rotating out of short-gamma hedges into passive flows as month-end rebalancing approaches."
            ),
            modifier = Modifier.padding(16.dp)
        )
    }
}

@Preview(showBackground = true, backgroundColor = 0xFF121212)
@Composable
private fun PreviewBattlegroundLevelsCard() {
    MaterialTheme {
        BattlegroundLevelsCard(
            levels = DomainBattlegroundLevels(
                accumulationFloor = 214.50,
                distributionCeiling = 231.75,
                orderBookDynamics = "Dark pool sweeps clustering near the 20-day SMA suggest systematic value algorithms are configured to defend the accumulation floor."
            ),
            modifier = Modifier.padding(16.dp)
        )
    }
}

@Preview(showBackground = true, backgroundColor = 0xFF121212)
@Composable
private fun PreviewStockNewsStreamCard() {
    MaterialTheme {
        StockNewsStreamCard(
            newsItems = listOf(
                DomainStockNewsItem(
                    headline = "Apple unveils new AI chip roadmap",
                    sourceDate = "07/24",
                    url = "https://example.com/article",
                    articleSynthesis = "The company detailed a multi-year silicon roadmap targeting on-device inference gains.",
                    transmissionMechanism = "Improves gross margin trajectory by reducing reliance on third-party foundry premiums."
                )
            ),
            modifier = Modifier.padding(16.dp)
        )
    }
}

@Preview(showBackground = true, backgroundColor = 0xFF121212)
@Composable
private fun PreviewMag7SelectorRow() {
    MaterialTheme {
        Mag7SelectorRow(
            symbols = listOf("AAPL", "MSFT", "GOOGL", "AMZN", "META", "TSLA", "NVDA"),
            selectedSymbol = "AAPL",
            onSymbolSelected = {},
            modifier = Modifier.padding(16.dp)
        )
    }
}

@Preview(showBackground = true, backgroundColor = 0xFF121212)
@Composable
private fun PreviewStockPriceHeader() {
    MaterialTheme {
        StockPriceHeader(
            symbol = "AAPL",
            price = 227.52,
            changePercent = 1.34,
            technicalSetup = "ACCUMULATION",
            modifier = Modifier.padding(16.dp)
        )
    }
}
