package com.marketlabs.pulse.ui.screens.stocks.views

// Generated by Claude Code.

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.foundation.layout.asPaddingValues
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.statusBars
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.stocks.DomainBattlegroundLevels
import com.marketlabs.pulse.storage.model.stocks.DomainExecutiveThesis
import com.marketlabs.pulse.storage.model.stocks.DomainStockNewsItem
import com.marketlabs.pulse.storage.model.stocks.StockAnalysis

/**
 * Full body of the "Analysis" tab: title, `Mag7SelectorRow` chip picker, then the selected
 * symbol's price header + deep-study cards — or a prompt to pick a symbol / an empty state if
 * that symbol hasn't been analyzed yet.
 */
@Composable
fun StockAnalysisScreen(
    trackedSymbols: List<String>,
    selectedSymbol: String?,
    analysis: StockAnalysis?,
    onSymbolSelected: (String) -> Unit,
    scaffoldPadding: PaddingValues
) {
    val statusBarHeight = WindowInsets.statusBars.asPaddingValues().calculateTopPadding()
    val paddingExtraLarge = dimensionResource(id = R.dimen.padding_extra_large)
    val paddingLarge = dimensionResource(id = R.dimen.padding_large)
    val paddingMedium = dimensionResource(id = R.dimen.padding_medium)

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(MaterialTheme.colorScheme.background)
            .verticalScroll(rememberScrollState())
            .padding(
                top = statusBarHeight + paddingExtraLarge,
                bottom = scaffoldPadding.calculateBottomPadding() + paddingExtraLarge,
                start = paddingLarge,
                end = paddingLarge
            ),
        verticalArrangement = Arrangement.spacedBy(paddingExtraLarge)
    ) {
        Text(
            text = stringResource(id = R.string.dashboard_section_stock_analysis),
            style = MaterialTheme.typography.headlineSmall.copy(fontWeight = FontWeight.Bold),
            color = MaterialTheme.colorScheme.onBackground
        )

        Mag7SelectorRow(
            symbols = trackedSymbols,
            selectedSymbol = selectedSymbol,
            onSymbolSelected = onSymbolSelected
        )

        when {
            selectedSymbol == null -> {
                Text(
                    text = stringResource(id = R.string.stock_analysis_select_prompt),
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }

            else -> {
                StockPriceHeader(
                    symbol = selectedSymbol,
                    price = analysis?.price,
                    changePercent = analysis?.changePercent,
                    technicalSetup = analysis?.technicalSetup
                )

                if (analysis == null) {
                    Text(
                        text = stringResource(id = R.string.stock_analysis_empty_state),
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                } else {
                    analysis.executiveThesis?.let { thesis -> ExecutiveThesisCard(thesis = thesis) }
                    analysis.battlegroundLevels?.let { levels -> BattlegroundLevelsCard(levels = levels) }
                    analysis.topNewsStream?.let { news ->
                        if (news.isNotEmpty()) StockNewsStreamCard(newsItems = news)
                    }
                }
            }
        }

        Spacer(modifier = Modifier.height(paddingMedium))
    }
}

@Preview(showBackground = true, backgroundColor = 0xFF121212)
@Composable
private fun PreviewStockAnalysisScreenSelected() {
    MaterialTheme {
        StockAnalysisScreen(
            trackedSymbols = listOf("AAPL", "MSFT", "GOOGL", "AMZN", "META", "TSLA", "NVDA"),
            selectedSymbol = "AAPL",
            analysis = StockAnalysis(
                symbol = "AAPL",
                lastSyncedTimestamp = System.currentTimeMillis(),
                price = 227.52,
                changePercent = 1.34,
                technicalSetup = "ACCUMULATION",
                executiveThesis = DomainExecutiveThesis(
                    macroTransmissionVector = "Elevated real yields are compressing the multiple on long-duration growth names.",
                    institutionalOrderFlow = "Desks are rotating out of short-gamma hedges into passive flows."
                ),
                battlegroundLevels = DomainBattlegroundLevels(
                    accumulationFloor = 214.50,
                    distributionCeiling = 231.75,
                    orderBookDynamics = "Dark pool sweeps clustering near the 20-day SMA."
                ),
                topNewsStream = listOf(
                    DomainStockNewsItem(
                        headline = "Apple unveils new AI chip roadmap",
                        sourceDate = "07/24",
                        url = "https://example.com/article",
                        articleSynthesis = "The company detailed a multi-year silicon roadmap.",
                        transmissionMechanism = "Improves gross margin trajectory."
                    )
                )
            ),
            onSymbolSelected = {},
            scaffoldPadding = PaddingValues(0.dp)
        )
    }
}

@Preview(showBackground = true, backgroundColor = 0xFF121212)
@Composable
private fun PreviewStockAnalysisScreenUnselected() {
    MaterialTheme {
        StockAnalysisScreen(
            trackedSymbols = listOf("AAPL", "MSFT", "GOOGL", "AMZN", "META", "TSLA", "NVDA"),
            selectedSymbol = null,
            analysis = null,
            onSymbolSelected = {},
            scaffoldPadding = PaddingValues(0.dp)
        )
    }
}
