package com.marketlabs.pulse.ui.screens.stocks.views

// Generated by Claude Code.

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.dimensionResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import com.marketlabs.pulse.R
import com.marketlabs.pulse.storage.model.stocks.StockPreview
import com.marketlabs.pulse.ui.common.UiError
import com.marketlabs.pulse.ui.components.PulseCard
import com.marketlabs.pulse.ui.components.PulseCardStyle
import com.marketlabs.pulse.ui.screens.stocks.components.StockPreviewCard
import com.marketlabs.pulse.ui.theme.LocalPulseColors
import com.marketlabs.pulse.ui.theme.MarketPulseTheme

/**
 * The Analysis tab's loaded-data content -- header ("Analysis" + "N TRACKED · ANALYZED AS OF ...")
 * followed by one `StockPreviewCard` per tracked symbol. Mirrors `NewsScreen`'s role exactly: the
 * Route owns the loading/error/empty state machine (same split `IndicatorsRoute`/`NewsRoute`
 * already use), this composable only ever renders the successful, data-present case.
 */
@Composable
fun StockAnalysisScreen(
    previews: List<StockPreview>,
    analyzedAsOf: String?,
    onCardClick: (String) -> Unit,
    scaffoldPadding: PaddingValues,
    modifier: Modifier = Modifier
) {
    val paddingLarge = dimensionResource(id = R.dimen.padding_large)

    // 💡 Top padding uses `scaffoldPadding`'s top component (the Scaffold's own measurement of
    // the global collapsing top bar's real rendered height), same as DashboardScreen/
    // IndicatorsScreen -- the raw status bar inset alone doesn't account for the app's own top
    // bar sitting below it, so content used to start underneath the top bar instead of below it.
    LazyColumn(
        modifier = modifier
            .fillMaxSize()
            .background(MaterialTheme.colorScheme.background),
        contentPadding = PaddingValues(
            top = scaffoldPadding.calculateTopPadding() + paddingLarge,
            bottom = scaffoldPadding.calculateBottomPadding() + paddingLarge,
            start = paddingLarge,
            end = paddingLarge
        ),
        verticalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.padding_large))
    ) {
        item {
            StockAnalysisHeader(trackedCount = previews.size, analyzedAsOf = analyzedAsOf)
        }
        items(previews, key = { it.symbol }) { preview ->
            StockPreviewCard(preview = preview, onClick = { onCardClick(preview.symbol) })
        }
    }
}

@Composable
private fun StockAnalysisHeader(trackedCount: Int, analyzedAsOf: String?) {
    Column {
        Text(
            text = stringResource(id = R.string.market_analysis_screen_title),
            style = MaterialTheme.typography.headlineMedium.copy(fontWeight = FontWeight.Bold),
            color = MaterialTheme.colorScheme.onBackground
        )
        if (analyzedAsOf != null) {
            Text(
                text = stringResource(
                    id = R.string.stock_analysis_subtitle,
                    trackedCount,
                    stringResource(id = R.string.analyzed_at, analyzedAsOf)
                ),
                style = MaterialTheme.typography.labelSmall,
                color = LocalPulseColors.current.onSurfaceMuted,
                modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_micro))
            )
        }
    }
}

/**
 * 3 static placeholder cards while the first page load is in flight. No shimmer animation -- this
 * app has no existing shimmer utility to build on, so this keeps to plain muted rectangles in the
 * same shape a real `StockPreviewCard` would occupy, same spacing as the loaded list.
 */
@Composable
fun StockAnalysisLoadingSkeleton(scaffoldPadding: PaddingValues, modifier: Modifier = Modifier) {
    val paddingLarge = dimensionResource(id = R.dimen.padding_large)

    Column(
        modifier = modifier
            .fillMaxSize()
            .background(MaterialTheme.colorScheme.background)
            .padding(
                // Same `scaffoldPadding.calculateTopPadding()` reasoning as StockAnalysisScreen
                // above -- keeps the skeleton's header at the same vertical position the real
                // header lands at once data loads, so there's no jump on the loading -> loaded swap.
                top = scaffoldPadding.calculateTopPadding() + paddingLarge,
                bottom = scaffoldPadding.calculateBottomPadding() + paddingLarge,
                start = paddingLarge,
                end = paddingLarge
            ),
        verticalArrangement = Arrangement.spacedBy(paddingLarge)
    ) {
        Text(
            text = stringResource(id = R.string.market_analysis_screen_title),
            style = MaterialTheme.typography.headlineMedium.copy(fontWeight = FontWeight.Bold),
            color = MaterialTheme.colorScheme.onBackground
        )
        repeat(3) {
            StockPreviewCardSkeleton()
        }
    }
}

@Composable
private fun StockPreviewCardSkeleton(modifier: Modifier = Modifier) {
    val barColor = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.08f)
    val barShape = RoundedCornerShape(dimensionResource(id = R.dimen.corner_radius_small))

    PulseCard(style = PulseCardStyle.SYNTHESIS, modifier = modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(dimensionResource(id = R.dimen.padding_large))) {
            Box(
                modifier = Modifier
                    .width(dimensionResource(id = R.dimen.stock_preview_skeleton_symbol_width))
                    .height(dimensionResource(id = R.dimen.icon_size_medium))
                    .background(barColor, barShape)
            )
            Box(
                modifier = Modifier
                    .padding(top = dimensionResource(id = R.dimen.padding_small))
                    .width(dimensionResource(id = R.dimen.stock_preview_skeleton_name_width))
                    .height(dimensionResource(id = R.dimen.icon_size_small))
                    .background(barColor, barShape)
            )
            Box(
                modifier = Modifier
                    .padding(top = dimensionResource(id = R.dimen.padding_large))
                    .fillMaxWidth()
                    .height(dimensionResource(id = R.dimen.icon_size_large) * 2)
                    .background(barColor, barShape)
            )
        }
    }
}

@Composable
private fun errorMessageFor(error: UiError): String = when (error) {
    is UiError.Network -> stringResource(id = R.string.stock_analysis_error_network)
    is UiError.Server -> stringResource(id = R.string.stock_analysis_error_server)
    is UiError.Unknown -> stringResource(id = R.string.stock_analysis_error_unknown)
}

@Composable
fun StockAnalysisErrorState(error: UiError, onRetry: () -> Unit, modifier: Modifier = Modifier) {
    Column(
        modifier = modifier
            .fillMaxSize()
            .padding(dimensionResource(id = R.dimen.padding_large)),
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Text(
            text = errorMessageFor(error),
            style = MaterialTheme.typography.bodyLarge,
            color = MaterialTheme.colorScheme.error
        )
        Button(
            onClick = onRetry,
            modifier = Modifier.padding(top = dimensionResource(id = R.dimen.padding_large))
        ) {
            Text(stringResource(id = R.string.action_retry))
        }
    }
}

@Composable
fun StockAnalysisEmptyState(modifier: Modifier = Modifier) {
    Box(
        modifier = modifier.fillMaxSize(),
        contentAlignment = Alignment.Center
    ) {
        Text(
            text = stringResource(id = R.string.stock_analysis_empty_message),
            style = MaterialTheme.typography.bodyLarge,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )
    }
}

// ============================================================================
// 🎨 PREVIEWS
// ============================================================================

private val mockPreviews = listOf(
    StockPreview(symbol = "AMZN", lastSyncedTimestamp = 0L, name = "Amazon.com, Inc.", price = 274.48, changePercent = 0.82, plainRead = "Amazon's stock sits at \$274.48, trading 16.04% above its 200-day average."),
    StockPreview(symbol = "NVDA", lastSyncedTimestamp = 0L, name = "NVIDIA Corporation", price = 178.42, changePercent = 2.31, plainRead = "NVIDIA trades at \$178.42 on 2.1x average volume as it clears its prior high.")
)

@Preview(name = "Loaded — Light", showBackground = true)
@Composable
private fun PreviewStockAnalysisScreenLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        StockAnalysisScreen(previews = mockPreviews, analyzedAsOf = "Aug 07, 6:15 PM", onCardClick = {}, scaffoldPadding = PaddingValues())
    }
}

@Preview(name = "Loaded — Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewStockAnalysisScreenDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        StockAnalysisScreen(previews = mockPreviews, analyzedAsOf = "Aug 07, 6:15 PM", onCardClick = {}, scaffoldPadding = PaddingValues())
    }
}

@Preview(name = "Loading — Light", showBackground = true)
@Composable
private fun PreviewStockAnalysisLoadingLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        StockAnalysisLoadingSkeleton(scaffoldPadding = PaddingValues())
    }
}

@Preview(name = "Loading — Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewStockAnalysisLoadingDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        StockAnalysisLoadingSkeleton(scaffoldPadding = PaddingValues())
    }
}

@Preview(name = "Error — Light", showBackground = true)
@Composable
private fun PreviewStockAnalysisErrorLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        StockAnalysisErrorState(error = UiError.Network(), onRetry = {})
    }
}

@Preview(name = "Error — Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewStockAnalysisErrorDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        StockAnalysisErrorState(error = UiError.Network(), onRetry = {})
    }
}

@Preview(name = "Empty — Light", showBackground = true)
@Composable
private fun PreviewStockAnalysisEmptyLight() {
    MarketPulseTheme(theme = MarketPulseTheme.NAVY) {
        StockAnalysisEmptyState()
    }
}

@Preview(name = "Empty — Dark", showBackground = true, backgroundColor = 0xFF0D0E12)
@Composable
private fun PreviewStockAnalysisEmptyDark() {
    MarketPulseTheme(theme = MarketPulseTheme.LILAC) {
        StockAnalysisEmptyState()
    }
}
