package com.marketlabs.pulse.ui.screens.stocks

// Generated by Claude Code.

import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.marketlabs.pulse.core.stocks.StockAnalysisRepository
import com.marketlabs.pulse.storage.model.stocks.StockPreview
import com.marketlabs.pulse.ui.common.UiError
import com.marketlabs.pulse.ui.common.toUiError
import com.marketlabs.pulse.ui.screens.stocks.StockDetailViewModel.Companion.ARG_SYMBOL
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import javax.inject.Inject

/**
 * 💡 THOUGHT PROCESS:
 * Drives the pushed stock-detail screen. This is the first `SavedStateHandle`-driven ViewModel in
 * this codebase — every other pushed screen either takes no argument (News, whose "which article"
 * signal is hoisted `remember` state in `PulseNavGraph`, not a nav arg) or a directly-encoded path
 * segment read straight off the nav backstack entry in the composable (`webview/{encodedUrl}`).
 * A per-symbol detail screen is a better fit for the standard Hilt pattern: `hiltViewModel()`
 * inside a `composable("${ROUTE_STOCK_DETAIL}/{$ARG_SYMBOL}") { ... }` destination auto-populates
 * `SavedStateHandle[ARG_SYMBOL]` from the route, and a distinct route string per symbol
 * (`stock_detail/AAPL` vs `stock_detail/MSFT`) means Compose Navigation gives each open symbol its
 * own ViewModel instance scoped to that backstack entry — exactly the "no default selection,
 * fetch this one symbol" shape the old chip-selection code had, without needing to hand-roll it.
 *
 * No `SyncManager` here — per `StockAnalysisRepository`'s interface doc, detail is deliberately
 * NOT sync-flag-driven; it's fetched on demand and `refreshDetail` already skips the network when
 * the cached detail's `detailVersion` matches the cached preview's. `onStart()` is kept anyway
 * (rather than firing the fetch from `init {}`) purely so the Route's lifecycle wiring is
 * identical to every other screen's `DisposableEffect` — `onStop()` is intentionally a no-op.
 *
 * Also reads `repository.getStockPreviewsStream()` (already running for the Analysis tab, or
 * spun back up here if the user deep-navigated) filtered down to this one symbol -- `StockDetail`
 * has no `name`/`price`/`change_percent`/`technical_setup`/`regime_at_analysis`/day-over-day-delta
 * fields of its own, only the preview does, so `DetailHeader` and the "what changed since last
 * run" box both read off this same cross-referenced preview rather than the detail stream.
 */
@HiltViewModel
class StockDetailViewModel @Inject constructor(
    private val repository: StockAnalysisRepository,
    savedStateHandle: SavedStateHandle
) : ViewModel() {

    private val symbol: String = checkNotNull(savedStateHandle[ARG_SYMBOL]) {
        "StockDetailViewModel requires a non-null \"$ARG_SYMBOL\" nav argument"
    }

    private val _isLoading = MutableStateFlow(false)
    private val _isRefreshing = MutableStateFlow(false)
    private val _error = MutableStateFlow<UiError?>(null)
    private val _expandedChipIds = MutableStateFlow<Set<String>>(emptySet())
    private val _expandedNewsIds = MutableStateFlow<Set<String>>(emptySet())

    private val matchingPreview: Flow<StockPreview?> = repository.getStockPreviewsStream()
        .map { previews -> previews.firstOrNull { it.symbol == symbol } }

    private val uiFlags: Flow<DetailUiFlags> = combine(
        _isLoading, _isRefreshing, _error, _expandedChipIds, _expandedNewsIds
    ) { isLoading, isRefreshing, error, expandedChipIds, expandedNewsIds ->
        DetailUiFlags(isLoading, isRefreshing, error, expandedChipIds, expandedNewsIds)
    }

    val uiState: StateFlow<StockDetailUiState> = combine(
        repository.getStockDetailStream(symbol),
        matchingPreview,
        uiFlags
    ) { detail, preview, flags ->
        StockDetailUiState(
            symbol = symbol,
            detail = detail,
            preview = preview,
            isLoading = flags.isLoading && detail == null,
            isRefreshing = flags.isRefreshing,
            expandedChipIds = flags.expandedChipIds,
            expandedNewsIds = flags.expandedNewsIds,
            error = flags.error
        )
    }.stateIn(
        scope = viewModelScope,
        started = SharingStarted.WhileSubscribed(5000),
        initialValue = StockDetailUiState(symbol = symbol, isLoading = true)
    )

    /** Called by the UI when the screen becomes visible. Triggers the version-checked fetch described above. */
    fun onStart() {
        fetchDetail(force = false)
    }

    /** No shared listener to stop — present only for parity with every other screen's Route wiring. */
    fun onStop() = Unit

    /** Called by pull-to-refresh — bypasses the cached-version check and always hits the network. */
    fun refresh() {
        fetchDetail(force = true)
    }

    /** Clears any active error (e.g. after a Snackbar is dismissed). */
    fun clearError() {
        _error.value = null
    }

    /** Toggles a SignalConditions chip's expanded (tap-to-show-meaning) state, keyed by its label. */
    fun toggleChipExpanded(chipLabel: String) {
        _expandedChipIds.value = _expandedChipIds.value.toggled(chipLabel)
    }

    /** Toggles a DirectNews item's expanded (tap-to-show-implication) state, keyed by its URL. */
    fun toggleNewsExpanded(newsUrl: String) {
        _expandedNewsIds.value = _expandedNewsIds.value.toggled(newsUrl)
    }

    private fun fetchDetail(force: Boolean) {
        viewModelScope.launch {
            if (force) _isRefreshing.value = true else _isLoading.value = true
            _error.value = null

            val result = repository.refreshDetail(symbol, force)

            if (result.isFailure) {
                _error.value = result.exceptionOrNull().toUiError()
            }

            _isLoading.value = false
            _isRefreshing.value = false
        }
    }

    companion object {
        /** Must match the nav argument name in the `stockAnalysis/{symbol}` route. */
        const val ARG_SYMBOL = "symbol"
    }
}

private data class DetailUiFlags(
    val isLoading: Boolean,
    val isRefreshing: Boolean,
    val error: UiError?,
    val expandedChipIds: Set<String>,
    val expandedNewsIds: Set<String>
)

private fun Set<String>.toggled(id: String): Set<String> =
    if (contains(id)) this - id else this + id
