package com.marketlabs.pulse.ui.screens.stocks

// Generated by Claude Code.

import com.marketlabs.pulse.storage.model.stocks.StockAnalysis

/**
 * UI state for the Analysis bottom-nav tab: the full tracked-symbol list to render as
 * `Mag7SelectorRow` chips, which one is currently selected (null until the user taps a chip — no
 * default, per project convention of leaving selection empty rather than picking an arbitrary one),
 * and the selected symbol's cached `StockAnalysis` once Room has it.
 */
data class StockAnalysisUiState(
    val trackedSymbols: List<String> = emptyList(),
    val selectedSymbol: String? = null,
    val analysis: StockAnalysis? = null,
    val isLoading: Boolean = false,
    val isRefreshing: Boolean = false,
    val errorMessage: String? = null
)
