package com.marketlabs.pulse.ui.screens.stocks

// Generated by Claude Code.

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.marketlabs.pulse.core.stocks.StockAnalysisRepository
import com.marketlabs.pulse.core.sync.SyncManager
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import javax.inject.Inject

/**
 * 💡 THOUGHT PROCESS:
 * Backs the "Analysis" bottom-nav tab. This used to be split across `DashboardViewModel` (chip
 * selection state) and a nav-arg-driven `StockAnalysisViewModel` (pushed detail screen reached by
 * tapping a chip on the Dashboard) — now that the whole feature is its own top-level tab instead
 * of a Dashboard widget, both halves live here together: the tracked-symbol chip row AND the
 * selected symbol's analysis, mirroring `DashboardViewModel`'s `uiState` shape (Room-cached stream
 * + `_isLoading`/`_isRefreshing`/`_errorMessage` combined into one `StateFlow`) but scoped to this
 * tab's own selection instead of nav args.
 */
@HiltViewModel
class StockAnalysisViewModel @Inject constructor(
    private val repository: StockAnalysisRepository,
    private val syncManager: SyncManager
) : ViewModel() {

    private val _selectedSymbol = MutableStateFlow<String?>(null)
    private val _isLoading = MutableStateFlow(false)
    private val _isRefreshing = MutableStateFlow(false)
    private val _errorMessage = MutableStateFlow<String?>(null)

    val uiState: StateFlow<StockAnalysisUiState> = combine(
        repository.getTrackedStocksStream(),
        _selectedSymbol,
        combine(_isLoading, _isRefreshing, _errorMessage) { loading, refreshing, error ->
            Triple(loading, refreshing, error)
        }
    ) { stocks, selectedSymbol, statusTriple ->
        val (loading, refreshing, error) = statusTriple

        StockAnalysisUiState(
            trackedSymbols = stocks.map { it.symbol },
            selectedSymbol = selectedSymbol,
            analysis = stocks.find { it.symbol == selectedSymbol },
            isLoading = loading && stocks.isEmpty(),
            isRefreshing = refreshing,
            errorMessage = error
        )
    }.stateIn(
        scope = viewModelScope,
        started = SharingStarted.WhileSubscribed(5000),
        initialValue = StockAnalysisUiState(isLoading = true)
    )

    fun onStart() {
        syncManager.startListening()
        fetchAnalysis(force = false)
    }

    fun onStop() {
        syncManager.stopListening()
    }

    /** Called when a `Mag7SelectorRow` chip is tapped — swaps which symbol's analysis is displayed. */
    fun selectStock(symbol: String) {
        _selectedSymbol.value = symbol
    }

    fun refresh() {
        fetchAnalysis(force = true)
    }

    fun clearError() {
        _errorMessage.value = null
    }

    private fun fetchAnalysis(force: Boolean) {
        viewModelScope.launch {
            if (force) _isRefreshing.value = true else _isLoading.value = true
            _errorMessage.value = null

            val result = repository.refreshTrackedStocks(force)
            if (result.isFailure) {
                _errorMessage.value = result.exceptionOrNull()?.localizedMessage ?: "Failed to load stock analysis"
            }

            _isLoading.value = false
            _isRefreshing.value = false
        }
    }
}
