package com.marketlabs.pulse.ui.screens.stocks

// Generated by Claude Code.

import androidx.lifecycle.SavedStateHandle
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.marketlabs.pulse.core.charts.ChartsRepository
import com.marketlabs.pulse.core.intraday.IntradayRepository
import com.marketlabs.pulse.core.stocks.StockAnalysisRepository
import com.marketlabs.pulse.storage.model.charts.ChartRange
import com.marketlabs.pulse.storage.model.charts.ChartSeries
import com.marketlabs.pulse.storage.model.charts.isCoveredByHistory
import com.marketlabs.pulse.storage.model.intraday.IntradaySeries
import com.marketlabs.pulse.storage.model.stocks.StockPreview
import com.marketlabs.pulse.ui.common.UiError
import com.marketlabs.pulse.ui.common.toUiError
import com.marketlabs.pulse.ui.screens.stocks.StockDetailViewModel.Companion.ARG_SYMBOL
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.flatMapLatest
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import java.time.LocalDate
import javax.inject.Inject

/**
 * 💡 THOUGHT PROCESS:
 * Drives the pushed stock-detail screen. This is the first `SavedStateHandle`-driven ViewModel in
 * this codebase — every other pushed screen either takes no argument (News, whose "which article"
 * signal is hoisted `remember` state in `PulseNavGraph`, not a nav arg) or a directly-encoded path
 * segment read straight off the nav backstack entry in the composable (`webview/{encodedUrl}`).
 * A per-symbol detail screen is a better fit for the standard Hilt pattern: `hiltViewModel()`
 * inside a `composable("${ROUTE_STOCK_DETAIL}/{$ARG_SYMBOL}") { ... }` destination auto-populates
 * `SavedStateHandle[ARG_SYMBOL]` from the route, and a distinct route string per symbol
 * (`stock_detail/AAPL` vs `stock_detail/MSFT`) means Compose Navigation gives each open symbol its
 * own ViewModel instance scoped to that backstack entry — exactly the "no default selection,
 * fetch this one symbol" shape the old chip-selection code had, without needing to hand-roll it.
 *
 * No `SyncManager` here — per `StockAnalysisRepository`'s interface doc, detail is deliberately
 * NOT sync-flag-driven; it's fetched on demand and `refreshDetail` already skips the network when
 * the cached detail's `detailVersion` matches the cached preview's. `onStart()` is kept anyway
 * (rather than firing the fetch from `init {}`) purely so the Route's lifecycle wiring is
 * identical to every other screen's `DisposableEffect` — `onStop()` is intentionally a no-op.
 *
 * Also reads `repository.getStockPreviewsStream()` (already running for the Analysis tab, or
 * spun back up here if the user deep-navigated) filtered down to this one symbol -- `StockDetail`
 * has no `name`/`price`/`change_percent`/`technical_setup`/`regime_at_analysis`/day-over-day-delta
 * fields of its own, only the preview does, so `DetailHeader` and the "what changed since last
 * run" box both read off this same cross-referenced preview rather than the detail stream.
 */
@OptIn(ExperimentalCoroutinesApi::class)
@HiltViewModel
class StockDetailViewModel @Inject constructor(
    private val repository: StockAnalysisRepository,
    private val chartsRepository: ChartsRepository,
    private val intradayRepository: IntradayRepository,
    savedStateHandle: SavedStateHandle
) : ViewModel() {

    private val symbol: String = checkNotNull(savedStateHandle[ARG_SYMBOL]) {
        "StockDetailViewModel requires a non-null \"$ARG_SYMBOL\" nav argument"
    }

    private val _isLoading = MutableStateFlow(false)
    private val _isRefreshing = MutableStateFlow(false)
    private val _error = MutableStateFlow<UiError?>(null)
    private val _expandedChipIds = MutableStateFlow<Set<String>>(emptySet())
    private val _expandedNewsIds = MutableStateFlow<Set<String>>(emptySet())
    private val _selectedTabIndex = MutableStateFlow(0)
    private val _selectedChartRange = MutableStateFlow(ChartRange.FIVE_DAY)
    private val _isChartLoading = MutableStateFlow(false)

    private val matchingPreview: Flow<StockPreview?> = repository.getStockPreviewsStream()
        .map { previews -> previews.firstOrNull { it.symbol == symbol } }

    private val uiFlags: Flow<DetailUiFlags> = combine(
        _isLoading, _isRefreshing, _error, _expandedChipIds, _expandedNewsIds
    ) { isLoading, isRefreshing, error, expandedChipIds, expandedNewsIds ->
        DetailUiFlags(isLoading, isRefreshing, error, expandedChipIds, expandedNewsIds)
    }

    /**
     * The period chart's own stream — a separate `ChartsRepository` (its own `GET /charts/:symbol`
     * endpoint) re-queried via `flatMapLatest` every time `_selectedChartRange` changes, since each
     * range is cached as its own row (see `ChartsRepository`'s doc comment on why a full series
     * isn't fetched once and sliced client-side). `intradayRepository.getIntradayStream(symbol)`
     * rides along here too -- it's not range-gated (the poll started in `onStart()` runs
     * regardless of which range is selected), but it belongs to this same "period chart section"
     * slice of state, and `IntradayPeriodChart` only ever renders it when `ChartRange.ONE_DAY` is
     * selected.
     *
     * `chartsRepository.getChartStream(symbol, ChartRange.ONE_YEAR)` is read here too, independent
     * of whatever range is actually selected -- it's how `availableChartRanges` learns the
     * symbol's real history depth (see `prefetchHistoryCoverage()`, which is what actually fetches
     * it), so `ChartRangePicker` can hide 6M/YTD/1Y for a recently-listed symbol instead of
     * showing three buttons that'd all render the same fully-clipped series.
     */
    private val chartFlow: Flow<ChartUiSlice> = combine(
        _selectedChartRange.flatMapLatest { range -> chartsRepository.getChartStream(symbol, range) },
        _selectedChartRange,
        _isChartLoading,
        intradayRepository.getIntradayStream(symbol),
        chartsRepository.getChartStream(symbol, ChartRange.ONE_YEAR)
    ) { series, range, isChartLoading, intradaySeries, oneYearSeries ->
        val earliestAvailableDate = oneYearSeries?.points?.firstOrNull()?.date?.let {
            runCatching { LocalDate.parse(it) }.getOrNull()
        }
        ChartUiSlice(
            series = series,
            range = range,
            isLoading = isChartLoading,
            intradaySeries = intradaySeries,
            availableChartRanges = ChartRange.entries.filter { it.isCoveredByHistory(earliestAvailableDate) }
        )
    }

    val uiState: StateFlow<StockDetailUiState> = combine(
        repository.getStockDetailStream(symbol),
        matchingPreview,
        uiFlags,
        _selectedTabIndex,
        chartFlow
    ) { detail, preview, flags, selectedTabIndex, chart ->
        StockDetailUiState(
            symbol = symbol,
            detail = detail,
            preview = preview,
            isLoading = flags.isLoading && detail == null,
            isRefreshing = flags.isRefreshing,
            expandedChipIds = flags.expandedChipIds,
            expandedNewsIds = flags.expandedNewsIds,
            selectedTabIndex = selectedTabIndex,
            chartSeries = chart.series,
            selectedChartRange = chart.range,
            isChartLoading = chart.isLoading,
            intradaySeries = chart.intradaySeries,
            availableChartRanges = chart.availableChartRanges,
            error = flags.error
        )
    }.stateIn(
        scope = viewModelScope,
        started = SharingStarted.WhileSubscribed(5000),
        initialValue = StockDetailUiState(symbol = symbol, isLoading = true)
    )

    /** Called by the UI when the screen becomes visible. Triggers the version-checked fetch described above. */
    fun onStart() {
        fetchDetail(force = false)
        fetchChart(_selectedChartRange.value, force = false)
        prefetchHistoryCoverage()
        // Every stock is intraday-eligible (the backend polls all tracked symbols
        // unconditionally, unlike the dashboard's gated set -- see `StockAnalysisViewModel`'s
        // identical reasoning for the preview-card sparklines), so this always starts polling.
        intradayRepository.trackSymbol(symbol)
    }

    /** Stops this screen's own intraday poll -- the list screen's tracking (if still open) is unaffected. */
    fun onStop() {
        intradayRepository.untrackSymbol(symbol)
    }

    /** Called by pull-to-refresh — bypasses the cached-version check and always hits the network. */
    fun refresh() {
        fetchDetail(force = true)
    }

    /** Clears any active error (e.g. after a Snackbar is dismissed). */
    fun clearError() {
        _error.value = null
    }

    /** Toggles a SignalConditions chip's expanded (tap-to-show-meaning) state, keyed by its label. */
    fun toggleChipExpanded(chipLabel: String) {
        _expandedChipIds.value = _expandedChipIds.value.toggled(chipLabel)
    }

    /** Toggles a DirectNews item's expanded (tap-to-show-implication) state, keyed by its URL. */
    fun toggleNewsExpanded(newsUrl: String) {
        _expandedNewsIds.value = _expandedNewsIds.value.toggled(newsUrl)
    }

    /** Called when the user taps a tab in the pinned `PrimaryTabRow`. Index into `DetailTab.entries`. */
    fun onTabSelected(index: Int) {
        _selectedTabIndex.value = index
    }

    /** Called when the user taps a range button on the period chart's `ChartRangePicker`. */
    fun selectChartRange(range: ChartRange) {
        _selectedChartRange.value = range
        // ONE_DAY has no `/charts/:symbol` fetch to do -- the intraday poll started in onStart()
        // is already live regardless of which range is selected.
        if (range != ChartRange.ONE_DAY) {
            fetchChart(range, force = false)
        }
    }

    private fun fetchChart(range: ChartRange, force: Boolean) {
        viewModelScope.launch {
            _isChartLoading.value = true
            // Deliberately silent on failure -- the chart is a supporting element on this screen,
            // not its main content, so a fetch failure just leaves the last-cached (or empty)
            // series showing rather than surfacing a Snackbar over the whole detail screen.
            chartsRepository.refreshChart(symbol, range, force)
            _isChartLoading.value = false
        }
    }

    /**
     * Silently fetches the widest backend-fetchable range purely to learn how far back this
     * symbol's history actually goes (see `availableChartRanges`' doc comment) -- does not touch
     * `_isChartLoading`, since toggling that here would race with whatever range the user is
     * actually looking at and flash its own loading indicator off prematurely. Skipped when
     * `ONE_YEAR` is already the selected range, since `fetchChart` is already fetching it.
     */
    private fun prefetchHistoryCoverage() {
        if (_selectedChartRange.value == ChartRange.ONE_YEAR) return
        viewModelScope.launch {
            chartsRepository.refreshChart(symbol, ChartRange.ONE_YEAR, force = false)
        }
    }

    private fun fetchDetail(force: Boolean) {
        viewModelScope.launch {
            if (force) _isRefreshing.value = true else _isLoading.value = true
            _error.value = null

            val result = repository.refreshDetail(symbol, force)

            if (result.isFailure) {
                _error.value = result.exceptionOrNull().toUiError()
            }

            _isLoading.value = false
            _isRefreshing.value = false
        }
    }

    companion object {
        /** Must match the nav argument name in the `stockAnalysis/{symbol}` route. */
        const val ARG_SYMBOL = "symbol"
    }
}

private data class DetailUiFlags(
    val isLoading: Boolean,
    val isRefreshing: Boolean,
    val error: UiError?,
    val expandedChipIds: Set<String>,
    val expandedNewsIds: Set<String>
)

private data class ChartUiSlice(
    val series: ChartSeries?,
    val range: ChartRange,
    val isLoading: Boolean,
    val intradaySeries: IntradaySeries?,
    val availableChartRanges: List<ChartRange>
)

private fun Set<String>.toggled(id: String): Set<String> =
    if (contains(id)) this - id else this + id
