package com.marketlabs.pulse.ui.screens.stocks

// Generated by Claude Code.

import com.marketlabs.pulse.storage.model.stocks.StockPreview
import com.marketlabs.pulse.ui.common.UiError

/**
 * Drives the Analysis tab's list/collapsed-card view. `previews` defaults to `emptyList()` rather
 * than staying null — same convention `DashboardUiState.assets` uses — since an empty list and
 * "not loaded yet" are already distinguished by `isLoading`, and the Screen can iterate this
 * directly without a null check.
 *
 * `analyzedAsOf` is the newest `timestamp` across `previews`, pre-formatted to a short "AUG 7"
 * style header line -- computed once in the ViewModel rather than left for the Screen to derive on
 * every recomposition. Null only when `previews` is empty (nothing to derive a date from).
 *
 * `error` is typed (`UiError`) rather than a plain string so the Screen can render distinct retry
 * copy for "no connection" vs. "server rejected it" vs. an unclassified failure.
 *
 * `selectedTabIndex` drives the pinned `PulseTabRow` (Favorites/Stocks/Indices-ETF) the same way
 * `InsightsUiState`/`StockDetailUiState` already do for their own tabs. `favoriteSymbols` is a
 * local-only, per-device preference (`FavoriteStocksRepository`) with no backend counterpart --
 * a tracked symbol can be favorited without changing anything about how it's tracked/analyzed.
 */
data class StockAnalysisUiState(
    val previews: List<StockPreview> = emptyList(),
    val isLoading: Boolean = false,
    val isRefreshing: Boolean = false,
    val analyzedAsOf: String? = null,
    /** Same `market_overview/market_state.is_equity_open` flag the Dashboard's hero card badge
     *  uses -- gates each `StockPreviewCard`'s "LIVE" label to actual regular market hours. */
    val isEquityOpen: Boolean = false,
    val selectedTabIndex: Int = 0,
    val favoriteSymbols: Set<String> = emptySet(),
    val error: UiError? = null
)
