package com.marketlabs.pulse.core.stocks

// Generated by Claude Code.

import com.marketlabs.pulse.storage.model.stocks.StockAnalysis
import kotlinx.coroutines.flow.Flow

/**
 * 💡 THOUGHT PROCESS:
 * Mirrors `IndicatorsRepository`'s Local+Remote-backed shape: the UI observes the Room-cached
 * stream via `getTrackedStocksStream()`, while `refreshTrackedStocks()` (driven by `SyncManager`,
 * pull-to-refresh, or screen entry) is what goes to the network and re-populates the cache.
 * `getLastSyncedTimestamp()`/`updateLastSyncedTimestamp()` give `SyncManager` the same surface it
 * uses to decide whether every other domain needs a fresh fetch.
 */
interface StockAnalysisRepository {

    fun getTrackedStocksStream(): Flow<List<StockAnalysis>>

    suspend fun refreshTrackedStocks(force: Boolean = false): Result<Unit>

    suspend fun getLastSyncedTimestamp(): Long?
    suspend fun updateLastSyncedTimestamp(timestamp: Long)
}
