package com.marketlabs.pulse.utils.extensions

// Generated by Claude Code.

import android.text.format.DateUtils
import java.text.ParseException
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Converts an epoch-millis timestamp into a relative "2 hours ago" / "Just now" style string.
 * Extracted from `NewsScreen.kt`'s `getTimeAgo()` so the Dashboard's news preview cards can render
 * the same relative timestamp format as the full News screen without duplicating the logic.
 */
fun Long.toRelativeTimeString(): String {
    return DateUtils.getRelativeTimeSpanString(
        this,
        System.currentTimeMillis(),
        DateUtils.MINUTE_IN_MILLIS,
        DateUtils.FORMAT_ABBREV_RELATIVE
    ).toString()
}

/**
 * Epoch millis -> "Aug 07, 6:15 PM" -- the "analyzed as of" timestamp format `DashboardScreen`/
 * `IndicatorsScreen`/`NewsScreen`/`SummaryScreen`/`MarketPostureView`/`MarketRisksView` already
 * hand-roll individually via their own local `SimpleDateFormat("MMM dd, h:mm a", ...)`. Pulled out
 * here so the Stock Analysis screens (Preview + Detail) share one definition of that same format
 * rather than adding yet another inline copy -- the older per-screen copies are left alone since
 * touching them isn't part of this change.
 */
fun Long.toAnalyzedAsOfString(): String =
    SimpleDateFormat("MMM dd, h:mm a", Locale.getDefault()).format(Date(this))

/**
 * The backend's `yyyy-MM-dd` date fields (event log dates, forward-call `made_on`/`resolve_date`,
 * news `source_date`, fundamentals' `next_earnings_date`) -- e.g. "2026-07-28" -- rendered as
 * "July 28" for display. Falls back to the original string on a parse failure (including a value
 * that's already human-formatted, e.g. a source that sends "Oct 29" directly) rather than blanking
 * out an otherwise-fine field.
 */
fun String.toLongDateString(): String {
    return try {
        val parsed = SimpleDateFormat("yyyy-MM-dd", Locale.US).parse(this) ?: return this
        SimpleDateFormat("MMMM d", Locale.US).format(parsed)
    } catch (e: ParseException) {
        this
    }
}

/**
 * Same `yyyy-MM-dd` backend date fields as [toLongDateString], but abbreviated ("Sep 4" rather than
 * "September 4") -- the Deep Dive banner/label and the short-interest date stamp both want the
 * shorter form. A sibling function rather than reusing [toLongDateString], which (despite its name
 * suggesting otherwise) actually renders the full month name, not an abbreviation.
 */
fun String.toShortDateString(): String {
    return try {
        val parsed = SimpleDateFormat("yyyy-MM-dd", Locale.US).parse(this) ?: return this
        SimpleDateFormat("MMM d", Locale.US).format(parsed)
    } catch (e: ParseException) {
        this
    }
}

/** Same as [toShortDateString] but with the year appended ("Sep 4, 2026") -- the Deep Dive screen's own header banner shows this fuller form since it's the one place displaying the authoritative last-run date on its own, without a symbol/date context already established elsewhere on screen. */
fun String.toShortDateWithYearString(): String {
    return try {
        val parsed = SimpleDateFormat("yyyy-MM-dd", Locale.US).parse(this) ?: return this
        SimpleDateFormat("MMM d, yyyy", Locale.US).format(parsed)
    } catch (e: ParseException) {
        this
    }
}
