package com.marketlabs.pulse.utils.extensions

// Generated by Claude Code.

import android.text.format.DateUtils
import java.text.ParseException
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Date
import java.util.Locale

/** Checks if a [Calendar] represents today in the local time zone. */
private fun Calendar.isToday(): Boolean {
    val now = Calendar.getInstance()
    return get(Calendar.YEAR) == now.get(Calendar.YEAR) &&
            get(Calendar.DAY_OF_YEAR) == now.get(Calendar.DAY_OF_YEAR)
}

/** Checks if a [Calendar] represents yesterday in the local time zone. */
private fun Calendar.isYesterday(): Boolean {
    val yesterday = Calendar.getInstance().apply { add(Calendar.DAY_OF_YEAR, -1) }
    return get(Calendar.YEAR) == yesterday.get(Calendar.YEAR) &&
            get(Calendar.DAY_OF_YEAR) == yesterday.get(Calendar.DAY_OF_YEAR)
}

/** "Today" / "Yesterday" when this date falls on that local day, otherwise null. */
fun Date.toTodayOrYesterdayLabel(): String? {
    val cal = Calendar.getInstance().apply { time = this@toTodayOrYesterdayLabel }
    return when {
        cal.isToday() -> "Today"
        cal.isYesterday() -> "Yesterday"
        else -> null
    }
}

/**
 * Given a `yyyy-MM-dd` date string, formats it as "Today", "Yesterday", or [formatter] for any other day.
 */
private fun formatRelativeDateString(dateString: String, formatter: (Date) -> String): String {
    return try {
        val parsed = SimpleDateFormat("yyyy-MM-dd", Locale.US).parse(dateString) ?: return dateString
        val cal = Calendar.getInstance().apply { time = parsed }
        when {
            cal.isToday() -> "Today"
            cal.isYesterday() -> "Yesterday"
            else -> formatter(parsed)
        }
    } catch (e: ParseException) {
        dateString
    }
}

/**
 * Converts an epoch-millis timestamp into a relative "2 hours ago" / "Just now" style string.
 * Extracted from `NewsScreen.kt`'s `getTimeAgo()` so the Dashboard's news preview cards can render
 * the same relative timestamp format as the full News screen without duplicating the logic.
 */
fun Long.toRelativeTimeString(): String {
    return DateUtils.getRelativeTimeSpanString(
        this,
        System.currentTimeMillis(),
        DateUtils.MINUTE_IN_MILLIS,
        DateUtils.FORMAT_ABBREV_RELATIVE
    ).toString()
}

/**
 * Epoch millis -> "Today, 6:15 PM" / "Yesterday, 6:15 PM" / "Aug 07, 6:15 PM".
 */
fun Long.toAnalyzedAsOfString(): String {
    val date = Date(this)
    val cal = Calendar.getInstance().apply { time = date }
    val timeFormat = SimpleDateFormat("h:mm a", Locale.getDefault()).format(date)
    return when {
        cal.isToday() -> "Today, $timeFormat"
        cal.isYesterday() -> "Yesterday, $timeFormat"
        else -> SimpleDateFormat("MMM dd, h:mm a", Locale.getDefault()).format(date)
    }
}

/**
 * The backend's `yyyy-MM-dd` date fields -- rendered as "Today", "Yesterday", or "July 28" for display.
 */
fun String.toLongDateString(): String {
    return formatRelativeDateString(this) { date ->
        SimpleDateFormat("MMMM d", Locale.US).format(date)
    }
}

/**
 * Same `yyyy-MM-dd` backend date fields as [toLongDateString], but abbreviated ("Today", "Yesterday", or "Sep 4").
 */
fun String.toShortDateString(): String {
    return formatRelativeDateString(this) { date ->
        SimpleDateFormat("MMM d", Locale.US).format(date)
    }
}

/** Same as [toShortDateString] but with the year appended for other days ("Today", "Yesterday", or "Sep 4, 2026"). */
fun String.toShortDateWithYearString(): String {
    return formatRelativeDateString(this) { date ->
        SimpleDateFormat("MMM d, yyyy", Locale.US).format(date)
    }
}

/** Epoch millis -> "Today", "Yesterday", or "Sep 4, 2026" (date only, no time). */
fun Long.toShortDateWithYearString(): String {
    val date = Date(this)
    return date.toTodayOrYesterdayLabel() ?: SimpleDateFormat("MMM d, yyyy", Locale.US).format(date)
}

/** Returns "from Today", "from Yesterday", or "on Sep 4" for grammatically correct captions. */
fun String.toPrepositionalDateString(): String {
    val dateStr = this.toShortDateString()
    return when (dateStr) {
        "Today" -> "from Today"
        "Yesterday" -> "from Yesterday"
        else -> "on $dateStr"
    }
}
